db.instrument.insertMany([
  {
    instrument_id: 1,
    instrument_type: "Stock",
    instrument_category: "Equity",
    venue: "SET",
    symbol: "CPALL",
    friendly_name: "CPALL",
    logo: "",
    security_type: "Common Stock",
    exchange_timezone: "Aisa/Bangkok",
    country: "TH",
    offset_seconds: -14400,
    is_projected: false,
    trading_unit: "Shares",
    min_bid_unit: "0.01",
    multiplier: "1",
    initial_margin: "30%",
    price_infos: [],
    order_books: [],
    public_trades: [],
    instrument_details: [],
    corporate_actions: [],
    trading_signs: [],
    financials: [],
    fund_performances: [],
    fund_details: [],
    nav_lists: [],
    fund_trade_dates: [],
    indicators: [],
    intermissions: [],
  },
  {
    instrument_id: 2,
    instrument_type: "Stock",
    instrument_category: "Equity",
    venue: "SET",
    symbol: "TISCO",
    friendly_name: "TISCO",
    logo: "",
    security_type: "Common Stock",
    exchange_timezone: "Aisa/Bangkok",
    country: "TH",
    offset_seconds: -14400,
    is_projected: false,
    trading_unit: "Shares",
    min_bid_unit: "0.01",
    multiplier: "1",
    initial_margin: "30%",
    price_infos: [],
    order_books: [],
    public_trades: [],
    instrument_details: [],
    corporate_actions: [],
    trading_signs: [],
    financials: [],
    fund_performances: [],
    fund_details: [],
    nav_lists: [],
    fund_trade_dates: [],
    indicators: [],
    intermissions: [],
  },
  {
    instrument_id: 3,
    instrument_type: "Stock",
    instrument_category: "Derivative",
    venue: "TFEX",
    symbol: "S50M23",
    friendly_name: "",
    logo: "",
    security_type: "",
    exchange_timezone: "Aisa/Bangkok",
    country: "USA",
    offset_seconds: -14400,
    is_projected: false,
    trading_unit: "Shares",
    min_bid_unit: "0.01",
    multiplier: "1",
    initial_margin: "30%",
    price_infos: [],
    order_books: [],
    public_trades: [],
    instrument_details: [],
    corporate_actions: [],
    trading_signs: [],
    financials: [],
    fund_performances: [],
    fund_details: [],
    nav_lists: [],
    fund_trade_dates: [],
    indicators: [],
    intermissions: [],
  },
]);

db.instrument_detail.insertMany([
  {
    instrument_detail_id: 0,
    order_book_id: 65545,
    instrument_id: 65804,
    market_capitalization: null,
    share_free_float: null,
    industry: null,
    sector: null,
    price_to_earnings_ratio: null,
    price_to_book_ratio: null,
    price_to_sales_ratio: null,
    dividend_yield_percent: null,
    ex_dividend_date: null,
    units: null,
    source: null,
    underlying_symbol: null,
    is_clickable: false,
    underlying_venue: null,
    underlying_instrument_type: null,
    underlying_instrument_category: null,
    underlying_logo: null,
    exercise_ratio: null,
    exercise_date: null,
    days_to_exercise: 0,
    direction: null,
    last_trading_date: null,
    days_to_last_trade: 0,
    issuer_series: null,
    foreign_currency: null,
    conversion_ratio: null,
    underlying_price: null,
    open_interest: null,
    contract_size: '1',
    last_nav_per_share: null,
    objective: null,
    asset_class_focus: null,
    expense_ratio_percentage: null,
    strike_price: '0',
    theoretical_price: null,
    implied_volatility_percent: null,
    description: null,
    website: null,
    decimals_in_price: 5,
    decimal_in_strike_price: 0,
    decimal_in_contract_size_pqf: 0,
    instrument: null
  }
])