using Pi.SetMarketData.Application.Abstractions;
using Pi.SetMarketData.Application.Queries.FundPerformance;

namespace Pi.SetMarketData.Application.Interfaces.FundPerformance;

public abstract class GetByIdFundPerformanceRequestAbstractHandler: RequestHandler<GetByIdFundPerformanceRequest, GetByIdFundPerformanceResponse>;