namespace Pi.TfexService.Application.Services.SetTrade;

public record AccountInfo(
    decimal CreditLine,
    decimal ExcessEquity,
    decimal CashBalance,
    decimal Equity,
    decimal TotalMarginRequire,
    decimal TotalMaintenanceMargin,
    decimal TotalForceMargin,
    string? CallForceFlag,
    decimal CallForceMargin,
    decimal LiquidationValue,
    decimal DepositWithdrawal,
    decimal CallForceMarginMM,
    decimal InitialMargin,
    string? ClosingMethod);

public enum SecurityType
{
    Futures = 1,
    Options = 2,
    FuturesFuturesOptionsOptions = 3
}

public enum Currency
{
    THB = 1,
    USD = 2,
    THBThaiBahtUSDUSDollar = 3
}

public record Portfolio(
    string BrokerId,
    string AccountNo,
    string Symbol,
    string Underlying,
    SecurityType SecurityType,
    DateOnly LastTradingDate,
    decimal Multiplier,
    Currency Currency,
    decimal CurrentXrt,
    string AsOfDateXrt,
    bool HasLongPosition,
    int StartLongPosition,
    int ActualLongPosition,
    int AvailableLongPosition,
    decimal StartLongPrice,
    decimal StartLongCost,
    decimal LongAvgPrice,
    decimal LongAvgCost,
    decimal ShortAvgCostThb,
    decimal LongAvgCostThb,
    int OpenLongPosition,
    int CloseLongPosition,
    decimal StartXrtLong,
    decimal StartXrtLongCost,
    decimal AvgXrtLong,
    decimal AvgXrtLongCost,
    bool HasShortPosition,
    int StartShortPosition,
    int ActualShortPosition,
    int AvailableShortPosition,
    decimal StartShortPrice,
    decimal StartShortCost,
    decimal ShortAvgPrice,
    decimal ShortAvgCost,
    int OpenShortPosition,
    int CloseShortPosition,
    decimal StartXrtShort,
    decimal StartXrtShortCost,
    decimal AvgXrtShort,
    decimal AvgXrtShortCost,
    decimal MarketPrice,
    decimal RealizedPl,
    decimal RealizedPlByCost,
    decimal RealizedPlCurrency,
    decimal RealizedPlByCostCurrency,
    decimal ShortAmount,
    decimal LongAmount,
    decimal ShortAmountByCost,
    decimal LongAmountByCost,
    int PriceDigit,
    int SettleDigit,
    decimal LongUnrealizePl,
    decimal LongUnrealizePlByCost,
    decimal LongPercentUnrealizePl,
    decimal LongPercentUnrealizePlByCost,
    decimal LongOptionsValue,
    decimal LongMarketValue,
    decimal ShortUnrealizePl,
    decimal ShortPercentUnrealizePl,
    decimal ShortUnrealizePlByCost,
    decimal ShortPercentUnrealizePlByCost,
    decimal ShortOptionsValue,
    decimal ShortMarketValue,
    decimal LongAvgPriceThb,
    decimal ShortAvgPriceThb,
    decimal ShortAmountCurrency,
    decimal LongAmountCurrency,
    decimal LongMarketValueCurrency,
    decimal ShortMarketValueCurrency,
    decimal LongUnrealizePlCurrency,
    decimal ShortUnrealizePlCurrency,
    decimal LongUnrealizedPlByCostCurrency,
    decimal ShortUnrealizedPlByCostCurrency,
    decimal LongAmountByCostCurrency,
    decimal ShortAmountByCostCurrency
);

public record TotalPortfolio(
    decimal Amount,
    decimal MarketValue,
    decimal AmountByCost,
    decimal UnrealizePl,
    decimal UnrealizePlByCost,
    decimal RealizePl,
    decimal RealizePlByCost,
    decimal PercentUnrealizePl,
    decimal PercentUnrealizePlByCost,
    decimal OptionsValue
);