/*
Pi.Financial.FundService.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package go_client

import (
	"encoding/json"
)

// checks if the PiFinancialClientFundConnextModelAddressForProfileV5 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PiFinancialClientFundConnextModelAddressForProfileV5{}

// PiFinancialClientFundConnextModelAddressForProfileV5 struct for PiFinancialClientFundConnextModelAddressForProfileV5
type PiFinancialClientFundConnextModelAddressForProfileV5 struct {
	No          NullableString `json:"no,omitempty"`
	Floor       NullableString `json:"floor,omitempty"`
	Building    NullableString `json:"building,omitempty"`
	RoomNo      NullableString `json:"roomNo,omitempty"`
	Soi         NullableString `json:"soi,omitempty"`
	Road        NullableString `json:"road,omitempty"`
	Moo         NullableString `json:"moo,omitempty"`
	Subdistrict NullableString `json:"subdistrict,omitempty"`
	District    NullableString `json:"district,omitempty"`
	Province    NullableString `json:"province,omitempty"`
	PostalCode  NullableString `json:"postalCode,omitempty"`
	Country     NullableString `json:"country,omitempty"`
}

// NewPiFinancialClientFundConnextModelAddressForProfileV5 instantiates a new PiFinancialClientFundConnextModelAddressForProfileV5 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPiFinancialClientFundConnextModelAddressForProfileV5() *PiFinancialClientFundConnextModelAddressForProfileV5 {
	this := PiFinancialClientFundConnextModelAddressForProfileV5{}
	return &this
}

// NewPiFinancialClientFundConnextModelAddressForProfileV5WithDefaults instantiates a new PiFinancialClientFundConnextModelAddressForProfileV5 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPiFinancialClientFundConnextModelAddressForProfileV5WithDefaults() *PiFinancialClientFundConnextModelAddressForProfileV5 {
	this := PiFinancialClientFundConnextModelAddressForProfileV5{}
	return &this
}

// GetNo returns the No field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) GetNo() string {
	if o == nil || IsNil(o.No.Get()) {
		var ret string
		return ret
	}
	return *o.No.Get()
}

// GetNoOk returns a tuple with the No field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) GetNoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.No.Get(), o.No.IsSet()
}

// HasNo returns a boolean if a field has been set.
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) HasNo() bool {
	if o != nil && o.No.IsSet() {
		return true
	}

	return false
}

// SetNo gets a reference to the given NullableString and assigns it to the No field.
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) SetNo(v string) {
	o.No.Set(&v)
}

// SetNoNil sets the value for No to be an explicit nil
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) SetNoNil() {
	o.No.Set(nil)
}

// UnsetNo ensures that no value is present for No, not even an explicit nil
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) UnsetNo() {
	o.No.Unset()
}

// GetFloor returns the Floor field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) GetFloor() string {
	if o == nil || IsNil(o.Floor.Get()) {
		var ret string
		return ret
	}
	return *o.Floor.Get()
}

// GetFloorOk returns a tuple with the Floor field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) GetFloorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Floor.Get(), o.Floor.IsSet()
}

// HasFloor returns a boolean if a field has been set.
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) HasFloor() bool {
	if o != nil && o.Floor.IsSet() {
		return true
	}

	return false
}

// SetFloor gets a reference to the given NullableString and assigns it to the Floor field.
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) SetFloor(v string) {
	o.Floor.Set(&v)
}

// SetFloorNil sets the value for Floor to be an explicit nil
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) SetFloorNil() {
	o.Floor.Set(nil)
}

// UnsetFloor ensures that no value is present for Floor, not even an explicit nil
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) UnsetFloor() {
	o.Floor.Unset()
}

// GetBuilding returns the Building field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) GetBuilding() string {
	if o == nil || IsNil(o.Building.Get()) {
		var ret string
		return ret
	}
	return *o.Building.Get()
}

// GetBuildingOk returns a tuple with the Building field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) GetBuildingOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Building.Get(), o.Building.IsSet()
}

// HasBuilding returns a boolean if a field has been set.
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) HasBuilding() bool {
	if o != nil && o.Building.IsSet() {
		return true
	}

	return false
}

// SetBuilding gets a reference to the given NullableString and assigns it to the Building field.
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) SetBuilding(v string) {
	o.Building.Set(&v)
}

// SetBuildingNil sets the value for Building to be an explicit nil
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) SetBuildingNil() {
	o.Building.Set(nil)
}

// UnsetBuilding ensures that no value is present for Building, not even an explicit nil
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) UnsetBuilding() {
	o.Building.Unset()
}

// GetRoomNo returns the RoomNo field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) GetRoomNo() string {
	if o == nil || IsNil(o.RoomNo.Get()) {
		var ret string
		return ret
	}
	return *o.RoomNo.Get()
}

// GetRoomNoOk returns a tuple with the RoomNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) GetRoomNoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RoomNo.Get(), o.RoomNo.IsSet()
}

// HasRoomNo returns a boolean if a field has been set.
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) HasRoomNo() bool {
	if o != nil && o.RoomNo.IsSet() {
		return true
	}

	return false
}

// SetRoomNo gets a reference to the given NullableString and assigns it to the RoomNo field.
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) SetRoomNo(v string) {
	o.RoomNo.Set(&v)
}

// SetRoomNoNil sets the value for RoomNo to be an explicit nil
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) SetRoomNoNil() {
	o.RoomNo.Set(nil)
}

// UnsetRoomNo ensures that no value is present for RoomNo, not even an explicit nil
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) UnsetRoomNo() {
	o.RoomNo.Unset()
}

// GetSoi returns the Soi field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) GetSoi() string {
	if o == nil || IsNil(o.Soi.Get()) {
		var ret string
		return ret
	}
	return *o.Soi.Get()
}

// GetSoiOk returns a tuple with the Soi field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) GetSoiOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Soi.Get(), o.Soi.IsSet()
}

// HasSoi returns a boolean if a field has been set.
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) HasSoi() bool {
	if o != nil && o.Soi.IsSet() {
		return true
	}

	return false
}

// SetSoi gets a reference to the given NullableString and assigns it to the Soi field.
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) SetSoi(v string) {
	o.Soi.Set(&v)
}

// SetSoiNil sets the value for Soi to be an explicit nil
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) SetSoiNil() {
	o.Soi.Set(nil)
}

// UnsetSoi ensures that no value is present for Soi, not even an explicit nil
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) UnsetSoi() {
	o.Soi.Unset()
}

// GetRoad returns the Road field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) GetRoad() string {
	if o == nil || IsNil(o.Road.Get()) {
		var ret string
		return ret
	}
	return *o.Road.Get()
}

// GetRoadOk returns a tuple with the Road field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) GetRoadOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Road.Get(), o.Road.IsSet()
}

// HasRoad returns a boolean if a field has been set.
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) HasRoad() bool {
	if o != nil && o.Road.IsSet() {
		return true
	}

	return false
}

// SetRoad gets a reference to the given NullableString and assigns it to the Road field.
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) SetRoad(v string) {
	o.Road.Set(&v)
}

// SetRoadNil sets the value for Road to be an explicit nil
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) SetRoadNil() {
	o.Road.Set(nil)
}

// UnsetRoad ensures that no value is present for Road, not even an explicit nil
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) UnsetRoad() {
	o.Road.Unset()
}

// GetMoo returns the Moo field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) GetMoo() string {
	if o == nil || IsNil(o.Moo.Get()) {
		var ret string
		return ret
	}
	return *o.Moo.Get()
}

// GetMooOk returns a tuple with the Moo field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) GetMooOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Moo.Get(), o.Moo.IsSet()
}

// HasMoo returns a boolean if a field has been set.
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) HasMoo() bool {
	if o != nil && o.Moo.IsSet() {
		return true
	}

	return false
}

// SetMoo gets a reference to the given NullableString and assigns it to the Moo field.
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) SetMoo(v string) {
	o.Moo.Set(&v)
}

// SetMooNil sets the value for Moo to be an explicit nil
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) SetMooNil() {
	o.Moo.Set(nil)
}

// UnsetMoo ensures that no value is present for Moo, not even an explicit nil
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) UnsetMoo() {
	o.Moo.Unset()
}

// GetSubdistrict returns the Subdistrict field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) GetSubdistrict() string {
	if o == nil || IsNil(o.Subdistrict.Get()) {
		var ret string
		return ret
	}
	return *o.Subdistrict.Get()
}

// GetSubdistrictOk returns a tuple with the Subdistrict field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) GetSubdistrictOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Subdistrict.Get(), o.Subdistrict.IsSet()
}

// HasSubdistrict returns a boolean if a field has been set.
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) HasSubdistrict() bool {
	if o != nil && o.Subdistrict.IsSet() {
		return true
	}

	return false
}

// SetSubdistrict gets a reference to the given NullableString and assigns it to the Subdistrict field.
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) SetSubdistrict(v string) {
	o.Subdistrict.Set(&v)
}

// SetSubdistrictNil sets the value for Subdistrict to be an explicit nil
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) SetSubdistrictNil() {
	o.Subdistrict.Set(nil)
}

// UnsetSubdistrict ensures that no value is present for Subdistrict, not even an explicit nil
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) UnsetSubdistrict() {
	o.Subdistrict.Unset()
}

// GetDistrict returns the District field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) GetDistrict() string {
	if o == nil || IsNil(o.District.Get()) {
		var ret string
		return ret
	}
	return *o.District.Get()
}

// GetDistrictOk returns a tuple with the District field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) GetDistrictOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.District.Get(), o.District.IsSet()
}

// HasDistrict returns a boolean if a field has been set.
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) HasDistrict() bool {
	if o != nil && o.District.IsSet() {
		return true
	}

	return false
}

// SetDistrict gets a reference to the given NullableString and assigns it to the District field.
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) SetDistrict(v string) {
	o.District.Set(&v)
}

// SetDistrictNil sets the value for District to be an explicit nil
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) SetDistrictNil() {
	o.District.Set(nil)
}

// UnsetDistrict ensures that no value is present for District, not even an explicit nil
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) UnsetDistrict() {
	o.District.Unset()
}

// GetProvince returns the Province field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) GetProvince() string {
	if o == nil || IsNil(o.Province.Get()) {
		var ret string
		return ret
	}
	return *o.Province.Get()
}

// GetProvinceOk returns a tuple with the Province field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) GetProvinceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Province.Get(), o.Province.IsSet()
}

// HasProvince returns a boolean if a field has been set.
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) HasProvince() bool {
	if o != nil && o.Province.IsSet() {
		return true
	}

	return false
}

// SetProvince gets a reference to the given NullableString and assigns it to the Province field.
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) SetProvince(v string) {
	o.Province.Set(&v)
}

// SetProvinceNil sets the value for Province to be an explicit nil
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) SetProvinceNil() {
	o.Province.Set(nil)
}

// UnsetProvince ensures that no value is present for Province, not even an explicit nil
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) UnsetProvince() {
	o.Province.Unset()
}

// GetPostalCode returns the PostalCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) GetPostalCode() string {
	if o == nil || IsNil(o.PostalCode.Get()) {
		var ret string
		return ret
	}
	return *o.PostalCode.Get()
}

// GetPostalCodeOk returns a tuple with the PostalCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) GetPostalCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PostalCode.Get(), o.PostalCode.IsSet()
}

// HasPostalCode returns a boolean if a field has been set.
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) HasPostalCode() bool {
	if o != nil && o.PostalCode.IsSet() {
		return true
	}

	return false
}

// SetPostalCode gets a reference to the given NullableString and assigns it to the PostalCode field.
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) SetPostalCode(v string) {
	o.PostalCode.Set(&v)
}

// SetPostalCodeNil sets the value for PostalCode to be an explicit nil
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) SetPostalCodeNil() {
	o.PostalCode.Set(nil)
}

// UnsetPostalCode ensures that no value is present for PostalCode, not even an explicit nil
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) UnsetPostalCode() {
	o.PostalCode.Unset()
}

// GetCountry returns the Country field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) GetCountry() string {
	if o == nil || IsNil(o.Country.Get()) {
		var ret string
		return ret
	}
	return *o.Country.Get()
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) GetCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Country.Get(), o.Country.IsSet()
}

// HasCountry returns a boolean if a field has been set.
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) HasCountry() bool {
	if o != nil && o.Country.IsSet() {
		return true
	}

	return false
}

// SetCountry gets a reference to the given NullableString and assigns it to the Country field.
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) SetCountry(v string) {
	o.Country.Set(&v)
}

// SetCountryNil sets the value for Country to be an explicit nil
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) SetCountryNil() {
	o.Country.Set(nil)
}

// UnsetCountry ensures that no value is present for Country, not even an explicit nil
func (o *PiFinancialClientFundConnextModelAddressForProfileV5) UnsetCountry() {
	o.Country.Unset()
}

func (o PiFinancialClientFundConnextModelAddressForProfileV5) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PiFinancialClientFundConnextModelAddressForProfileV5) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.No.IsSet() {
		toSerialize["no"] = o.No.Get()
	}
	if o.Floor.IsSet() {
		toSerialize["floor"] = o.Floor.Get()
	}
	if o.Building.IsSet() {
		toSerialize["building"] = o.Building.Get()
	}
	if o.RoomNo.IsSet() {
		toSerialize["roomNo"] = o.RoomNo.Get()
	}
	if o.Soi.IsSet() {
		toSerialize["soi"] = o.Soi.Get()
	}
	if o.Road.IsSet() {
		toSerialize["road"] = o.Road.Get()
	}
	if o.Moo.IsSet() {
		toSerialize["moo"] = o.Moo.Get()
	}
	if o.Subdistrict.IsSet() {
		toSerialize["subdistrict"] = o.Subdistrict.Get()
	}
	if o.District.IsSet() {
		toSerialize["district"] = o.District.Get()
	}
	if o.Province.IsSet() {
		toSerialize["province"] = o.Province.Get()
	}
	if o.PostalCode.IsSet() {
		toSerialize["postalCode"] = o.PostalCode.Get()
	}
	if o.Country.IsSet() {
		toSerialize["country"] = o.Country.Get()
	}
	return toSerialize, nil
}

type NullablePiFinancialClientFundConnextModelAddressForProfileV5 struct {
	value *PiFinancialClientFundConnextModelAddressForProfileV5
	isSet bool
}

func (v NullablePiFinancialClientFundConnextModelAddressForProfileV5) Get() *PiFinancialClientFundConnextModelAddressForProfileV5 {
	return v.value
}

func (v *NullablePiFinancialClientFundConnextModelAddressForProfileV5) Set(val *PiFinancialClientFundConnextModelAddressForProfileV5) {
	v.value = val
	v.isSet = true
}

func (v NullablePiFinancialClientFundConnextModelAddressForProfileV5) IsSet() bool {
	return v.isSet
}

func (v *NullablePiFinancialClientFundConnextModelAddressForProfileV5) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePiFinancialClientFundConnextModelAddressForProfileV5(val *PiFinancialClientFundConnextModelAddressForProfileV5) *NullablePiFinancialClientFundConnextModelAddressForProfileV5 {
	return &NullablePiFinancialClientFundConnextModelAddressForProfileV5{value: val, isSet: true}
}

func (v NullablePiFinancialClientFundConnextModelAddressForProfileV5) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePiFinancialClientFundConnextModelAddressForProfileV5) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
