namespace Pi.FundMarketData.Worker.Services.FundMarket.Sirius;

public static class LegacyMarket
{
    public static readonly HashSet<string> FundSymbols = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
    {
        "1AM-DAILY-RA",
        "1AM-DAILY-SSF",
        "1AM-TG",
        "1AMSET50-ID",
        "1AMSET50-RA",
        "1AMSET50-RU",
        "1GLOBALBOND",
        "1S-LTF-NT",
        "1S-LTF-T",
        "1SG-LTF-NT",
        "1SG-LTF-T",
        "1SMART-LTF",
        "1US-OPP",
        "1VAL-RD",
        "70/30-D LTF",
        "ABAGS",
        "ABAGS-SSF",
        "ABAPAC",
        "ABAPAC-RMF",
        "ABAPAC-SSF",
        "ABCA-A",
        "ABCC",
        "ABCG",
        "ABCG-SSF",
        "ABCNEXT-A",
        "ABCNEXT-SSF",
        "ABEG",
        "ABFC",
        "ABG",
        "ABGDD-A",
        "ABGDD-R",
        "ABGDD-RMF",
        "ABGDD-SSF",
        "ABGEM",
        "ABGFIX-A",
        "ABGS-A",
        "ABGS-SSF",
        "ABIG",
        "ABINC",
        "ABINNO-A",
        "ABINNO-SSF",
        "ABJO",
        "ABLTF",
        "ABLTF 70/30",
        "ABSC-RMF",
        "ABSI-RMF",
        "ABSL",
        "ABSM",
        "ABSM-RMF",
        "ABSM-SSF",
        "ABTED",
        "ABTESSF",
        "ABTESSFX",
        "ABV",
        "ABWOOF",
        "AEOB",
        "AFMOAT-HA",
        "AFMOAT-HSSF",
        "AFMOATHRMF",
        "AGF",
        "ASIA-E",
        "ASP",
        "ASP-AAA-A",
        "ASP-AAA-R",
        "ASP-ASIAN",
        "ASP-BRIC",
        "ASP-CHINA",
        "ASP-CHINABOND-A",
        "ASP-CHINABOND-R",
        "ASP-CHINATRIG 3M1",
        "ASP-CPGOV 6M1",
        "ASP-DIGIBLOC",
        "ASP-DIGIBLOC-SSF",
        "ASP-DIGIBLOCRMF",
        "ASP-DISRUPT",
        "ASP-DISRUPTRMF",
        "ASP-ERF",
        "ASP-EUG",
        "ASP-EUPROP",
        "ASP-EUROPE QUALITY",
        "ASP-EVOCHINA",
        "ASP-EVOCHINA-SSF",
        "ASP-EVOCHINARMF",
        "ASP-FFPLUSA",
        "ASP-FFPLUSR",
        "ASP-FLEXPLUS",
        "ASP-FRF",
        "ASP-GLTF-T",
        "ASP-GOLD",
        "ASP-HSI",
        "ASP-IHEALTH",
        "ASP-INDIA",
        "ASP-LTF-T",
        "ASP-MRF",
        "ASP-NGF",
        "ASP-OIL",
        "ASP-POWER",
        "ASP-POWERRMF",
        "ASP-PROPIN-A",
        "ASP-PROPIN-R",
        "ASP-ROBOT",
        "ASP-ROBOTRMF",
        "ASP-S&P500",
        "ASP-SME-A",
        "ASP-SME-SSF",
        "ASP-SME-SSFX",
        "ASP-SMELTF-T",
        "ASP-SMERMF",
        "ASP-T12",
        "ASP-ThaiESG",
        "ASP-THAITRIG 5M1",
        "ASP-THEQ",
        "ASP-TOPBRANDRMF",
        "ASP-TRIGGER 6M3",
        "ASP-USSMALL",
        "ASP-VIETRMF",
        "ASP-X",
        "ASPGIPLUS-A",
        "ASPGIPLUS-R",
        "BIC",
        "BIG CAP-D LTF",
        "CG-LTF",
        "CG-RMF",
        "CPRMF1",
        "CPRMF2",
        "CPRMF3",
        "CPRMF4",
        "CPRMF5",
        "DAOL-ALPHABONDS",
        "DAOL-AQUA",
        "DAOL-CANAB",
        "DAOL-CHIG",
        "DAOL-CYBER",
        "DAOL-DEWORLD",
        "DAOL-EUROPE",
        "DAOL-EVOSEMI",
        "DAOL-GEDUCATION",
        "DAOL-GEQUITY",
        "DAOL-GIHEALTH",
        "DAOL-GLOBALEQRMF",
        "DAOL-GOLD",
        "DAOL-GOLDRMF",
        "DAOL-GSECURE",
        "DAOL-GTECH",
        "DAOL-INNOVA",
        "DAOL-MONEY-R",
        "DAOL-MONYRMF",
        "DAOL-MULTI",
        "DAOL-OSHOP",
        "DAOL-PLAY",
        "DAOL-REALASSETS",
        "DAOL-TENERGY",
        "DAOL-THAITRIG6M",
        "DAOL-TRBOND-A",
        "DAOL-USREIT",
        "DAOL-USTBILL",
        "DAOL-VIETGROWTH",
        "DAOL-XPROP-A",
        "DAOL-XPROP-D",
        "DCAF-R",
        "DE-1",
        "DTOP",
        "EHD",
        "ERMF",
        "ES-GCG-A",
        "ES-GCG-SSF",
        "ES-GDIV",
        "ES-GDIV-Acc",
        "ES-GF-A",
        "ES-GF-D",
        "ES-GINFRA-A",
        "ES-GINFRA-D",
        "ES-GINNO-A",
        "ES-GINNO-SSF",
        "ES-GOVCP1Y5",
        "ES-GOVCP1Y6",
        "ES-GOVCP6M11",
        "ES-GSBOND-A",
        "ES-INDONESIA",
        "ES-INDONESIA-RMF",
        "ES-JPNBRCR1YB",
        "ES-LOVE",
        "ES-SETESG-ThaiESG-A",
        "ES-SETESG-ThaiESG-D",
        "ES-SPlus",
        "ES-TEQ6M1",
        "ES-USDCR1YB",
        "ES-USDCR1YC",
        "ES-USDCR1YD",
        "ES-USTECH",
        "F-RMF",
        "FLEX-RMF",
        "FLEXAR",
        "GBRMF",
        "GC",
        "GI5EM1",
        "GOLD-RMF-A",
        "HAPPY D5",
        "HI-DIV RMF",
        "HIDIV-AR",
        "HIDIV-D",
        "HIDIV-SSF",
        "HIDIVLTF",
        "HIDIVMF",
        "HIDIVPLUSG",
        "I-10",
        "I-20",
        "I-ASEAN STAR 10",
        "I-CHIC",
        "I-DEVELOP",
        "I-Emerging 10S2",
        "I-GOLD7S2",
        "I-GOLD7S3",
        "I-GOLDRMF",
        "I-OIL",
        "I-SMART",
        "IGOLD-G",
        "IGOLD-SSF",
        "IREITG",
        "K-2500",
        "K-2510",
        "K-2520",
        "K-2530",
        "K-AEC",
        "K-AFIXED",
        "K-AGRI",
        "K-ALLBASIC",
        "K-APB-A(A)",
        "K-ASIA",
        "K-ASIACV-A(A)",
        "K-ASIAX",
        "K-ATECH",
        "K-BANKING",
        "K-CASH",
        "K-CBOND-A",
        "K-CCTV-A(A)",
        "K-CHANGE-A(A)",
        "K-CHANGE-SSF",
        "K-CHINA-A(A)",
        "K-CHINA-A(D)",
        "K-CHINA-SSF",
        "K-CHX",
        "K-ENERGY",
        "K-EQUITY",
        "K-EUROPE-A(D)",
        "K-EUSAGE",
        "K-EUSMALL",
        "K-EUX",
        "K-FEQ",
        "K-FIXED-A",
        "K-FIXEDPLUS-A",
        "K-FIXEDPLUS-SSF",
        "K-FIXEDPRO",
        "K-GA-A(A)",
        "K-GA-A(D)",
        "K-GB-A(D)",
        "K-GDBOND-A(A)",
        "K-GEMO",
        "K-GHEALTH",
        "K-GHEALTH(UH)",
        "K-GINCOME-A(A)",
        "K-GINCOME-A(R)",
        "K-GINCOME-SSF",
        "K-GINFRA-A(D)",
        "K-GLOBE",
        "K-GOLD-A(A)",
        "K-GOLD-A(D)",
        "K-GPROP-A(A)",
        "K-GPROP-A(D)",
        "K-GTECH",
        "K-HIT-A(A)",
        "K-ICT",
        "K-INDIA-A(A)",
        "K-INDIA-A(D)",
        "K-INDX",
        "K-JP-A(D)",
        "K-JPX-A(A)",
        "K-MIDSMALL",
        "K-MONEY",
        "K-MVEQ",
        "K-OIL",
        "K-PLAN1",
        "K-PLAN2",
        "K-PLAN3",
        "K-PLANET-A(A)",
        "K-PROPI-A(D)",
        "K-SELECT",
        "K-SEMQ",
        "K-SET50",
        "K-SF-A",
        "K-SF-SSF",
        "K-SFPLUS",
        "K-SGM",
        "K-STAR-A(A)",
        "K-STAR-A(R)",
        "K-STAR-SSF",
        "K-STEQ-A(A)",
        "K-SUPSTAR-SSFX",
        "K-TREASURY",
        "K-US500X-A(A)",
        "K-USA-A(A)",
        "K-USA-A(D)",
        "K-USA-SSF",
        "K-USXNDQ-A(A)",
        "K-USXNDQ-A(D)",
        "K-VALUE",
        "K-VIETNAM",
        "K-VIETNAM-SSF",
        "K-WORLDX",
        "K2035RMF",
        "K2040RMF",
        "K20SLTF-A(D)",
        "K20SLTF-C(L)",
        "K70LTF-A(D)",
        "K70LTF-C(L)",
        "KAF",
        "KBLRMF",
        "KCHANGERMF",
        "KCHINARMF",
        "KDLTF-A(D)",
        "KDLTF-C(L)",
        "KEQLTF-A(A)",
        "KEQLTF-C(L)",
        "KEURMF",
        "KF-BIC",
        "KF-CHINA",
        "KF-CSINCOM",
        "KF-EM",
        "KF-EUROPE",
        "KF-GLS",
        "KF-GOLD",
        "KF-HCHINAD",
        "KF-HGOLD",
        "KF-HJAPAND",
        "KF-HSMUS",
        "KF-INCOME",
        "KF-JPSCAPD",
        "KF-LATAM",
        "KF-OIL",
        "KF-ORTFLEX",
        "KF-SINCOME",
        "KF-SMCAPD",
        "KF1MAX-A",
        "KF1MAXRMF",
        "KF1MAXSSF",
        "KF1MEAN-A",
        "KF1MEANRMF",
        "KF1MEANSSF",
        "KF1MILD-A",
        "KF1MILDRMF",
        "KF1MILDSSF",
        "KFACHINA-A",
        "KFACHINRMF",
        "KFACHINSSF",
        "KFAFIX-A",
        "KFAFIXRMF",
        "KFAFIXSSF",
        "KFAHYBON-A",
        "KFAINCOM-A",
        "KFAINCOM-R",
        "KFCASH-A",
        "KFCASHPLUS",
        "KFCASHRMF",
        "KFCASHSSF",
        "KFCHINARMF",
        "KFCINCOM-A",
        "KFCLIMA-A",
        "KFCLIMARMF",
        "KFCLIMASSF",
        "KFCMEGA-A",
        "KFCMEGARMF",
        "KFCMEGASSF",
        "KFCORE",
        "KFCORERMF",
        "KFCORESSF",
        "KFCSI300-A",
        "KFCYBER-A",
        "KFDIVERS-A",
        "KFDIVERS-R",
        "KFDIVRMF",
        "KFDIVSSF",
        "KFDNM-D",
        "KFDNMRMF",
        "KFDYNAMIC",
        "KFENFIX",
        "KFENS50-A",
        "KFENS50SSF",
        "KFEQRMF",
        "KFESG-A",
        "KFESGRMF",
        "KFESGSSF",
        "KFEURORMF",
        "KFFIN-D",
        "KFFITG1",
        "KFFITG2",
        "KFFLEX",
        "KFFLEX-D",
        "KFFLEX2RMF",
        "KFGBRAND-A",
        "KFGBRAND-D",
        "KFGBRANRMF",
        "KFGBRANSSF",
        "KFGDIV-A",
        "KFGDIV-D",
        "KFGG-A",
        "KFGGRMF",
        "KFGGSSF",
        "KFGMIL-A",
        "KFGOLDRMF",
        "KFGOOD",
        "KFGOODRMF",
        "KFGOVRMF",
        "KFGPROP-A",
        "KFGPROP-D",
        "KFGROWTH-A",
        "KFGROWTH-D",
        "KFGTECH-A",
        "KFGTECHRMF",
        "KFHAPPY-A",
        "KFHAPPYRMF",
        "KFHAPPYSSF",
        "KFHASIA-A",
        "KFHCARERMF",
        "KFHEALTH-A",
        "KFHEALTH-D",
        "KFHEUROP-A",
        "KFHHCARE-A",
        "KFHHCARE-D",
        "KFHTECH-A",
        "KFINDIARMF",
        "KFINFRA-A",
        "KFINFRARMF",
        "KFINFRASSF",
        "KFINNO-A",
        "KFIRMF",
        "KFJAPANRMF",
        "KFJPINDX-A",
        "KFJPSCAP-A",
        "KFLRMF",
        "KFLTF50",
        "KFLTF50-A",
        "KFLTFA50-D",
        "KFLTFAST-D",
        "KFLTFD70",
        "KFLTFD70-D",
        "KFLTFDIV",
        "KFLTFDIV-D",
        "KFLTFDNM-D",
        "KFLTFEQ",
        "KFLTFEQ-A",
        "KFLTFEQ70D",
        "KFLTFSTARD",
        "KFLTFTSM-D",
        "KFLTGOVRMF",
        "KFMINCOM-A",
        "KFMINCOM-R",
        "KFMTFI",
        "KFMTFI-D",
        "KFMTFIRMF",
        "KFNDQ-A",
        "KFPREFER-A",
        "KFS100-A",
        "KFS100RMF",
        "KFS100SSF",
        "KFS100SSFX",
        "KFSDIV",
        "KFSEQ",
        "KFSEQ-D",
        "KFSINCFX-A",
        "KFSINCFX-R",
        "KFSINCRMF",
        "KFSMART-A",
        "KFSMUL",
        "KFSPLUS-A",
        "KFSTARRMF",
        "KFSUPER",
        "KFSUPERRMF",
        "KFTHAICG",
        "KFTHAIESGA",
        "KFTHAIESGD",
        "KFTHAISM",
        "KFTRB-A",
        "KFTSRMF",
        "KFTSTAR-A",
        "KFTSTAR-D",
        "KFUS-A",
        "KFUSINDX-A",
        "KFUSRMF",
        "KFUSSSF",
        "KFVALUE-A",
        "KFVIET-A",
        "KFVIETRMF",
        "KFVIETSSF",
        "KFWINDX-A",
        "KGARMF",
        "KGBRMF",
        "KGDRMF",
        "KGHRMF",
        "KGIFRMF",
        "KGINCOMERMF",
        "KGLTF-A(D)",
        "KGLTF-C(L)",
        "KGTECHRMF",
        "KJPRMF",
        "KKP ACT EQ-A",
        "KKP ACT EQ-D",
        "KKP ACT EQ-SSF",
        "KKP ACT FIXED",
        "KKP ACT FIXED-SSF",
        "KKP BLRMF",
        "KKP CHINA-H",
        "KKP CHINA-H-SSF",
        "KKP DIVIDEND",
        "KKP DIVIDEND-SSF",
        "KKP EMXCN-H",
        "KKP EMXCN-UH",
        "KKP EQ THAI ESG",
        "KKP EQRMF",
        "KKP G-THEME-H",
        "KKP G-THEME-H-SSF",
        "KKP G-UBOND-H",
        "KKP G-UBOND-H-SSF",
        "KKP GB THAI ESG",
        "KKP GHC",
        "KKP GIMPACT-H",
        "KKP GIMPACT-H-SSF",
        "KKP GINFRAEQ-H",
        "KKP GINFRAEQ-H-SSF",
        "KKP GNP",
        "KKP GNP RMF-H",
        "KKP GNP RMF-UH",
        "KKP GNP-H",
        "KKP GNP-H-SSF",
        "KKP GNP-SSF",
        "KKP GOLD",
        "KKP INRMF",
        "KKP LTFD",
        "KKP MMRMF",
        "KKP MP",
        "KKP MP-SSF",
        "KKP NDQ100-H",
        "KKP NDQ100-H-SSF",
        "KKP NDQ100-UH",
        "KKP NDQ100-UH-SSF",
        "KKP PGE RMF-H",
        "KKP PGE-H",
        "KKP PGE-H-SSF",
        "KKP PGE-UH",
        "KKP PGE-UH-SSF",
        "KKP PLUS",
        "KKP PLUS-SSF",
        "KKP PROP",
        "KKP PROP-D",
        "KKP PROP-D-SSF",
        "KKP PROPRMF",
        "KKP S-PLUS",
        "KKP S-PLUS-SSF",
        "KKP SEMICON-H",
        "KKP SEMICON-H-SSF",
        "KKP SET50 ESG",
        "KKP SET50 ESG-SSF",
        "KKP SET50 ESG-SSFX",
        "KKP SG-AA",
        "KKP SG-AA Extra",
        "KKP SG-AA Extra-SSF",
        "KKP SG-AA Light",
        "KKP SG-AA Light-SSF",
        "KKP SG-AA RMF",
        "KKP SG-AA Ultra Light",
        "KKP SG-AA Ultra Light-SSF",
        "KKP SG-AA-SSF",
        "KKP SmartMV LTF",
        "KKP TECH RMF-H",
        "KKP TECH-H",
        "KKP TECH-H-SSF",
        "KKP TQG",
        "KKP TQG-SSF",
        "KMSLTF-A(A)",
        "KMSLTF-C(L)",
        "KMSRMF",
        "KMVLTF-A(A)",
        "KMVLTF-C(L)",
        "KPLANETRMF",
        "KPLUS2",
        "KS50LTF-A(A)",
        "KS50LTF-C(L)",
        "KS50RMF",
        "KSET50LTF-L",
        "KSFRMF",
        "KSLTF-L",
        "KSRMF",
        "KSTARRMF",
        "KT-AASIA-A",
        "KT-AGRIANDFOOD",
        "KT-ARB-A",
        "KT-ASEAN-A",
        "KT-ASEAN-SSF",
        "KT-Ashares RMF",
        "KT-Ashares-A",
        "KT-Ashares-SSF",
        "KT-ASIAG-A",
        "KT-ASIAG-SSF",
        "KT-ASIANBOND-A",
        "KT-BLOCKCHAIN-A",
        "KT-BOND",
        "KT-BOND RMF",
        "KT-BRAIN RMF",
        "KT-BRAIN-A",
        "KT-CARE-A",
        "KT-CHINA RMF",
        "KT-CHINA-A",
        "KT-CHINA-SSF",
        "KT-CHINABOND-A",
        "KT-CHINABOND-SSF",
        "KT-CLIMATE RMF",
        "KT-CLIMATE-A",
        "KT-CLIMATE-SSF",
        "KT-CLMVT-A",
        "KT-CLMVT-D",
        "KT-CSBOND-A",
        "KT-DHINCOME-A",
        "KT-EMEQ-A",
        "KT-ENERGY",
        "KT-EPIC-A",
        "KT-ESG RMF",
        "KT-ESG-A",
        "KT-EUROSM",
        "KT-EUROTECH-A",
        "KT-EUROTECH-SSF",
        "KT-FINANCE-A",
        "KT-FINANCE-SSF",
        "KT-FLEX",
        "KT-GCINCOME-A",
        "KT-GCINCOME-R",
        "KT-GCINCOME-SSF",
        "KT-GEQ-A",
        "KT-GESG-A",
        "KT-GESG-SSF",
        "KT-GMO-A",
        "KT-GOI-A",
        "KT-GOLD",
        "KT-GOLD RMF",
        "KT-GREEN-A",
        "KT-GREEN-SSF",
        "KT-HEALTHC RMF",
        "KT-HEALTHCARE-A",
        "KT-HEALTHCARE-SSF",
        "KT-HiDiv RMF",
        "KT-HiDiv-A",
        "KT-HiDiv-D",
        "KT-IGF-A",
        "KT-IGF-R",
        "KT-INDIA-A",
        "KT-INDIA-D",
        "KT-INDIA-SSF",
        "KT-JAPANSM-A",
        "KT-JAPANSM-D",
        "KT-JAPANSM-SSF",
        "KT-JPFUND-A",
        "KT-LUXURY-A",
        "KT-LUXURY-SSF",
        "KT-MAB-A",
        "KT-mai",
        "KT-MINING",
        "KT-OIL",
        "KT-OPP-A",
        "KT-OPP-D",
        "KT-PIF RMF",
        "KT-PIF-A",
        "KT-PIF-D",
        "KT-PIF-SSF",
        "KT-PRECIOUS",
        "KT-PROPERTY RMF",
        "KT-PROPERTY-A",
        "KT-PROPERTY-D",
        "KT-PROPERTY-SSF",
        "KT-SAGA-A",
        "KT-SET50-A",
        "KT-SET50-D",
        "KT-ST",
        "KT-TMT3",
        "KT-TMT7",
        "KT-TRIG7",
        "KT-TRIG8",
        "KT-US RMF",
        "KT-US-A",
        "KT-US-SSF",
        "KT-VIETNAM RMF",
        "KT-VIETNAM-A",
        "KT-VIETNAM-SSF",
        "KT-WCORP",
        "KT-WEQ RMF",
        "KT-WEQ-A",
        "KT-WEQ-SSF",
        "KT-WTAI RMF",
        "KT-WTAI-A",
        "KT25/75-A",
        "KT25/75-R",
        "KT25/75RMF",
        "KT70/30S-SSF",
        "KT70/30S-SSFX",
        "KTAG-ThaiESG",
        "KTAG70/30-ThaiESG",
        "KTBTHAICG-A",
        "KTEF",
        "KTEF-LTF-L",
        "KTEF-RMF",
        "KTESG50-ThaiESG",
        "KTESGS-SSF",
        "KTESGS-SSFX",
        "KTF13",
        "KTF14",
        "KTF15",
        "KTF16",
        "KTF17",
        "KTF18",
        "KTF19",
        "KTF20",
        "KTF21",
        "KTF22",
        "KTF23",
        "KTF24",
        "KTFIX-1Y3Y",
        "KTFIX3M1",
        "KTFIXPLUS-A",
        "KTFIXPLUS-D",
        "KTFIXPLUS-SSF",
        "KTGNEXT",
        "KTHAICGRMF",
        "KTILF",
        "KTLF-L",
        "KTLF70/30-L",
        "KTMEE-A",
        "KTMEE-D",
        "KTMEE-RMF",
        "KTMEE-SSF",
        "KTMSEQ",
        "KTMUNG-A",
        "KTMUNG-D",
        "KTMUNG-RMF",
        "KTMUNG-SSF",
        "KTPLUS",
        "KTSE",
        "KTSE-LTF-L",
        "KTSE-RMF",
        "KTSET50RMF",
        "KTSF",
        "KTSIV3M1",
        "KTSIV3M2",
        "KTSRI-A",
        "KTSRI-D",
        "KTSRI-RMF",
        "KTSRI-SSF",
        "KTSS",
        "KTSTPLUS-A",
        "KTSTPLUS-SSF",
        "KTSUK-A",
        "KTSUK-D",
        "KTSUK-RMF",
        "KTSUK-SSF",
        "KTSV",
        "KTTWIN1Y1",
        "KTTWIN1Y2",
        "KUSARMF",
        "KVIETNAMRMF",
        "KWI AEPLUS-A",
        "KWI APREIT-A",
        "KWI APREIT-R",
        "KWI ASIAN SM",
        "KWI ASM RMF",
        "KWI DRAGON",
        "KWI EE EURO",
        "KWI EQ",
        "KWI EQ DIV",
        "KWI EQ SSF",
        "KWI FLEX RMF",
        "KWI HCARE-A",
        "KWI HCARE-D",
        "KWI INDIA-A",
        "KWI INDIA-D",
        "KWI LTF",
        "KWI MONEY",
        "KWI SENERGY-A",
        "KWI SENERGY-SSF",
        "KWI ThaiESG-A",
        "KWI ThaiESG-D",
        "KWI THEQ",
        "KWI USBANK-A",
        "KWI VIETNAM",
        "LHACTLTF-A",
        "LHACTLTF-D",
        "LHCHINA-A",
        "LHCHINA-ASSF",
        "LHCHINA-D",
        "LHCHINA-DSSF",
        "LHCHINARMF",
        "LHCYBER-A",
        "LHCYBER-ASSF",
        "LHCYBER-D",
        "LHCYBER-DSSF",
        "LHDEBT-A",
        "LHDEBT-D",
        "LHDEBT-R",
        "LHDIGITAL-A",
        "LHDIGITAL-D",
        "LHDIGITAL-R",
        "LHDIVB-A",
        "LHDIVB-ASSF",
        "LHDIVB-D",
        "LHDIVB-DSSF",
        "LHEME-A",
        "LHEME-D",
        "LHEQD-A",
        "LHEQD-D",
        "LHEQD-R",
        "LHEQDPLUS-A",
        "LHEQDPLUS-D",
        "LHESPORT-A",
        "LHESPORT-D",
        "LHEUROPE-A",
        "LHEUROPE-ASSF",
        "LHEUROPE-D",
        "LHEUROPE-DSSF",
        "LHFL",
        "LHFLRMF",
        "LHGDYNAMIC-A",
        "LHGDYNAMIC-D",
        "LHGEQ-A",
        "LHGEQ-ASSF",
        "LHGEQ-D",
        "LHGEQ-DSSF",
        "LHGEQ-R",
        "LHGEQP-A",
        "LHGEQP-ASSF",
        "LHGEQP-D",
        "LHGEQP-DSSF",
        "LHGEQRMF",
        "LHGINCOME-A",
        "LHGINCOME-D",
        "LHGINCOME-R",
        "LHGINCOMERMF",
        "LHGLIFEE-A",
        "LHGLIFEE-D",
        "LHGOLD-A",
        "LHGOLD-D",
        "LHGOVRMF",
        "LHGREEN-A",
        "LHGREEN-D",
        "LHGROWTH-A",
        "LHGROWTH-D",
        "LHGROWTH-R",
        "LHHEALTH-A",
        "LHHEALTH-ASSF",
        "LHHEALTH-D",
        "LHHEALTH-DSSF",
        "LHINDIAE-A",
        "LHINDIAE-D",
        "LHINNO-A",
        "LHINNO-D",
        "LHIP-D",
        "LHJAPE-A",
        "LHJAPE-D",
        "LHMEGA-A",
        "LHMEGA-D",
        "LHMM-A",
        "LHMM-ASSF",
        "LHMMRMF",
        "LHMOBILITY-A",
        "LHMOBILITY-D",
        "LHMSFL-A",
        "LHMSFL-D",
        "LHMSFL-R",
        "LHPROP-I",
        "LHPROPG-A",
        "LHPROPG-D",
        "LHPROPIA-A",
        "LHPROPIA-ASSF",
        "LHPROPIA-D",
        "LHPROPIA-DSSF",
        "LHPROPINFRA-D",
        "LHROBOTE-A",
        "LHROBOTE-D",
        "LHSELECT-D",
        "LHSEMICON-A",
        "LHSEMICON-D",
        "LHSMART-D",
        "LHSMARTDSSF-SSF",
        "LHSMARTLTF-D",
        "LHSTGLTF-A",
        "LHSTGLTF-D",
        "LHSTPLUS-A",
        "LHSTPLUS-ASSF",
        "LHSTRATEGY-A",
        "LHSTRATEGY-ASSF",
        "LHSTRATEGY-D",
        "LHSTRATEGY-DSSF",
        "LHSTRATEGY-O",
        "LHSTRATEGY-R",
        "LHTHAIESG-A",
        "LHTHAIESG-D",
        "LHTOPPICK-A",
        "LHTOPPICK-D",
        "LHTOPPICK-R",
        "LHTPROP",
        "LHTPROPRMF",
        "LHTREASURY-A",
        "LHTRIG7M",
        "LHUSFIN-A",
        "LHUSFIN-ASSF",
        "LHUSFIN-D",
        "LHUSFIN-DSSF",
        "LHVN-A",
        "LHVN-ASSF",
        "LHVN-D",
        "LHVN-DSSF",
        "LHWPLUS-A",
        "LHWPLUS-D",
        "M-ACTIVE",
        "M-ASIA",
        "M-BOND",
        "M-CR",
        "M-EDGE",
        "M-EM",
        "M-EUBANK",
        "M-FIX",
        "M-FLEX",
        "M-FOCUS",
        "M-MEGA-A",
        "M-MEGA-D",
        "M-META",
        "M-MIDSMALL-A",
        "M-MIDSMALL-D",
        "M-MIDSMALL-SSF",
        "M-MIX20",
        "M-MIX50",
        "M-MIX70",
        "M-MULTI-A",
        "M-MULTI-D",
        "M-PROP RMF",
        "M-PROPERTY",
        "M-RMF-A",
        "M-S50 RMF",
        "M-S50-G",
        "M-S50-SSF",
        "M-SELECTCG",
        "M-SMART INCOME-AC",
        "M-SMART INCOME-AR",
        "M-SUKUK",
        "M-TWSUK RMF",
        "M-USTBILL",
        "M-VALUE",
        "M-VI",
        "MALTF",
        "MAMF",
        "MATECH-A",
        "MATECH-D",
        "MATECH-IA",
        "MBT-G",
        "MCANN",
        "MCBOND",
        "MCHEVO",
        "MCHINAGA",
        "MCHINAGD",
        "MCHINAIA",
        "MCHINASSF",
        "MCONT",
        "MCONVERT",
        "MDIVA-A",
        "MDIVA-D",
        "MDIVA-ID",
        "MEGA10-A",
        "MEGA10-SSF",
        "MEGA10CHINA-A",
        "MEGA10CHINA-SSF",
        "MEGA10CHINARMF",
        "MEGA10RMF",
        "MEGA20THAIESG",
        "MEURO-G",
        "MEURO-SSF",
        "MFF",
        "MFLEX-ThaiESG",
        "MFTECH",
        "MFX",
        "MGAG",
        "MGFGA",
        "MGFGD",
        "MGFIA",
        "MGFRMF",
        "MGFSSF",
        "MGLTF",
        "MGMF",
        "MGMVOL",
        "MGOV-Roll3M",
        "MGOV-Roll6M",
        "MGOV1Y1",
        "MGOV1Y2",
        "MGS",
        "MGTECH",
        "MHEALTHG",
        "MHEALTHRMF",
        "MHEALTHSSF",
        "MIDSMALLLTF",
        "MIDSMALLMF",
        "MIF-G",
        "MIFLTF",
        "MIFMF",
        "MIFSSF",
        "MINFRA",
        "MIPLUS-G",
        "MIPLUS-SSF",
        "MIX-D1585",
        "MMF-RMF",
        "MMGOVMF",
        "MMGOVSSF",
        "MMM-MF",
        "MMM-PLUS",
        "MMM-SSF",
        "MPDIVMF",
        "MPDIVSSF",
        "MPII-A",
        "MPII-D",
        "MPII-ID",
        "MRENEW-A",
        "MRENEW-D",
        "MRENEW-IA",
        "MRENEW-SSF",
        "MRENEWRMF",
        "MS50LTF",
        "MS50MF",
        "MT25-ThaiESG",
        "MTF-SSF",
        "MTF-SSFX",
        "MTOP2",
        "MTOP4",
        "MTQ-SSF",
        "MTQ-SSFX",
        "MUBOND-A",
        "MUBOND-D",
        "MUBOND-SSF",
        "MUBONDUH-A",
        "MUBONDUH-D",
        "MUBONDUH-SSF",
        "MVIET",
        "MVLTF",
        "MVMF",
        "MVSSF",
        "ONE-ACT-RD",
        "ONE-ACTIVE6/2",
        "ONE-ALLCHINA-ASSF",
        "ONE-ALLCHINA-RA",
        "ONE-APACESG",
        "ONE-APACPROP-RD",
        "ONE-CHINATOP10M-UH",
        "ONE-CHINATOP10M2",
        "ONE-DISC-ASSF",
        "ONE-DISC-RA",
        "ONE-DISCRMF-A",
        "ONE-EC14-RA",
        "ONE-EC14-RD",
        "ONE-EQ",
        "ONE-EUROEQ",
        "ONE-FAR",
        "ONE-FAS",
        "ONE-FIXED-A",
        "ONE-FLEX",
        "ONE-G",
        "ONE-GECOM",
        "ONE-GEM",
        "ONE-GLOBFIN-IA",
        "ONE-GLOBFIN-ID",
        "ONE-GLOBFIN-RA",
        "ONE-GLOBFIN-RD",
        "ONE-GLOBHY-R",
        "ONE-HOSPITAL",
        "ONE-INDIAOPP-IA",
        "ONE-INDIAOPP-ID",
        "ONE-INDIAOPP-RA",
        "ONE-INDIAOPP-RD",
        "ONE-MEDTECH",
        "ONE-METAVERSE",
        "ONE-MIDSMALL",
        "ONE-OPPORTUNITY6/2",
        "ONE-POWER-ND",
        "ONE-PREMIER",
        "ONE-PROP",
        "ONE-SETHD",
        "ONE-SHARIAHLTF",
        "ONE-STOXXASEAN",
        "ONE-TCMSSF-SSF",
        "ONE-TCMSSF-SSFX",
        "ONE-THAIESG",
        "ONE-TOP5M",
        "ONE-UGERMF-A",
        "ONE-UGG-ASSF",
        "ONE-UGG-IA",
        "ONE-UGG-RA",
        "ONE-UJE-RA",
        "ONE-ULTRA",
        "ONE-ULTRAPLUS-ASSF",
        "ONE-ULTRAPLUS-RA",
        "ONE-VIETNAM-RA",
        "ONE-VIETNAMRMF-A",
        "ONEPROP-RD",
        "ONEPROP-RMF",
        "ONEPROP-SG",
        "P-CGREEN",
        "PBOND",
        "PCASH",
        "PEQ",
        "PFIXRMF",
        "PGOLD",
        "PMIXRMF",
        "PRINCIPAL 70LTFD-T",
        "PRINCIPAL AARMF",
        "PRINCIPAL APDI-A",
        "PRINCIPAL APDIRMF",
        "PRINCIPAL BARMF",
        "PRINCIPAL CHEQ-A",
        "PRINCIPAL CHTECH-A",
        "PRINCIPAL CHTG6M2",
        "PRINCIPAL CII",
        "PRINCIPAL DAILY FIX",
        "PRINCIPAL DEF",
        "PRINCIPAL DPLUS-A",
        "PRINCIPAL EEF-D",
        "PRINCIPAL ELTF-T",
        "PRINCIPAL EPIF",
        "PRINCIPAL EQESG-ThaiESG",
        "PRINCIPAL EQRMF",
        "PRINCIPAL EUEQ-A",
        "PRINCIPAL FIRMF",
        "PRINCIPAL GCF-D",
        "PRINCIPAL GCLEAN-A",
        "PRINCIPAL GCLOUD-A",
        "PRINCIPAL GCREDIT-A",
        "PRINCIPAL GEDTECH-A",
        "PRINCIPAL GEF-A",
        "PRINCIPAL GERMANEQ",
        "PRINCIPAL GESG-A",
        "PRINCIPAL GFIXED",
        "PRINCIPAL GHEALTH-A",
        "PRINCIPAL GIF",
        "PRINCIPAL GINNO-A",
        "PRINCIPAL GMA-A",
        "PRINCIPAL GMV-A",
        "PRINCIPAL GOPP-A",
        "PRINCIPAL GOPP-SSF",
        "PRINCIPAL GQE-A",
        "PRINCIPAL GREITs",
        "PRINCIPAL GSA",
        "PRINCIPAL GSCEQ-R",
        "PRINCIPAL iBALANCED-D",
        "PRINCIPAL iBALANCED-R",
        "PRINCIPAL iDAILY-A",
        "PRINCIPAL iDAILY-D",
        "PRINCIPAL iDAILY-R",
        "PRINCIPAL iDIV-A",
        "PRINCIPAL iDIV-D",
        "PRINCIPAL iDIV-R",
        "PRINCIPAL iFIXED-A",
        "PRINCIPAL iFIXED-R",
        "PRINCIPAL iGOLD-A",
        "PRINCIPAL iGOLD-R",
        "PRINCIPAL iPROP-A",
        "PRINCIPAL iPROP-D",
        "PRINCIPAL iPROP-R",
        "PRINCIPAL iPROPEN-A",
        "PRINCIPAL iPROPEN-D",
        "PRINCIPAL iPROPEN-SSF",
        "PRINCIPAL iPROPPLUS",
        "PRINCIPAL iPROPRMF",
        "PRINCIPAL JEQ-A",
        "PRINCIPAL KEQ",
        "PRINCIPAL LTF-T",
        "PRINCIPAL MMRMF",
        "PRINCIPAL PRMF",
        "PRINCIPAL SET100RMF",
        "PRINCIPAL SET50-A",
        "PRINCIPAL SET50SSF-SSF",
        "PRINCIPAL SET50SSF-SSFX",
        "PRINCIPAL SIF-A",
        "PRINCIPAL TDIF-D",
        "PRINCIPAL TDIF-SSF",
        "PRINCIPAL THTG6M1",
        "PRINCIPAL TREASURY",
        "PRINCIPAL USEQ-A",
        "PRINCIPAL VF-A",
        "PRINCIPAL VNEQ-A",
        "PRINCIPAL VNEQRMF",
        "PRINCIPAL VNTG7M1",
        "PRINCIPAL VTOPP-A",
        "PWIN",
        "PWINRMF",
        "Q-PORT",
        "RKBC",
        "RKF4",
        "RMF1",
        "RMF2",
        "RMF3",
        "RMF4",
        "RPF2",
        "RRF1",
        "SAN",
        "SCB2576",
        "SCB2586",
        "SCB70-SSFX",
        "SCBAAA",
        "SCBABOND(A)",
        "SCBABS",
        "SCBAEM",
        "SCBAEMHA",
        "SCBAOA",
        "SCBASHARES(A)",
        "SCBASHARES(SSF)",
        "SCBAUD",
        "SCBAUTO(A)",
        "SCBAUTO(SSF)",
        "SCBAXJ(A)",
        "SCBAXJ(SSF)",
        "SCBBANKING",
        "SCBBANKINGA",
        "SCBBLN",
        "SCBBLNA",
        "SCBBLOC(A)",
        "SCBCE",
        "SCBCE(SSF)",
        "SCBCEH",
        "SCBCHA",
        "SCBCHA-SSF",
        "SCBCHAA",
        "SCBCHEQA",
        "SCBCHINA",
        "SCBCHTG2",
        "SCBCIO(A)",
        "SCBCLASSICA",
        "SCBCLEANA",
        "SCBCOMP",
        "SCBCP1Y10",
        "SCBCP1Y11",
        "SCBCP1Y5",
        "SCBCP1Y9",
        "SCBCP9M2",
        "SCBCP9M3",
        "SCBCP9M4",
        "SCBCTECH-SSF",
        "SCBCTECHA",
        "SCBDBOND(A)",
        "SCBDIGI",
        "SCBDJI(A)",
        "SCBDJI(SSF)",
        "SCBDM",
        "SCBDM2",
        "SCBDPLUSA",
        "SCBDV-SSF",
        "SCBDVA",
        "SCBEMBOND",
        "SCBEMEQ",
        "SCBEMEQA",
        "SCBENERGY",
        "SCBENERGYA",
        "SCBEQ-SSFX",
        "SCBEQUALA",
        "SCBEUEQ",
        "SCBEUEQA",
        "SCBEUROPE(A)",
        "SCBEUROPE(SSF)",
        "SCBEUSM",
        "SCBEV(A)",
        "SCBEV(SSF)",
        "SCBFINA",
        "SCBFINR",
        "SCBFINTECH(A)",
        "SCBFINTECH(SSF)",
        "SCBFIXEDA",
        "SCBFLX",
        "SCBFP",
        "SCBFP-SSF",
        "SCBFST",
        "SCBGA(A)",
        "SCBGEARA",
        "SCBGEESGA",
        "SCBGENOME(A)",
        "SCBGENOME(SSF)",
        "SCBGEQ",
        "SCBGEQA",
        "SCBGEX(A)",
        "SCBGEX(SSF)",
        "SCBGHC",
        "SCBGHCA",
        "SCBGIF",
        "SCBGINA",
        "SCBGINR",
        "SCBGLOB",
        "SCBGLOW",
        "SCBGLOWP",
        "SCBGMLA",
        "SCBGOLD",
        "SCBGOLDH",
        "SCBGOLDH-SSF",
        "SCBGOLDHRMF",
        "SCBGOLDHRMF-51",
        "SCBGPROP",
        "SCBGPROPA",
        "SCBGQUAL(A)",
        "SCBGSIF",
        "SCBGSIF-SSF",
        "SCBGSIFR",
        "SCBGTO",
        "SCBGTTG2",
        "SCBGVALUE(A)",
        "SCBIHEALTH(A)",
        "SCBIHEALTH(SSF)",
        "SCBINCA",
        "SCBINCR",
        "SCBINDEQ(A)",
        "SCBINDIA",
        "SCBINDIAA",
        "SCBINDO(A)",
        "SCBINNO(A)",
        "SCBINNO(SSF)",
        "SCBJAPAN(A)",
        "SCBJAPAN(SSF)",
        "SCBJPSMA",
        "SCBKEQTG",
        "SCBLARGEA",
        "SCBLEQ",
        "SCBLEQ-SSF",
        "SCBLEQA",
        "SCBLT1-2020",
        "SCBLT1-SSF",
        "SCBLT1(SSFA)",
        "SCBLT2-2020",
        "SCBLT2-SSF",
        "SCBLT3-2020",
        "SCBLT3-SSF",
        "SCBLT4-2020",
        "SCBLT4-SSF",
        "SCBLTSEA-2020",
        "SCBLTSED-2020",
        "SCBLTSET-SSF",
        "SCBLTSETA-2020",
        "SCBLTSETD-2020",
        "SCBLTT-2020",
        "SCBLTT-SSF",
        "SCBMEGA(A)",
        "SCBMILDA",
        "SCBMLCA(SSF)",
        "SCBMLCAA",
        "SCBMLT(SSF)",
        "SCBMLTA",
        "SCBMOMENTA",
        "SCBMPLUSA",
        "SCBMSE",
        "SCBNDQ(A)",
        "SCBNDQ(SSF)",
        "SCBNEXT(A)",
        "SCBNEXT(SSF)",
        "SCBNK225",
        "SCBNK225D",
        "SCBOIL",
        "SCBOPPA",
        "SCBOPPR",
        "SCBPGF",
        "SCBPGF(SSF)",
        "SCBPIN-SSF",
        "SCBPINA",
        "SCBPIND",
        "SCBPLUS",
        "SCBPLUSA",
        "SCBPMO",
        "SCBPMOA",
        "SCBPOPA",
        "SCBQUALITYA",
        "SCBRF",
        "SCBRM1",
        "SCBRM1-51",
        "SCBRM2",
        "SCBRM2-51",
        "SCBRM3",
        "SCBRM3-51",
        "SCBRM4",
        "SCBRM4-51",
        "SCBRMASHARES(A)",
        "SCBRMASHARES(A)-51",
        "SCBRMCHA",
        "SCBRMCHA-51",
        "SCBRMCLEAN(A)",
        "SCBRMCLEAN(A)-51",
        "SCBRMCTECH",
        "SCBRMCTECH-51",
        "SCBRMDIGI(A)",
        "SCBRMEU",
        "SCBRMEU-51",
        "SCBRMGHC",
        "SCBRMGHC-51",
        "SCBRMGIF",
        "SCBRMGW",
        "SCBRMGW-51",
        "SCBRMGWP",
        "SCBRMGWP-51",
        "SCBRMJAPAN(A)",
        "SCBRMJP",
        "SCBRMJP-51",
        "SCBRMLEQ",
        "SCBRMLEQ-51",
        "SCBRMMLCA",
        "SCBRMMLCA-51",
        "SCBRMNDQ(A)",
        "SCBRMNDQ(A)-51",
        "SCBRMPGF(A)",
        "SCBRMPGF(A)-51",
        "SCBRMPIN",
        "SCBRMPIN-51",
        "SCBRMPOP",
        "SCBRMPOP-51",
        "SCBRMS&P500",
        "SCBRMS&P500-51",
        "SCBRMS50",
        "SCBRMS50-51",
        "SCBRMUSA(A)",
        "SCBRMUSA(A)-51",
        "SCBRMVIET(A)",
        "SCBRMWORLD(A)",
        "SCBROBOA",
        "SCBRS2000(A)",
        "SCBRS2000(SSF)",
        "SCBS&P500",
        "SCBS&P500-SSF",
        "SCBS&P500(SSFA)",
        "SCBS&P500A",
        "SCBSE",
        "SCBSE-SSF",
        "SCBSEA",
        "SCBSEMI(A)",
        "SCBSEMI(SSF)",
        "SCBSET",
        "SCBSET-SSFX",
        "SCBSET50",
        "SCBSET50(SSF)",
        "SCBSFF",
        "SCBSFFPLUS-I",
        "SCBSFFPLUS-SSF",
        "SCBSMART2",
        "SCBSMART2-SSF",
        "SCBSMART2A",
        "SCBSMART3",
        "SCBSMART4",
        "SCBSPICYA",
        "SCBSPLUSA",
        "SCBST555A",
        "SCBST555B",
        "SCBTA(ThaiESG)",
        "SCBTA(ThaiESGA)",
        "SCBTEQ",
        "SCBTG3",
        "SCBTHAICGA",
        "SCBTM(ThaiESG)",
        "SCBTM(ThaiESGA)",
        "SCBTMF",
        "SCBTMFPLUS-I",
        "SCBTP(ThaiESG)",
        "SCBTP(ThaiESGA)",
        "SCBTRAVEL(A)",
        "SCBUSA(SSF)",
        "SCBUSAA",
        "SCBUSHYA",
        "SCBUSSM",
        "SCBVALUEA",
        "SCBVIET(A)",
        "SCBVIET(SSF)",
        "SCBVIET(SSFA)",
        "SCBWINA",
        "SCBWINR",
        "SCBWIPA",
        "SCBWIPD",
        "SCBWIPR",
        "SCBWORLD(A)",
        "SCBWORLD(SSF)",
        "SCDF",
        "SCIF",
        "SCIF2",
        "SF4",
        "SF5",
        "SF7",
        "SF8",
        "SI5A4",
        "SMART-PLUS",
        "SMARTMF",
        "SMARTSSF",
        "SMO5A1",
        "SPOT33S10",
        "SPOT33S11",
        "SPOT33S14",
        "SPOT33S15",
        "SPOT33S7",
        "SPOT33S8",
        "STD",
        "STD2",
        "SVRMF",
        "T-ES-CHINA A",
        "T-ES-ChinaA-SSF",
        "T-GlobalBondRMF",
        "T-JapanEQ",
        "TBF",
        "TCMF",
        "TDF",
        "TEF",
        "TEF-DIV",
        "TFIF",
        "TLDIVEQ-D",
        "TLDIVLTF-D",
        "TLDIVRMF",
        "TLEQ",
        "TLEQ-THAICG",
        "TLEQRMF",
        "TLFLEX",
        "TLFLEXRMF",
        "TLLTFEQ",
        "TLMMF-A",
        "TLMMF-SSF",
        "TLMMRMF",
        "TLMSEQ-A",
        "TLMSEQ-SSF",
        "TLMSEQRMF",
        "TLSMALLEQ-A",
        "TLSMALLEQ-SSF",
        "TLUSNDQ-H-A",
        "TLUSNDQ-H-SSF",
        "TMBTMSMVLTF",
        "TNP",
        "TS",
        "UBOT",
        "UCHI",
        "UCHINA",
        "UCHINA-SSF",
        "UCHINARMF",
        "UCI",
        "UCI-SSF",
        "UDAILY",
        "UDB-A",
        "UDB-N",
        "UDB-SSF",
        "UEMIF-A",
        "UEMIF-N",
        "UES",
        "UESG",
        "UESG-D",
        "UESG-SSF",
        "UESG-SSF-D",
        "UEV",
        "UEV-SSF",
        "UFIN-A",
        "UFIN-N",
        "UGBF-A",
        "UGBF-N",
        "UGBF-SSF",
        "UGBFRMF",
        "UGD",
        "UGIS-A",
        "UGIS-N",
        "UGIS-SSF",
        "UGISRMF",
        "UGLDC1Y1",
        "UGQG",
        "UGQG-SSF",
        "UGQGRMF",
        "UGSE",
        "UHCRMF",
        "UHERO",
        "UIDPLUS",
        "UINC-A",
        "UINC-N",
        "UINFRA-N",
        "UINFRA-SSF",
        "UJSMRMF",
        "UNF",
        "UNI",
        "UNI-SSF",
        "UNIRMF",
        "UOBEQ-SSF",
        "UOBEQ-SSFX",
        "UOBEQRMF",
        "UOBGARMF",
        "UOBGBRMF",
        "UOBGRMF-H",
        "UOBID",
        "UOBLTF",
        "UOBLTF-D",
        "UOBLTF-NTD",
        "UOBSA",
        "UOBSAI",
        "UOBSAS100",
        "UOBSAS100D",
        "UOBSC",
        "UOBSCI-D",
        "UOBSCI-N",
        "UOBSD",
        "UOBSD-SSF",
        "UOBSDF",
        "UOBSG - H",
        "UOBSG-D",
        "UOBSG-N",
        "UOBSGA-N",
        "UOBSGC",
        "UOBSHC",
        "UOBSHC-SSF",
        "UOBSJSM",
        "UOBSMG",
        "UOBSVRMF",
        "UPINCM",
        "USDHY-A",
        "USDHY-N",
        "USUS-SSF",
        "USUSRMF",
        "UTEQC1Y1",
        "UTHAICG",
        "UTSEQ-THAIESG",
        "UTSME",
        "UTSME-LTF",
        "UVO",
        "V-RMF-A",
        "VALUE-D LTF",
        "VFOCUS-D",
        "X-EQRMF",
        "X-SEQS-ASSF",
        "X-SEQS-DSSF",
        "X-SEQS-IA",
        "X-SEQS-ID",
        "X-SEQS-RA",
        "X-SEQS-RD"
    };
}
