name: Checkout to new branch and push to remote
description: Checkout to new branch and push to remote

inputs:
  working_directory:
    description: Base path to work on
    required: false
    default: .

runs:
  using: composite
  steps:
    - name: Setup git config
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |-
        git config user.name "Pi Financial Github Action"
        git config user.email "github.action@pi.financial"
