name: Checkout Config

inputs:
  token_image_update:
    description: Github Access Token needed for the checkout of other repositories
    required: true
  target-repository: 
    description: the repository that the tag change will happen in
    required: false  
 

runs:
  using: composite
  steps:
  - name: Checkout Target Repository
    uses: actions/checkout@v4
    with:
      repository: pi-platform-configs
      path: gitleaks
      token: ${{ inputs.token_image_update }}
      fetch-depth: 0