services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: redis:6379

  # Redis Service
  redis:
    image: "redis:alpine" # Use a public Redis image to build the redis service
    restart: unless-stopped

  db:
    image: mysql:8
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssword
      - MYSQL_PASSWORD=password
      - MYSQL_USER=go-boilerplate-user
      - MYSQL_DATABASE=go-boilerplate-db
    volumes:
      - go-boilerplate-mysql-data:/var/lib/mysql

volumes:
  go-boilerplate-mysql-data: