/*
 * FundConnext
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = Pi.Financial.Client.FundConnext.Client.FileParameter;
using OpenAPIDateConverter = Pi.Financial.Client.FundConnext.Client.OpenAPIDateConverter;

namespace Pi.Financial.Client.FundConnext.Model
{
    /// <summary>
    /// ระดับความเสี่ยง&lt;/br&gt;(1-5)&lt;/br&gt;
    /// </summary>
    [JsonConverter(typeof(IndividualInvestorV5ResponseSuitabilityRiskLevelJsonConverter))]
    [DataContract(Name = "IndividualInvestorV5Response_suitabilityRiskLevel")]
    public partial class IndividualInvestorV5ResponseSuitabilityRiskLevel : AbstractOpenAPISchema, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IndividualInvestorV5ResponseSuitabilityRiskLevel" /> class
        /// with the <see cref="decimal" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of decimal.</param>
        public IndividualInvestorV5ResponseSuitabilityRiskLevel(decimal actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType = "oneOf";
            this.ActualInstance = actualInstance;
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(decimal))
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: decimal");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `decimal`. If the actual instance is not `decimal`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of decimal</returns>
        public decimal GetDecimal()
        {
            return (decimal)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class IndividualInvestorV5ResponseSuitabilityRiskLevel {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, IndividualInvestorV5ResponseSuitabilityRiskLevel.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of IndividualInvestorV5ResponseSuitabilityRiskLevel
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of IndividualInvestorV5ResponseSuitabilityRiskLevel</returns>
        public static IndividualInvestorV5ResponseSuitabilityRiskLevel FromJson(string jsonString)
        {
            IndividualInvestorV5ResponseSuitabilityRiskLevel newIndividualInvestorV5ResponseSuitabilityRiskLevel = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newIndividualInvestorV5ResponseSuitabilityRiskLevel;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(decimal).GetProperty("AdditionalProperties") == null)
                {
                    newIndividualInvestorV5ResponseSuitabilityRiskLevel = new IndividualInvestorV5ResponseSuitabilityRiskLevel(JsonConvert.DeserializeObject<decimal>(jsonString, IndividualInvestorV5ResponseSuitabilityRiskLevel.SerializerSettings));
                }
                else
                {
                    newIndividualInvestorV5ResponseSuitabilityRiskLevel = new IndividualInvestorV5ResponseSuitabilityRiskLevel(JsonConvert.DeserializeObject<decimal>(jsonString, IndividualInvestorV5ResponseSuitabilityRiskLevel.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("decimal");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into decimal: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + String.Join(",", matchedTypes));
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newIndividualInvestorV5ResponseSuitabilityRiskLevel;
        }


        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for IndividualInvestorV5ResponseSuitabilityRiskLevel
    /// </summary>
    public class IndividualInvestorV5ResponseSuitabilityRiskLevelJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(IndividualInvestorV5ResponseSuitabilityRiskLevel).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch (reader.TokenType)
            {
                case JsonToken.Float:
                    return new IndividualInvestorV5ResponseSuitabilityRiskLevel(Convert.ToDecimal(reader.Value));
                case JsonToken.StartObject:
                    return IndividualInvestorV5ResponseSuitabilityRiskLevel.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return IndividualInvestorV5ResponseSuitabilityRiskLevel.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
