/*
 * FundConnext
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = Pi.Financial.Client.FundConnext.Client.FileParameter;
using OpenAPIDateConverter = Pi.Financial.Client.FundConnext.Client.OpenAPIDateConverter;

namespace Pi.Financial.Client.FundConnext.Model
{
    /// <summary>
    /// Spouse
    /// </summary>
    [DataContract(Name = "Spouse")]
    public partial class Spouse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Spouse" /> class.
        /// </summary>
        /// <param name="thFirstName">thFirstName.</param>
        /// <param name="thLastName">thLastName.</param>
        /// <param name="enFirstName">enFirstName.</param>
        /// <param name="enLastName">enLastName.</param>
        public Spouse(string thFirstName = default(string), string thLastName = default(string), string enFirstName = default(string), string enLastName = default(string))
        {
            this.ThFirstName = thFirstName;
            this.ThLastName = thLastName;
            this.EnFirstName = enFirstName;
            this.EnLastName = enLastName;
        }

        /// <summary>
        /// Gets or Sets ThFirstName
        /// </summary>
        [DataMember(Name = "thFirstName", EmitDefaultValue = false)]
        public string ThFirstName { get; set; }

        /// <summary>
        /// Gets or Sets ThLastName
        /// </summary>
        [DataMember(Name = "thLastName", EmitDefaultValue = false)]
        public string ThLastName { get; set; }

        /// <summary>
        /// Gets or Sets EnFirstName
        /// </summary>
        [DataMember(Name = "enFirstName", EmitDefaultValue = false)]
        public string EnFirstName { get; set; }

        /// <summary>
        /// Gets or Sets EnLastName
        /// </summary>
        [DataMember(Name = "enLastName", EmitDefaultValue = false)]
        public string EnLastName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Spouse {\n");
            sb.Append("  ThFirstName: ").Append(ThFirstName).Append("\n");
            sb.Append("  ThLastName: ").Append(ThLastName).Append("\n");
            sb.Append("  EnFirstName: ").Append(EnFirstName).Append("\n");
            sb.Append("  EnLastName: ").Append(EnLastName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
