/*
Pi.SetService.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package go_client

import (
	"encoding/json"
)

// checks if the PiSetServiceAPIModelsSetOpenOrderResponseListApiResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PiSetServiceAPIModelsSetOpenOrderResponseListApiResponse{}

// PiSetServiceAPIModelsSetOpenOrderResponseListApiResponse struct for PiSetServiceAPIModelsSetOpenOrderResponseListApiResponse
type PiSetServiceAPIModelsSetOpenOrderResponseListApiResponse struct {
	Data []PiSetServiceAPIModelsSetOpenOrderResponse `json:"data,omitempty"`
}

// NewPiSetServiceAPIModelsSetOpenOrderResponseListApiResponse instantiates a new PiSetServiceAPIModelsSetOpenOrderResponseListApiResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPiSetServiceAPIModelsSetOpenOrderResponseListApiResponse() *PiSetServiceAPIModelsSetOpenOrderResponseListApiResponse {
	this := PiSetServiceAPIModelsSetOpenOrderResponseListApiResponse{}
	return &this
}

// NewPiSetServiceAPIModelsSetOpenOrderResponseListApiResponseWithDefaults instantiates a new PiSetServiceAPIModelsSetOpenOrderResponseListApiResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPiSetServiceAPIModelsSetOpenOrderResponseListApiResponseWithDefaults() *PiSetServiceAPIModelsSetOpenOrderResponseListApiResponse {
	this := PiSetServiceAPIModelsSetOpenOrderResponseListApiResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PiSetServiceAPIModelsSetOpenOrderResponseListApiResponse) GetData() []PiSetServiceAPIModelsSetOpenOrderResponse {
	if o == nil {
		var ret []PiSetServiceAPIModelsSetOpenOrderResponse
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PiSetServiceAPIModelsSetOpenOrderResponseListApiResponse) GetDataOk() ([]PiSetServiceAPIModelsSetOpenOrderResponse, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *PiSetServiceAPIModelsSetOpenOrderResponseListApiResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []PiSetServiceAPIModelsSetOpenOrderResponse and assigns it to the Data field.
func (o *PiSetServiceAPIModelsSetOpenOrderResponseListApiResponse) SetData(v []PiSetServiceAPIModelsSetOpenOrderResponse) {
	o.Data = v
}

func (o PiSetServiceAPIModelsSetOpenOrderResponseListApiResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PiSetServiceAPIModelsSetOpenOrderResponseListApiResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullablePiSetServiceAPIModelsSetOpenOrderResponseListApiResponse struct {
	value *PiSetServiceAPIModelsSetOpenOrderResponseListApiResponse
	isSet bool
}

func (v NullablePiSetServiceAPIModelsSetOpenOrderResponseListApiResponse) Get() *PiSetServiceAPIModelsSetOpenOrderResponseListApiResponse {
	return v.value
}

func (v *NullablePiSetServiceAPIModelsSetOpenOrderResponseListApiResponse) Set(val *PiSetServiceAPIModelsSetOpenOrderResponseListApiResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePiSetServiceAPIModelsSetOpenOrderResponseListApiResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePiSetServiceAPIModelsSetOpenOrderResponseListApiResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePiSetServiceAPIModelsSetOpenOrderResponseListApiResponse(val *PiSetServiceAPIModelsSetOpenOrderResponseListApiResponse) *NullablePiSetServiceAPIModelsSetOpenOrderResponseListApiResponse {
	return &NullablePiSetServiceAPIModelsSetOpenOrderResponseListApiResponse{value: val, isSet: true}
}

func (v NullablePiSetServiceAPIModelsSetOpenOrderResponseListApiResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePiSetServiceAPIModelsSetOpenOrderResponseListApiResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
