/*
Pi.SetService.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package go_client

import (
	"encoding/json"
)

// checks if the PiSetServiceAPIModelsSetTradeHistoryResponseListApiResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PiSetServiceAPIModelsSetTradeHistoryResponseListApiResponse{}

// PiSetServiceAPIModelsSetTradeHistoryResponseListApiResponse struct for PiSetServiceAPIModelsSetTradeHistoryResponseListApiResponse
type PiSetServiceAPIModelsSetTradeHistoryResponseListApiResponse struct {
	Data []PiSetServiceAPIModelsSetTradeHistoryResponse `json:"data,omitempty"`
}

// NewPiSetServiceAPIModelsSetTradeHistoryResponseListApiResponse instantiates a new PiSetServiceAPIModelsSetTradeHistoryResponseListApiResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPiSetServiceAPIModelsSetTradeHistoryResponseListApiResponse() *PiSetServiceAPIModelsSetTradeHistoryResponseListApiResponse {
	this := PiSetServiceAPIModelsSetTradeHistoryResponseListApiResponse{}
	return &this
}

// NewPiSetServiceAPIModelsSetTradeHistoryResponseListApiResponseWithDefaults instantiates a new PiSetServiceAPIModelsSetTradeHistoryResponseListApiResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPiSetServiceAPIModelsSetTradeHistoryResponseListApiResponseWithDefaults() *PiSetServiceAPIModelsSetTradeHistoryResponseListApiResponse {
	this := PiSetServiceAPIModelsSetTradeHistoryResponseListApiResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PiSetServiceAPIModelsSetTradeHistoryResponseListApiResponse) GetData() []PiSetServiceAPIModelsSetTradeHistoryResponse {
	if o == nil {
		var ret []PiSetServiceAPIModelsSetTradeHistoryResponse
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PiSetServiceAPIModelsSetTradeHistoryResponseListApiResponse) GetDataOk() ([]PiSetServiceAPIModelsSetTradeHistoryResponse, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *PiSetServiceAPIModelsSetTradeHistoryResponseListApiResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []PiSetServiceAPIModelsSetTradeHistoryResponse and assigns it to the Data field.
func (o *PiSetServiceAPIModelsSetTradeHistoryResponseListApiResponse) SetData(v []PiSetServiceAPIModelsSetTradeHistoryResponse) {
	o.Data = v
}

func (o PiSetServiceAPIModelsSetTradeHistoryResponseListApiResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PiSetServiceAPIModelsSetTradeHistoryResponseListApiResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullablePiSetServiceAPIModelsSetTradeHistoryResponseListApiResponse struct {
	value *PiSetServiceAPIModelsSetTradeHistoryResponseListApiResponse
	isSet bool
}

func (v NullablePiSetServiceAPIModelsSetTradeHistoryResponseListApiResponse) Get() *PiSetServiceAPIModelsSetTradeHistoryResponseListApiResponse {
	return v.value
}

func (v *NullablePiSetServiceAPIModelsSetTradeHistoryResponseListApiResponse) Set(val *PiSetServiceAPIModelsSetTradeHistoryResponseListApiResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePiSetServiceAPIModelsSetTradeHistoryResponseListApiResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePiSetServiceAPIModelsSetTradeHistoryResponseListApiResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePiSetServiceAPIModelsSetTradeHistoryResponseListApiResponse(val *PiSetServiceAPIModelsSetTradeHistoryResponseListApiResponse) *NullablePiSetServiceAPIModelsSetTradeHistoryResponseListApiResponse {
	return &NullablePiSetServiceAPIModelsSetTradeHistoryResponseListApiResponse{value: val, isSet: true}
}

func (v NullablePiSetServiceAPIModelsSetTradeHistoryResponseListApiResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePiSetServiceAPIModelsSetTradeHistoryResponseListApiResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
