name: Generate Client
description: Generate Dotnet client from swagger file

inputs:
  api_name:
    description: name for output package
    required: true
  base_path:
    description: base path to operate on
    required: true
  swagger_path:
    description: path to swagger file relative to base path
    required: false
    default: tmp/swagger.yml
  package_name:
    description: name of generated package
    required: true
  package_version:
    description: version of generated package
    required: true
  http_client:
    description: HTTP client to generate, validated for `axios`, `fetch`. See https://openapi-generator.tech/docs/generators/
    default: axios
  output_path:
    description: path output dir relative to base path
    required: false
    default: Client/
  generator_version:
    description: version of openapi-generator-cli to use
    required: true
  swagger_filetype:
    description: select swagger filetype (yml or json)
    type: string
    default: yml

runs:
  using: composite
  steps:
    - name: Create generator config file
      shell: bash
      working-directory: ${{ inputs.base_path }}
      run: |
        cat << EOL > generator-config.json
          {
            "supportsES6": true,
            "disallowAdditionalPropertiesIfNotPresent": false,
            "npmName": "@pi-financial/${{ inputs.package_name }}",
            "npmVersion": "${{ inputs.package_version }}"
          }
        EOF

    - name: Generate
      shell: bash
      working-directory: ${{ inputs.base_path }}
      run: |-
        docker run --rm \
          --user $(id -u):$(id -g) \
          -v "${PWD}:/local" \
          openapitools/openapi-generator-cli:${{ inputs.generator_version }} generate \
            -g typescript-${{ inputs.http_client }} \
            -i /local/${{ inputs.swagger_path }}.${{ inputs.swagger_filetype }} \
            -o /local/${{ inputs.output_path }} \
            -c /local/generator-config.json \
            --git-user-id pi-financial \
            --git-repo-id ${{ github.event.repository.name }}
