db.curated_filter.insertMany([
  {
    _id: ObjectId('6705206262632ce3094d9ced'),
    filter_id: 29635,
    filter_name: 'SET50',
    filter_category: 'Markets',
    filter_type: 'Primary',
    category_priority: 1,
    group_name: 'Thai Equities',
    sub_group_name: 'Stocks',
    curated_list_id: 661,
    is_default: 1,
    highlight: 0,
    ordering: 2
  },
  {
    _id: ObjectId('6705206262632ce3094d9cee'),
    filter_id: 29761,
    filter_name: 'SET50 Index',
    filter_category: 'Markets',
    filter_type: 'Primary',
    category_priority: 1,
    group_name: 'Thai Equities',
    sub_group_name: 'Derivative Warrants',
    curated_list_id: 990,
    is_default: 1,
    highlight: 0,
    ordering: 2
  },
  {
    _id: ObjectId('6705206262632ce3094d9cef'),
    filter_id: 29894,
    filter_name: 'PF & REIT',
    filter_category: 'Markets',
    filter_type: 'Primary',
    category_priority: 1,
    group_name: 'Thai Equities',
    sub_group_name: 'PF & REIT',
    curated_list_id: 906,
    is_default: 1,
    highlight: 0,
    ordering: 1
  },
  {
    _id: ObjectId('6705206262632ce3094d9cf0'),
    filter_id: 29901,
    filter_name: 'Depositary Receipts',
    filter_category: 'Markets',
    filter_type: 'Primary',
    category_priority: 1,
    group_name: 'Thai Equities',
    sub_group_name: 'Depositary Receipts',
    curated_list_id: 1011,
    is_default: 1,
    highlight: 0,
    ordering: 1
  },
  {
    _id: ObjectId('6705206262632ce3094d9cf1'),
    filter_id: 29908,
    filter_name: 'ETFs',
    filter_category: 'Markets',
    filter_type: 'Primary',
    category_priority: 1,
    group_name: 'Thai Equities',
    sub_group_name: 'ETFs',
    curated_list_id: 1025,
    is_default: 1,
    highlight: 0,
    ordering: 1
  },
  {
    _id: ObjectId('6705206262632ce3094d9cf2'),
    filter_id: 29915,
    filter_name: 'Warrants',
    filter_category: 'Markets',
    filter_type: 'Primary',
    category_priority: 1,
    group_name: 'Thai Equities',
    sub_group_name: 'Warrants',
    curated_list_id: 1018,
    is_default: 1,
    highlight: 0,
    ordering: 1
  },
  {
    _id: ObjectId('6705206262632ce3094d9cf3'),
    filter_id: 30937,
    filter_name: 'SET50 Futures',
    filter_category: 'Markets',
    filter_type: 'Primary',
    category_priority: 1,
    group_name: 'Derivatives',
    sub_group_name: 'S50 Futures',
    curated_list_id: 1032,
    is_default: 1,
    highlight: 0,
    ordering: 1
  },
  {
    _id: ObjectId('6705206262632ce3094d9cf4'),
    filter_id: 30944,
    filter_name: 'SET50 Options',
    filter_category: 'Markets',
    filter_type: 'Primary',
    category_priority: 1,
    group_name: 'Derivatives',
    sub_group_name: 'S50 Options',
    curated_list_id: 1067,
    is_default: 1,
    highlight: 0,
    ordering: 1
  },
  {
    _id: ObjectId('6705206262632ce3094d9cf5'),
    filter_id: 30965,
    filter_name: 'Sector Index Futures',
    filter_category: 'Markets',
    filter_type: 'Primary',
    category_priority: 1,
    group_name: 'Derivatives',
    sub_group_name: 'Sectors',
    curated_list_id: 1039,
    is_default: 1,
    highlight: 0,
    ordering: 1
  },
  {
    _id: ObjectId('6705206262632ce3094d9cf6'),
    filter_id: 30972,
    filter_name: 'Single Stock Futures',
    filter_category: 'Markets',
    filter_type: 'Primary',
    category_priority: 1,
    group_name: 'Derivatives',
    sub_group_name: 'Stocks',
    curated_list_id: 1046,
    is_default: 1,
    highlight: 0,
    ordering: 1
  },
  {
    _id: ObjectId('6705206262632ce3094d9cf7'),
    filter_id: 30979,
    filter_name: 'Precious Metal Futures',
    filter_category: 'Markets',
    filter_type: 'Primary',
    category_priority: 1,
    group_name: 'Derivatives',
    sub_group_name: 'Metals',
    curated_list_id: 1053,
    is_default: 1,
    highlight: 0,
    ordering: 1
  },
  {
    _id: ObjectId('6705206262632ce3094d9cf8'),
    filter_id: 30986,
    filter_name: 'Currency Futures',
    filter_category: 'Markets',
    filter_type: 'Primary',
    category_priority: 1,
    group_name: 'Derivatives',
    sub_group_name: 'Currency',
    curated_list_id: 1060,
    is_default: 1,
    highlight: 0,
    ordering: 1
  }
]);