db.curated_list.insertMany([
  {
    _id: ObjectId('6705206262632ce3094d9cf9'),
    curated_list_id: 661,
    curated_list_code: null,
    curated_type: 'Logical',
    relevant_to: 'Thai Equities',
    name: 'S50',
    hashtag: '#SET50.TH',
    ordering: null,
    create_time: null,
    update_time: null,
    update_by: null
  },
  {
    _id: ObjectId('6705206262632ce3094d9cfa'),
    curated_list_id: 906,
    curated_list_code: null,
    curated_type: 'Logical',
    relevant_to: 'Thai Equities',
    name: 'PF&REIT',
    hashtag: '#PF&REIT',
    ordering: null,
    create_time: null,
    update_time: null,
    update_by: null
  },
  {
    _id: ObjectId('6705206262632ce3094d9cfb'),
    curated_list_id: 990,
    curated_list_code: null,
    curated_type: 'Logical',
    relevant_to: 'Thai Equities',
    name: 'S50 Index Derivative Warrants',
    hashtag: null,
    ordering: null,
    create_time: null,
    update_time: null,
    update_by: null
  },
  {
    _id: ObjectId('6705206362632ce3094d9cfc'),
    curated_list_id: 1011,
    curated_list_code: null,
    curated_type: 'Logical',
    relevant_to: 'Thai Equities',
    name: 'Default (Depositary Receipts)',
    hashtag: null,
    ordering: null,
    create_time: null,
    update_time: null,
    update_by: null
  },
  {
    _id: ObjectId('6705206362632ce3094d9cfd'),
    curated_list_id: 1018,
    curated_list_code: null,
    curated_type: 'Logical',
    relevant_to: 'Thai Equities',
    name: 'Default (Thai Warrants)',
    hashtag: null,
    ordering: null,
    create_time: null,
    update_time: null,
    update_by: null
  },
  {
    _id: ObjectId('6705206362632ce3094d9cfe'),
    curated_list_id: 1025,
    curated_list_code: null,
    curated_type: 'Logical',
    relevant_to: 'Thai Equities',
    name: 'Default (Thai ETFs)',
    hashtag: null,
    ordering: null,
    create_time: null,
    update_time: null,
    update_by: null
  },
  {
    _id: ObjectId('6705206362632ce3094d9cff'),
    curated_list_id: 1032,
    curated_list_code: null,
    curated_type: 'Logical',
    relevant_to: 'Derivatives',
    name: 'Default (SET50 Index Futures)',
    hashtag: null,
    ordering: null,
    create_time: null,
    update_time: null,
    update_by: null
  },
  {
    _id: ObjectId('6705206362632ce3094d9d00'),
    curated_list_id: 1039,
    curated_list_code: null,
    curated_type: 'Logical',
    relevant_to: 'Derivatives',
    name: 'Default (Sector Index Futures)',
    hashtag: null,
    ordering: null,
    create_time: null,
    update_time: null,
    update_by: null
  },
  {
    _id: ObjectId('6705206362632ce3094d9d01'),
    curated_list_id: 1046,
    curated_list_code: null,
    curated_type: 'Logical',
    relevant_to: 'Derivatives',
    name: 'Default (Single Stock Futures)',
    hashtag: null,
    ordering: null,
    create_time: null,
    update_time: null,
    update_by: null
  },
  {
    _id: ObjectId('6705206362632ce3094d9d02'),
    curated_list_id: 1053,
    curated_list_code: null,
    curated_type: 'Logical',
    relevant_to: 'Derivatives',
    name: 'Default (Precious Metal Futures)',
    hashtag: null,
    ordering: null,
    create_time: null,
    update_time: null,
    update_by: null
  },
  {
    _id: ObjectId('6705206362632ce3094d9d03'),
    curated_list_id: 1060,
    curated_list_code: null,
    curated_type: 'Logical',
    relevant_to: 'Derivatives',
    name: 'Default (Currency Futures)',
    hashtag: null,
    ordering: null,
    create_time: null,
    update_time: null,
    update_by: null
  },
  {
    _id: ObjectId('6705206362632ce3094d9d04'),
    curated_list_id: 1067,
    curated_list_code: null,
    curated_type: 'Logical',
    relevant_to: 'Derivatives',
    name: 'Default (SET50 Index Options)',
    hashtag: null,
    ordering: null,
    create_time: null,
    update_time: null,
    update_by: null
  },
  {
    curated_list_id: 1068,
    curated_list_code: null,
    curated_type: 'Manual',
    relevant_to: 'Homepage',
    list_name: 'Home Carousel',
    name: 'Home Carousel',
    hashtag: '#Home.Carousel',
    ordering: null,
    create_time: null,
    update_time: null,
    update_by: null,
    symbols: [
      'Equity.SET',
      'Equity.SET50',
      'Equity.mai'
    ]
  }
]);