name: Checkout Repository

inputs:
  repository:
    description: repository name
    required: false
    default: ${{ github.repository }}
  base_ref:
    description: branch, tag or commit SHA to be base code
    required: false
    default: ${{ github.base_ref || 'main' }}
  target_ref:
    description: branch, tag or commit SHA to merge into base code
    required: false
    default: ${{ github.head_ref || github.ref_name }}
  fetch_depth:
    description: to specify depth of commits 0 - for all 1 - for single commit
    required: false
    default: 1

runs:
  using: composite
  steps:
    - name: if it not from a pull request
      if: ${{ github.event_name != 'pull_request'}}
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.base_ref }}
        fetch-depth: ${{ inputs.fetch_depth}}
        clean: true
        

    - name: if its from a pull request
      if: ${{ github.event_name == 'pull_request'}}
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        fetch-depth: ${{ inputs.fetch_depth}}
        ref: ${{ github.event.pull_request.head.sha }}
        clean: true

    - name: if it has a tag
      shell: bash
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        git config user.name "Pi Financial Github Action"
        git config user.email "github.action@pi.financial"
        git fetch
        # git merge --no-commit --no-ff ${{ inputs.target_ref }}

    - name: if its from a pull request
      shell: bash
      if: ${{ github.event_name == 'pull_request'}}
      run: |
        git config user.name "Pi Financial Github Action"
        git config user.email "github.action@pi.financial"
        git fetch
        # git merge --no-commit  --no-ff origin/${{ inputs.target_ref }}

    - name: if its from a merged pull request
      shell: bash
      if: github.event.pull_request.merged == 'true'
      run: |
        git config user.name "Pi Financial Github Action"
        git config user.email "github.action@pi.financial"
        git fetch
        # git merge --no-commit  --no-ff ${{ inputs.target_ref }}

    - name: If its from main
      shell: bash
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        git config user.name "Pi Financial Github Action"
        git config user.email "github.action@pi.financial"
        git fetch
        # git merge --no-commit  --no-ff ${{ inputs.target_ref }}
