name: Authenticate Github

inputs:
  gh_access_token:
    description: Github Access Token
    required: true

runs:
  using: composite
  steps:
    - name: Create .netrc file
      shell: bash
      run: |
        cat <<EOF > .netrc
        machine github.com
          login ${{ inputs.gh_access_token }}
          password x-oauth-basic
        EOF
        chmod 600 .netrc
        cp .netrc $HOME/.netrc
