/*
MarketData Migration Proxy API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package go_client

import (
	"encoding/json"
)

// checks if the PiMarketDataDomainModelsResponseMarketDerivativeInformationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PiMarketDataDomainModelsResponseMarketDerivativeInformationResponse{}

// PiMarketDataDomainModelsResponseMarketDerivativeInformationResponse struct for PiMarketDataDomainModelsResponseMarketDerivativeInformationResponse
type PiMarketDataDomainModelsResponseMarketDerivativeInformationResponse struct {
	Code       NullableString                                                 `json:"code,omitempty"`
	Message    NullableString                                                 `json:"message,omitempty"`
	Response   *PiMarketDataDomainModelsResponseDerivativeInformationResponse `json:"response,omitempty"`
	DebugStack NullableString                                                 `json:"debugStack,omitempty"`
}

// NewPiMarketDataDomainModelsResponseMarketDerivativeInformationResponse instantiates a new PiMarketDataDomainModelsResponseMarketDerivativeInformationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPiMarketDataDomainModelsResponseMarketDerivativeInformationResponse() *PiMarketDataDomainModelsResponseMarketDerivativeInformationResponse {
	this := PiMarketDataDomainModelsResponseMarketDerivativeInformationResponse{}
	return &this
}

// NewPiMarketDataDomainModelsResponseMarketDerivativeInformationResponseWithDefaults instantiates a new PiMarketDataDomainModelsResponseMarketDerivativeInformationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPiMarketDataDomainModelsResponseMarketDerivativeInformationResponseWithDefaults() *PiMarketDataDomainModelsResponseMarketDerivativeInformationResponse {
	this := PiMarketDataDomainModelsResponseMarketDerivativeInformationResponse{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PiMarketDataDomainModelsResponseMarketDerivativeInformationResponse) GetCode() string {
	if o == nil || IsNil(o.Code.Get()) {
		var ret string
		return ret
	}
	return *o.Code.Get()
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PiMarketDataDomainModelsResponseMarketDerivativeInformationResponse) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Code.Get(), o.Code.IsSet()
}

// HasCode returns a boolean if a field has been set.
func (o *PiMarketDataDomainModelsResponseMarketDerivativeInformationResponse) HasCode() bool {
	if o != nil && o.Code.IsSet() {
		return true
	}

	return false
}

// SetCode gets a reference to the given NullableString and assigns it to the Code field.
func (o *PiMarketDataDomainModelsResponseMarketDerivativeInformationResponse) SetCode(v string) {
	o.Code.Set(&v)
}

// SetCodeNil sets the value for Code to be an explicit nil
func (o *PiMarketDataDomainModelsResponseMarketDerivativeInformationResponse) SetCodeNil() {
	o.Code.Set(nil)
}

// UnsetCode ensures that no value is present for Code, not even an explicit nil
func (o *PiMarketDataDomainModelsResponseMarketDerivativeInformationResponse) UnsetCode() {
	o.Code.Unset()
}

// GetMessage returns the Message field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PiMarketDataDomainModelsResponseMarketDerivativeInformationResponse) GetMessage() string {
	if o == nil || IsNil(o.Message.Get()) {
		var ret string
		return ret
	}
	return *o.Message.Get()
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PiMarketDataDomainModelsResponseMarketDerivativeInformationResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Message.Get(), o.Message.IsSet()
}

// HasMessage returns a boolean if a field has been set.
func (o *PiMarketDataDomainModelsResponseMarketDerivativeInformationResponse) HasMessage() bool {
	if o != nil && o.Message.IsSet() {
		return true
	}

	return false
}

// SetMessage gets a reference to the given NullableString and assigns it to the Message field.
func (o *PiMarketDataDomainModelsResponseMarketDerivativeInformationResponse) SetMessage(v string) {
	o.Message.Set(&v)
}

// SetMessageNil sets the value for Message to be an explicit nil
func (o *PiMarketDataDomainModelsResponseMarketDerivativeInformationResponse) SetMessageNil() {
	o.Message.Set(nil)
}

// UnsetMessage ensures that no value is present for Message, not even an explicit nil
func (o *PiMarketDataDomainModelsResponseMarketDerivativeInformationResponse) UnsetMessage() {
	o.Message.Unset()
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *PiMarketDataDomainModelsResponseMarketDerivativeInformationResponse) GetResponse() PiMarketDataDomainModelsResponseDerivativeInformationResponse {
	if o == nil || IsNil(o.Response) {
		var ret PiMarketDataDomainModelsResponseDerivativeInformationResponse
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PiMarketDataDomainModelsResponseMarketDerivativeInformationResponse) GetResponseOk() (*PiMarketDataDomainModelsResponseDerivativeInformationResponse, bool) {
	if o == nil || IsNil(o.Response) {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *PiMarketDataDomainModelsResponseMarketDerivativeInformationResponse) HasResponse() bool {
	if o != nil && !IsNil(o.Response) {
		return true
	}

	return false
}

// SetResponse gets a reference to the given PiMarketDataDomainModelsResponseDerivativeInformationResponse and assigns it to the Response field.
func (o *PiMarketDataDomainModelsResponseMarketDerivativeInformationResponse) SetResponse(v PiMarketDataDomainModelsResponseDerivativeInformationResponse) {
	o.Response = &v
}

// GetDebugStack returns the DebugStack field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PiMarketDataDomainModelsResponseMarketDerivativeInformationResponse) GetDebugStack() string {
	if o == nil || IsNil(o.DebugStack.Get()) {
		var ret string
		return ret
	}
	return *o.DebugStack.Get()
}

// GetDebugStackOk returns a tuple with the DebugStack field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PiMarketDataDomainModelsResponseMarketDerivativeInformationResponse) GetDebugStackOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DebugStack.Get(), o.DebugStack.IsSet()
}

// HasDebugStack returns a boolean if a field has been set.
func (o *PiMarketDataDomainModelsResponseMarketDerivativeInformationResponse) HasDebugStack() bool {
	if o != nil && o.DebugStack.IsSet() {
		return true
	}

	return false
}

// SetDebugStack gets a reference to the given NullableString and assigns it to the DebugStack field.
func (o *PiMarketDataDomainModelsResponseMarketDerivativeInformationResponse) SetDebugStack(v string) {
	o.DebugStack.Set(&v)
}

// SetDebugStackNil sets the value for DebugStack to be an explicit nil
func (o *PiMarketDataDomainModelsResponseMarketDerivativeInformationResponse) SetDebugStackNil() {
	o.DebugStack.Set(nil)
}

// UnsetDebugStack ensures that no value is present for DebugStack, not even an explicit nil
func (o *PiMarketDataDomainModelsResponseMarketDerivativeInformationResponse) UnsetDebugStack() {
	o.DebugStack.Unset()
}

func (o PiMarketDataDomainModelsResponseMarketDerivativeInformationResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PiMarketDataDomainModelsResponseMarketDerivativeInformationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Code.IsSet() {
		toSerialize["code"] = o.Code.Get()
	}
	if o.Message.IsSet() {
		toSerialize["message"] = o.Message.Get()
	}
	if !IsNil(o.Response) {
		toSerialize["response"] = o.Response
	}
	if o.DebugStack.IsSet() {
		toSerialize["debugStack"] = o.DebugStack.Get()
	}
	return toSerialize, nil
}

type NullablePiMarketDataDomainModelsResponseMarketDerivativeInformationResponse struct {
	value *PiMarketDataDomainModelsResponseMarketDerivativeInformationResponse
	isSet bool
}

func (v NullablePiMarketDataDomainModelsResponseMarketDerivativeInformationResponse) Get() *PiMarketDataDomainModelsResponseMarketDerivativeInformationResponse {
	return v.value
}

func (v *NullablePiMarketDataDomainModelsResponseMarketDerivativeInformationResponse) Set(val *PiMarketDataDomainModelsResponseMarketDerivativeInformationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePiMarketDataDomainModelsResponseMarketDerivativeInformationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePiMarketDataDomainModelsResponseMarketDerivativeInformationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePiMarketDataDomainModelsResponseMarketDerivativeInformationResponse(val *PiMarketDataDomainModelsResponseMarketDerivativeInformationResponse) *NullablePiMarketDataDomainModelsResponseMarketDerivativeInformationResponse {
	return &NullablePiMarketDataDomainModelsResponseMarketDerivativeInformationResponse{value: val, isSet: true}
}

func (v NullablePiMarketDataDomainModelsResponseMarketDerivativeInformationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePiMarketDataDomainModelsResponseMarketDerivativeInformationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
