/*
MarketData Migration Proxy API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package go_client

import (
	"encoding/json"
)

// checks if the PiMarketDataDomainModelsResponseMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PiMarketDataDomainModelsResponseMeta{}

// PiMarketDataDomainModelsResponseMeta struct for PiMarketDataDomainModelsResponseMeta
type PiMarketDataDomainModelsResponseMeta struct {
	Exchange         NullableString `json:"exchange,omitempty"`
	ExchangeTimezone NullableString `json:"exchangeTimezone,omitempty"`
	Country          NullableString `json:"country,omitempty"`
	OffsetSeconds    *int32         `json:"offsetSeconds,omitempty"`
}

// NewPiMarketDataDomainModelsResponseMeta instantiates a new PiMarketDataDomainModelsResponseMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPiMarketDataDomainModelsResponseMeta() *PiMarketDataDomainModelsResponseMeta {
	this := PiMarketDataDomainModelsResponseMeta{}
	return &this
}

// NewPiMarketDataDomainModelsResponseMetaWithDefaults instantiates a new PiMarketDataDomainModelsResponseMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPiMarketDataDomainModelsResponseMetaWithDefaults() *PiMarketDataDomainModelsResponseMeta {
	this := PiMarketDataDomainModelsResponseMeta{}
	return &this
}

// GetExchange returns the Exchange field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PiMarketDataDomainModelsResponseMeta) GetExchange() string {
	if o == nil || IsNil(o.Exchange.Get()) {
		var ret string
		return ret
	}
	return *o.Exchange.Get()
}

// GetExchangeOk returns a tuple with the Exchange field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PiMarketDataDomainModelsResponseMeta) GetExchangeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Exchange.Get(), o.Exchange.IsSet()
}

// HasExchange returns a boolean if a field has been set.
func (o *PiMarketDataDomainModelsResponseMeta) HasExchange() bool {
	if o != nil && o.Exchange.IsSet() {
		return true
	}

	return false
}

// SetExchange gets a reference to the given NullableString and assigns it to the Exchange field.
func (o *PiMarketDataDomainModelsResponseMeta) SetExchange(v string) {
	o.Exchange.Set(&v)
}

// SetExchangeNil sets the value for Exchange to be an explicit nil
func (o *PiMarketDataDomainModelsResponseMeta) SetExchangeNil() {
	o.Exchange.Set(nil)
}

// UnsetExchange ensures that no value is present for Exchange, not even an explicit nil
func (o *PiMarketDataDomainModelsResponseMeta) UnsetExchange() {
	o.Exchange.Unset()
}

// GetExchangeTimezone returns the ExchangeTimezone field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PiMarketDataDomainModelsResponseMeta) GetExchangeTimezone() string {
	if o == nil || IsNil(o.ExchangeTimezone.Get()) {
		var ret string
		return ret
	}
	return *o.ExchangeTimezone.Get()
}

// GetExchangeTimezoneOk returns a tuple with the ExchangeTimezone field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PiMarketDataDomainModelsResponseMeta) GetExchangeTimezoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExchangeTimezone.Get(), o.ExchangeTimezone.IsSet()
}

// HasExchangeTimezone returns a boolean if a field has been set.
func (o *PiMarketDataDomainModelsResponseMeta) HasExchangeTimezone() bool {
	if o != nil && o.ExchangeTimezone.IsSet() {
		return true
	}

	return false
}

// SetExchangeTimezone gets a reference to the given NullableString and assigns it to the ExchangeTimezone field.
func (o *PiMarketDataDomainModelsResponseMeta) SetExchangeTimezone(v string) {
	o.ExchangeTimezone.Set(&v)
}

// SetExchangeTimezoneNil sets the value for ExchangeTimezone to be an explicit nil
func (o *PiMarketDataDomainModelsResponseMeta) SetExchangeTimezoneNil() {
	o.ExchangeTimezone.Set(nil)
}

// UnsetExchangeTimezone ensures that no value is present for ExchangeTimezone, not even an explicit nil
func (o *PiMarketDataDomainModelsResponseMeta) UnsetExchangeTimezone() {
	o.ExchangeTimezone.Unset()
}

// GetCountry returns the Country field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PiMarketDataDomainModelsResponseMeta) GetCountry() string {
	if o == nil || IsNil(o.Country.Get()) {
		var ret string
		return ret
	}
	return *o.Country.Get()
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PiMarketDataDomainModelsResponseMeta) GetCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Country.Get(), o.Country.IsSet()
}

// HasCountry returns a boolean if a field has been set.
func (o *PiMarketDataDomainModelsResponseMeta) HasCountry() bool {
	if o != nil && o.Country.IsSet() {
		return true
	}

	return false
}

// SetCountry gets a reference to the given NullableString and assigns it to the Country field.
func (o *PiMarketDataDomainModelsResponseMeta) SetCountry(v string) {
	o.Country.Set(&v)
}

// SetCountryNil sets the value for Country to be an explicit nil
func (o *PiMarketDataDomainModelsResponseMeta) SetCountryNil() {
	o.Country.Set(nil)
}

// UnsetCountry ensures that no value is present for Country, not even an explicit nil
func (o *PiMarketDataDomainModelsResponseMeta) UnsetCountry() {
	o.Country.Unset()
}

// GetOffsetSeconds returns the OffsetSeconds field value if set, zero value otherwise.
func (o *PiMarketDataDomainModelsResponseMeta) GetOffsetSeconds() int32 {
	if o == nil || IsNil(o.OffsetSeconds) {
		var ret int32
		return ret
	}
	return *o.OffsetSeconds
}

// GetOffsetSecondsOk returns a tuple with the OffsetSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PiMarketDataDomainModelsResponseMeta) GetOffsetSecondsOk() (*int32, bool) {
	if o == nil || IsNil(o.OffsetSeconds) {
		return nil, false
	}
	return o.OffsetSeconds, true
}

// HasOffsetSeconds returns a boolean if a field has been set.
func (o *PiMarketDataDomainModelsResponseMeta) HasOffsetSeconds() bool {
	if o != nil && !IsNil(o.OffsetSeconds) {
		return true
	}

	return false
}

// SetOffsetSeconds gets a reference to the given int32 and assigns it to the OffsetSeconds field.
func (o *PiMarketDataDomainModelsResponseMeta) SetOffsetSeconds(v int32) {
	o.OffsetSeconds = &v
}

func (o PiMarketDataDomainModelsResponseMeta) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PiMarketDataDomainModelsResponseMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Exchange.IsSet() {
		toSerialize["exchange"] = o.Exchange.Get()
	}
	if o.ExchangeTimezone.IsSet() {
		toSerialize["exchangeTimezone"] = o.ExchangeTimezone.Get()
	}
	if o.Country.IsSet() {
		toSerialize["country"] = o.Country.Get()
	}
	if !IsNil(o.OffsetSeconds) {
		toSerialize["offsetSeconds"] = o.OffsetSeconds
	}
	return toSerialize, nil
}

type NullablePiMarketDataDomainModelsResponseMeta struct {
	value *PiMarketDataDomainModelsResponseMeta
	isSet bool
}

func (v NullablePiMarketDataDomainModelsResponseMeta) Get() *PiMarketDataDomainModelsResponseMeta {
	return v.value
}

func (v *NullablePiMarketDataDomainModelsResponseMeta) Set(val *PiMarketDataDomainModelsResponseMeta) {
	v.value = val
	v.isSet = true
}

func (v NullablePiMarketDataDomainModelsResponseMeta) IsSet() bool {
	return v.isSet
}

func (v *NullablePiMarketDataDomainModelsResponseMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePiMarketDataDomainModelsResponseMeta(val *PiMarketDataDomainModelsResponseMeta) *NullablePiMarketDataDomainModelsResponseMeta {
	return &NullablePiMarketDataDomainModelsResponseMeta{value: val, isSet: true}
}

func (v NullablePiMarketDataDomainModelsResponseMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePiMarketDataDomainModelsResponseMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
