/*
MarketData Migration Proxy API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package go_client

import (
	"encoding/json"
	"time"
)

// checks if the PiMarketDataDomainModelsRequestBrokerInfoRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PiMarketDataDomainModelsRequestBrokerInfoRequest{}

// PiMarketDataDomainModelsRequestBrokerInfoRequest struct for PiMarketDataDomainModelsRequestBrokerInfoRequest
type PiMarketDataDomainModelsRequestBrokerInfoRequest struct {
	AsOfDate *time.Time                                  `json:"asOfDate,omitempty"`
	Data     []PiMarketDataDomainModelsRequestBrokerData `json:"data,omitempty"`
}

// NewPiMarketDataDomainModelsRequestBrokerInfoRequest instantiates a new PiMarketDataDomainModelsRequestBrokerInfoRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPiMarketDataDomainModelsRequestBrokerInfoRequest() *PiMarketDataDomainModelsRequestBrokerInfoRequest {
	this := PiMarketDataDomainModelsRequestBrokerInfoRequest{}
	return &this
}

// NewPiMarketDataDomainModelsRequestBrokerInfoRequestWithDefaults instantiates a new PiMarketDataDomainModelsRequestBrokerInfoRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPiMarketDataDomainModelsRequestBrokerInfoRequestWithDefaults() *PiMarketDataDomainModelsRequestBrokerInfoRequest {
	this := PiMarketDataDomainModelsRequestBrokerInfoRequest{}
	return &this
}

// GetAsOfDate returns the AsOfDate field value if set, zero value otherwise.
func (o *PiMarketDataDomainModelsRequestBrokerInfoRequest) GetAsOfDate() time.Time {
	if o == nil || IsNil(o.AsOfDate) {
		var ret time.Time
		return ret
	}
	return *o.AsOfDate
}

// GetAsOfDateOk returns a tuple with the AsOfDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PiMarketDataDomainModelsRequestBrokerInfoRequest) GetAsOfDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.AsOfDate) {
		return nil, false
	}
	return o.AsOfDate, true
}

// HasAsOfDate returns a boolean if a field has been set.
func (o *PiMarketDataDomainModelsRequestBrokerInfoRequest) HasAsOfDate() bool {
	if o != nil && !IsNil(o.AsOfDate) {
		return true
	}

	return false
}

// SetAsOfDate gets a reference to the given time.Time and assigns it to the AsOfDate field.
func (o *PiMarketDataDomainModelsRequestBrokerInfoRequest) SetAsOfDate(v time.Time) {
	o.AsOfDate = &v
}

// GetData returns the Data field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PiMarketDataDomainModelsRequestBrokerInfoRequest) GetData() []PiMarketDataDomainModelsRequestBrokerData {
	if o == nil {
		var ret []PiMarketDataDomainModelsRequestBrokerData
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PiMarketDataDomainModelsRequestBrokerInfoRequest) GetDataOk() ([]PiMarketDataDomainModelsRequestBrokerData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *PiMarketDataDomainModelsRequestBrokerInfoRequest) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []PiMarketDataDomainModelsRequestBrokerData and assigns it to the Data field.
func (o *PiMarketDataDomainModelsRequestBrokerInfoRequest) SetData(v []PiMarketDataDomainModelsRequestBrokerData) {
	o.Data = v
}

func (o PiMarketDataDomainModelsRequestBrokerInfoRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PiMarketDataDomainModelsRequestBrokerInfoRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AsOfDate) {
		toSerialize["asOfDate"] = o.AsOfDate
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullablePiMarketDataDomainModelsRequestBrokerInfoRequest struct {
	value *PiMarketDataDomainModelsRequestBrokerInfoRequest
	isSet bool
}

func (v NullablePiMarketDataDomainModelsRequestBrokerInfoRequest) Get() *PiMarketDataDomainModelsRequestBrokerInfoRequest {
	return v.value
}

func (v *NullablePiMarketDataDomainModelsRequestBrokerInfoRequest) Set(val *PiMarketDataDomainModelsRequestBrokerInfoRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePiMarketDataDomainModelsRequestBrokerInfoRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePiMarketDataDomainModelsRequestBrokerInfoRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePiMarketDataDomainModelsRequestBrokerInfoRequest(val *PiMarketDataDomainModelsRequestBrokerInfoRequest) *NullablePiMarketDataDomainModelsRequestBrokerInfoRequest {
	return &NullablePiMarketDataDomainModelsRequestBrokerInfoRequest{value: val, isSet: true}
}

func (v NullablePiMarketDataDomainModelsRequestBrokerInfoRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePiMarketDataDomainModelsRequestBrokerInfoRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
