/*
MarketData Migration Proxy API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package go_client

import (
	"encoding/json"
)

// checks if the PiMarketDataDomainModelsResponseTimelineMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PiMarketDataDomainModelsResponseTimelineMeta{}

// PiMarketDataDomainModelsResponseTimelineMeta struct for PiMarketDataDomainModelsResponseTimelineMeta
type PiMarketDataDomainModelsResponseTimelineMeta struct {
	Exchange         NullableString `json:"exchange,omitempty"`
	ExchangeTimezone NullableString `json:"exchangeTimezone,omitempty"`
	Country          NullableString `json:"country,omitempty"`
	OffsetSeconds    *int32         `json:"offsetSeconds,omitempty"`
}

// NewPiMarketDataDomainModelsResponseTimelineMeta instantiates a new PiMarketDataDomainModelsResponseTimelineMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPiMarketDataDomainModelsResponseTimelineMeta() *PiMarketDataDomainModelsResponseTimelineMeta {
	this := PiMarketDataDomainModelsResponseTimelineMeta{}
	return &this
}

// NewPiMarketDataDomainModelsResponseTimelineMetaWithDefaults instantiates a new PiMarketDataDomainModelsResponseTimelineMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPiMarketDataDomainModelsResponseTimelineMetaWithDefaults() *PiMarketDataDomainModelsResponseTimelineMeta {
	this := PiMarketDataDomainModelsResponseTimelineMeta{}
	return &this
}

// GetExchange returns the Exchange field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PiMarketDataDomainModelsResponseTimelineMeta) GetExchange() string {
	if o == nil || IsNil(o.Exchange.Get()) {
		var ret string
		return ret
	}
	return *o.Exchange.Get()
}

// GetExchangeOk returns a tuple with the Exchange field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PiMarketDataDomainModelsResponseTimelineMeta) GetExchangeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Exchange.Get(), o.Exchange.IsSet()
}

// HasExchange returns a boolean if a field has been set.
func (o *PiMarketDataDomainModelsResponseTimelineMeta) HasExchange() bool {
	if o != nil && o.Exchange.IsSet() {
		return true
	}

	return false
}

// SetExchange gets a reference to the given NullableString and assigns it to the Exchange field.
func (o *PiMarketDataDomainModelsResponseTimelineMeta) SetExchange(v string) {
	o.Exchange.Set(&v)
}

// SetExchangeNil sets the value for Exchange to be an explicit nil
func (o *PiMarketDataDomainModelsResponseTimelineMeta) SetExchangeNil() {
	o.Exchange.Set(nil)
}

// UnsetExchange ensures that no value is present for Exchange, not even an explicit nil
func (o *PiMarketDataDomainModelsResponseTimelineMeta) UnsetExchange() {
	o.Exchange.Unset()
}

// GetExchangeTimezone returns the ExchangeTimezone field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PiMarketDataDomainModelsResponseTimelineMeta) GetExchangeTimezone() string {
	if o == nil || IsNil(o.ExchangeTimezone.Get()) {
		var ret string
		return ret
	}
	return *o.ExchangeTimezone.Get()
}

// GetExchangeTimezoneOk returns a tuple with the ExchangeTimezone field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PiMarketDataDomainModelsResponseTimelineMeta) GetExchangeTimezoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExchangeTimezone.Get(), o.ExchangeTimezone.IsSet()
}

// HasExchangeTimezone returns a boolean if a field has been set.
func (o *PiMarketDataDomainModelsResponseTimelineMeta) HasExchangeTimezone() bool {
	if o != nil && o.ExchangeTimezone.IsSet() {
		return true
	}

	return false
}

// SetExchangeTimezone gets a reference to the given NullableString and assigns it to the ExchangeTimezone field.
func (o *PiMarketDataDomainModelsResponseTimelineMeta) SetExchangeTimezone(v string) {
	o.ExchangeTimezone.Set(&v)
}

// SetExchangeTimezoneNil sets the value for ExchangeTimezone to be an explicit nil
func (o *PiMarketDataDomainModelsResponseTimelineMeta) SetExchangeTimezoneNil() {
	o.ExchangeTimezone.Set(nil)
}

// UnsetExchangeTimezone ensures that no value is present for ExchangeTimezone, not even an explicit nil
func (o *PiMarketDataDomainModelsResponseTimelineMeta) UnsetExchangeTimezone() {
	o.ExchangeTimezone.Unset()
}

// GetCountry returns the Country field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PiMarketDataDomainModelsResponseTimelineMeta) GetCountry() string {
	if o == nil || IsNil(o.Country.Get()) {
		var ret string
		return ret
	}
	return *o.Country.Get()
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PiMarketDataDomainModelsResponseTimelineMeta) GetCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Country.Get(), o.Country.IsSet()
}

// HasCountry returns a boolean if a field has been set.
func (o *PiMarketDataDomainModelsResponseTimelineMeta) HasCountry() bool {
	if o != nil && o.Country.IsSet() {
		return true
	}

	return false
}

// SetCountry gets a reference to the given NullableString and assigns it to the Country field.
func (o *PiMarketDataDomainModelsResponseTimelineMeta) SetCountry(v string) {
	o.Country.Set(&v)
}

// SetCountryNil sets the value for Country to be an explicit nil
func (o *PiMarketDataDomainModelsResponseTimelineMeta) SetCountryNil() {
	o.Country.Set(nil)
}

// UnsetCountry ensures that no value is present for Country, not even an explicit nil
func (o *PiMarketDataDomainModelsResponseTimelineMeta) UnsetCountry() {
	o.Country.Unset()
}

// GetOffsetSeconds returns the OffsetSeconds field value if set, zero value otherwise.
func (o *PiMarketDataDomainModelsResponseTimelineMeta) GetOffsetSeconds() int32 {
	if o == nil || IsNil(o.OffsetSeconds) {
		var ret int32
		return ret
	}
	return *o.OffsetSeconds
}

// GetOffsetSecondsOk returns a tuple with the OffsetSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PiMarketDataDomainModelsResponseTimelineMeta) GetOffsetSecondsOk() (*int32, bool) {
	if o == nil || IsNil(o.OffsetSeconds) {
		return nil, false
	}
	return o.OffsetSeconds, true
}

// HasOffsetSeconds returns a boolean if a field has been set.
func (o *PiMarketDataDomainModelsResponseTimelineMeta) HasOffsetSeconds() bool {
	if o != nil && !IsNil(o.OffsetSeconds) {
		return true
	}

	return false
}

// SetOffsetSeconds gets a reference to the given int32 and assigns it to the OffsetSeconds field.
func (o *PiMarketDataDomainModelsResponseTimelineMeta) SetOffsetSeconds(v int32) {
	o.OffsetSeconds = &v
}

func (o PiMarketDataDomainModelsResponseTimelineMeta) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PiMarketDataDomainModelsResponseTimelineMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Exchange.IsSet() {
		toSerialize["exchange"] = o.Exchange.Get()
	}
	if o.ExchangeTimezone.IsSet() {
		toSerialize["exchangeTimezone"] = o.ExchangeTimezone.Get()
	}
	if o.Country.IsSet() {
		toSerialize["country"] = o.Country.Get()
	}
	if !IsNil(o.OffsetSeconds) {
		toSerialize["offsetSeconds"] = o.OffsetSeconds
	}
	return toSerialize, nil
}

type NullablePiMarketDataDomainModelsResponseTimelineMeta struct {
	value *PiMarketDataDomainModelsResponseTimelineMeta
	isSet bool
}

func (v NullablePiMarketDataDomainModelsResponseTimelineMeta) Get() *PiMarketDataDomainModelsResponseTimelineMeta {
	return v.value
}

func (v *NullablePiMarketDataDomainModelsResponseTimelineMeta) Set(val *PiMarketDataDomainModelsResponseTimelineMeta) {
	v.value = val
	v.isSet = true
}

func (v NullablePiMarketDataDomainModelsResponseTimelineMeta) IsSet() bool {
	return v.isSet
}

func (v *NullablePiMarketDataDomainModelsResponseTimelineMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePiMarketDataDomainModelsResponseTimelineMeta(val *PiMarketDataDomainModelsResponseTimelineMeta) *NullablePiMarketDataDomainModelsResponseTimelineMeta {
	return &NullablePiMarketDataDomainModelsResponseTimelineMeta{value: val, isSet: true}
}

func (v NullablePiMarketDataDomainModelsResponseTimelineMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePiMarketDataDomainModelsResponseTimelineMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
