name: Authenticate AWS for promote

inputs:
  aws_access_key_id:
    description: AWS access key id
    required: true
  aws_secret_access_key:
    description: AWS Secret access key
    required: true
  aws_region:
    description: AWS Region
    required: true
  role_to_assume_target:
    description: role of the environment
    required: false
  role_to_assume_source:
    description: role of the environment
    required: false
outputs:
  ecr-registry_source:
    description: ECR Registry
    value: ${{ steps.login-ecr-source.outputs.registry }}
  ecr-registry_target:
    description: ECR Registry
    value: ${{ steps.login-ecr-target.outputs.registry }}

runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
        aws-access-key-id: ${{ inputs.aws_access_key_id }}
        aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
        aws-region: ${{ inputs.aws_region }}
        role-to-assume: ${{ inputs.role_to_assume_target}}
        role-duration-seconds: 1200
        role-session-name: ci-run-${{ github.run_id }}
    - name: Login to Amazon ECR
      id: login-ecr-source
      uses: aws-actions/amazon-ecr-login@v1.5.1

 
