DROP INDEX `portfolio_bond_daily_snapshot_custcode` ON `portfolio_bond_daily_snapshot`;
DROP INDEX `portfolio_bond_daily_snapshot_date_key` ON `portfolio_bond_daily_snapshot`;
DROP INDEX `portfolio_bond_daily_snapshot_date_key_custcode` ON `portfolio_bond_daily_snapshot`;
DROP INDEX `portfolio_cash_daily_snapshot_custcode` ON `portfolio_cash_daily_snapshot`;
DROP INDEX `portfolio_cash_daily_snapshot_date_key` ON `portfolio_cash_daily_snapshot`;
DROP INDEX `portfolio_cash_daily_snapshot_date_key_custcode` ON `portfolio_cash_daily_snapshot`;
DROP INDEX `portfolio_global_equity_daily_snapshot_custcode` ON `portfolio_global_equity_daily_snapshot`;
DROP INDEX `portfolio_global_equity_daily_snapshot_date_key` ON `portfolio_global_equity_daily_snapshot`;
DROP INDEX `portfolio_global_equity_daily_snapshot_date_key_custcode` ON `portfolio_global_equity_daily_snapshot`;
DROP INDEX `portfolio_global_equity_otc_daily_snapshot_custcode` ON `portfolio_global_equity_otc_daily_snapshot`;
DROP INDEX `portfolio_global_equity_otc_daily_snapshot_date_key` ON `portfolio_global_equity_otc_daily_snapshot`;
DROP INDEX `portfolio_global_equity_otc_daily_snapshot_date_key_custcode` ON `portfolio_global_equity_otc_daily_snapshot`;
DROP INDEX `portfolio_mutual_fund_daily_snapshot_custcode` ON `portfolio_mutual_fund_daily_snapshot`;
DROP INDEX `portfolio_mutual_fund_daily_snapshot_date_key` ON `portfolio_mutual_fund_daily_snapshot`;
DROP INDEX `portfolio_mutual_fund_daily_snapshot_date_key_custcode` ON `portfolio_mutual_fund_daily_snapshot`;
DROP INDEX `portfolio_structured_product_daily_snapshot_custcode` ON `portfolio_structured_product_daily_snapshot`;
DROP INDEX `portfolio_structured_product_daily_snapshot_date_key` ON `portfolio_structured_product_daily_snapshot`;
DROP INDEX `portfolio_structured_product_daily_snapshot_date_key_custcode` ON `portfolio_structured_product_daily_snapshot`;
DROP INDEX `portfolio_summary_daily_snapshot_custcode` ON `portfolio_summary_daily_snapshot`;
DROP INDEX `portfolio_summary_daily_snapshot_date_key` ON `portfolio_summary_daily_snapshot`;
DROP INDEX `portfolio_summary_daily_snapshot_date_key_custcode_mktid` ON `portfolio_summary_daily_snapshot`;
DROP INDEX `portfolio_tfex_daily_snapshot_custcode` ON `portfolio_tfex_daily_snapshot`;
DROP INDEX `portfolio_tfex_daily_snapshot_date_key` ON `portfolio_tfex_daily_snapshot`;
DROP INDEX `portfolio_tfex_daily_snapshot_date_key_custcode` ON `portfolio_tfex_daily_snapshot`;
DROP INDEX `portfolio_tfex_summary_daily_snapshot_custcode` ON `portfolio_tfex_summary_daily_snapshot`;
DROP INDEX `portfolio_tfex_summary_daily_snapshot_date_key` ON `portfolio_tfex_summary_daily_snapshot`;
DROP INDEX `portfolio_tfex_summary_daily_snapshot_date_key_custcode` ON `portfolio_tfex_summary_daily_snapshot`;
DROP INDEX `portfolio_thai_equity_daily_snapshot_custcode` ON `portfolio_thai_equity_daily_snapshot`;
DROP INDEX `portfolio_thai_equity_daily_snapshot_date_key` ON `portfolio_thai_equity_daily_snapshot`;
DROP INDEX `portfolio_thai_equity_daily_snapshot_date_key_custcode` ON `portfolio_thai_equity_daily_snapshot`;
SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME = 'SequelizeMeta' AND TABLE_SCHEMA = 'portfolio_summary_db';
SHOW INDEX FROM `SequelizeMeta`;
DELETE FROM `SequelizeMeta` WHERE `name` = '20240311070520-add-index-portfolio-daily-snapshot.js';
