name: Argocd tag and deploy

inputs:
  token_image_update:
    description: Github Access Token needed for the checkout of other repositories
    required: true
  infra: 
    description: the repository that the tag change will happen in
    required: false
  target_repository:
    description: the repository that the tag change will happen in
    required: false 
  platform_repository:
    description: the repository that the tag change will happen in
    required: false 
  workflow_repository:
    description: the repository that the tag change will happen in
    required: false 
 

runs:
  using: composite
  steps:
  - name: Checkout Target Repository
    uses: actions/checkout@v3
    with:
      repository: pi-financial/${{ inputs.target_repository }}
      path: config1
      token: ${{ inputs.token_image_update }}

  - name: Checkout platform Repository
    uses: actions/checkout@v3
    with:
      repository: pi-financial/${{ inputs.platform_repository }}
      path: config2
      token: ${{ inputs.token_image_update }}
      
