export const ALL_ROLES = [
  'manage-account',
  'manage-account-links',
  'view-profile',
  'transaction-read',
  'ticket-workspace-view',
  'transaction-export',
  'offline_access',
  'default-roles-backoffice',
  'uma_authorization',
  'ticket-read',
  'ticket-manage',
  'ticket-export',
  'document-portal',
  'application-summary',
  'blocktrade-dashboard',
  'blocktrade-allocation',
  'blocktrade-portfolio',
  'blocktrade-activitylog',
  'blocktrade-calculator',
  'blocktrade-monitor',
  'blocktrade-marginreport',
  'report-read',
  'report-export',
  'ocr-portal',
  'sbl-read',
  'sbl-approve',
  'sbl-edit',
  'ats-registration',
  'sso-read',
  'sso-edit',
  'curated-manager',
  'customer-info-read',
  'customer-info-edit',
] as const

export type Role = (typeof ALL_ROLES)[number]
