enum Currency {
  AED,
  AFN,
  ALL,
  AMD,
  ANG,
  AOA,
  ARS,
  AUD,
  AWG,
  AZN,
  BAM,
  BBD,
  BDT,
  BGN,
  BHD,
  BIF,
  BMD,
  BND,
  BOB,
  BRL,
  BSD,
  BTN,
  BWP,
  BYR,
  BZD,
  CAD,
  CDF,
  CHF,
  CLP,
  CNY,
  COP,
  CRC,
  CUC,
  CUP,
  CVE,
  CZK,
  DJF,
  DKK,
  DOP,
  DZD,
  EGP,
  ERN,
  ETB,
  EUR,
  FJD,
  FKP,
  GBP,
  GEL,
  GGP,
  GHS,
  GIP,
  GMD,
  GNF,
  GTQ,
  GYD,
  HKD,
  HNL,
  HRK,
  HTG,
  HUF,
  IDR,
  ILS,
  IMP,
  INR,
  IQD,
  IRR,
  ISK,
  JEP,
  JMD,
  JOD,
  JPY,
  KES,
  KGS,
  KHR,
  KMF,
  KPW,
  KRW,
  KWD,
  KYD,
  KZT,
  LAK,
  LBP,
  LKR,
  LRD,
  LSL,
  LYD,
  MAD,
  MDL,
  MGA,
  MKD,
  MMK,
  MNT,
  MOP,
  MRO,
  MUR,
  MVR,
  MWK,
  MXN,
  MYR,
  MZN,
  NAD,
  NGN,
  NIO,
  NOK,
  NPR,
  NZD,
  OMR,
  PAB,
  PEN,
  PGK,
  PHP,
  PKR,
  PLN,
  PYG,
  QAR,
  RON,
  RSD,
  RUB,
  RWF,
  SAR,
  SBD,
  SCR,
  SDG,
  SEK,
  SGD,
  SHP,
  SLL,
  SOS,
  SPL,
  SRD,
  STD,
  SVC,
  SYP,
  SZL,
  THB,
  TJS,
  TMT,
  TND,
  TOP,
  TRY,
  TTD,
  TVD,
  TWD,
  TZS,
  UAH,
  UGX,
  USD,
  UYU,
  UZS,
  VEF,
  VND,
  VUV,
  WST,
  XAF,
  XCD,
  XOF,
  XPF,
  YER,
  ZAR,
  ZMW,
  ZWD,
}

interface CurrencyInfo {
  Currency: Currency;
  MinorUnits: number;
  Name: string;
  ISO3: string;
}

export const Currencies: CurrencyInfo[] = [
  {
    Currency: Currency.AED,
    MinorUnits: 100,
    Name: 'United Arab Emirates Dirham',
    ISO3: 'AED',
  },
  {
    Currency: Currency.AFN,
    MinorUnits: 100,
    Name: 'Afghanistan Afghani',
    ISO3: 'AFN',
  },
  { Currency: Currency.ALL, MinorUnits: 100, Name: 'Albania Lek', ISO3: 'ALL' },
  {
    Currency: Currency.AMD,
    MinorUnits: 100,
    Name: 'Armenia Dram',
    ISO3: 'AMD',
  },
  {
    Currency: Currency.ANG,
    MinorUnits: 100,
    Name: 'Netherlands Antilles Guilder',
    ISO3: 'ANG',
  },
  {
    Currency: Currency.AOA,
    MinorUnits: 100,
    Name: 'Angola Kwanza',
    ISO3: 'AOA',
  },
  {
    Currency: Currency.ARS,
    MinorUnits: 100,
    Name: 'Argentina Peso',
    ISO3: 'ARS',
  },
  {
    Currency: Currency.AUD,
    MinorUnits: 100,
    Name: 'Australia Dollar',
    ISO3: 'AUD',
  },
  {
    Currency: Currency.AWG,
    MinorUnits: 100,
    Name: 'Aruba Guilder',
    ISO3: 'AWG',
  },
  {
    Currency: Currency.AZN,
    MinorUnits: 100,
    Name: 'Azerbaijan New Manat',
    ISO3: 'AZN',
  },
  {
    Currency: Currency.BAM,
    MinorUnits: 100,
    Name: 'Bosnia and Herzegovina Convertible Marka',
    ISO3: 'BAM',
  },
  {
    Currency: Currency.BBD,
    MinorUnits: 100,
    Name: 'Barbados Dollar',
    ISO3: 'BBD',
  },
  {
    Currency: Currency.BDT,
    MinorUnits: 100,
    Name: 'Bangladesh Taka',
    ISO3: 'BDT',
  },
  {
    Currency: Currency.BGN,
    MinorUnits: 100,
    Name: 'Bulgaria Lev',
    ISO3: 'BGN',
  },
  {
    Currency: Currency.BHD,
    MinorUnits: 100,
    Name: 'Bahrain Dinar',
    ISO3: 'BHD',
  },
  { Currency: Currency.BIF, MinorUnits: 0, Name: 'Burundi Franc', ISO3: 'BIF' },
  {
    Currency: Currency.BMD,
    MinorUnits: 100,
    Name: 'Bermuda Dollar',
    ISO3: 'BMD',
  },
  {
    Currency: Currency.BND,
    MinorUnits: 100,
    Name: 'Brunei Darussalam Dollar',
    ISO3: 'BND',
  },
  {
    Currency: Currency.BOB,
    MinorUnits: 100,
    Name: 'Bolivia Boliviano',
    ISO3: 'BOB',
  },
  { Currency: Currency.BRL, MinorUnits: 100, Name: 'Brazil Real', ISO3: 'BRL' },
  {
    Currency: Currency.BSD,
    MinorUnits: 100,
    Name: 'Bahamas Dollar',
    ISO3: 'BSD',
  },
  {
    Currency: Currency.BTN,
    MinorUnits: 100,
    Name: 'Bhutan Ngultrum',
    ISO3: 'BTN',
  },
  {
    Currency: Currency.BWP,
    MinorUnits: 100,
    Name: 'Botswana Pula',
    ISO3: 'BWP',
  },
  {
    Currency: Currency.BYR,
    MinorUnits: 100,
    Name: 'Belarus Ruble',
    ISO3: 'BYR',
  },
  {
    Currency: Currency.BZD,
    MinorUnits: 100,
    Name: 'Belize Dollar',
    ISO3: 'BZD',
  },
  {
    Currency: Currency.CAD,
    MinorUnits: 100,
    Name: 'Canada Dollar',
    ISO3: 'CAD',
  },
  {
    Currency: Currency.CDF,
    MinorUnits: 100,
    Name: 'Congo/Kinshasa Franc',
    ISO3: 'CDF',
  },
  {
    Currency: Currency.CHF,
    MinorUnits: 100,
    Name: 'Switzerland Franc',
    ISO3: 'CHF',
  },
  { Currency: Currency.CLP, MinorUnits: 0, Name: 'Chile Peso', ISO3: 'CLP' },
  {
    Currency: Currency.CNY,
    MinorUnits: 100,
    Name: 'China Yuan Renminbi',
    ISO3: 'CNY',
  },
  {
    Currency: Currency.COP,
    MinorUnits: 100,
    Name: 'Colombia Peso',
    ISO3: 'COP',
  },
  {
    Currency: Currency.CRC,
    MinorUnits: 100,
    Name: 'Costa Rica Colon',
    ISO3: 'CRC',
  },
  {
    Currency: Currency.CUC,
    MinorUnits: 100,
    Name: 'Cuba Convertible Peso',
    ISO3: 'CUC',
  },
  { Currency: Currency.CUP, MinorUnits: 100, Name: 'Cuba Peso', ISO3: 'CUP' },
  {
    Currency: Currency.CVE,
    MinorUnits: 100,
    Name: 'Cape Verde Escudo',
    ISO3: 'CVE',
  },
  {
    Currency: Currency.CZK,
    MinorUnits: 100,
    Name: 'Czech Republic Koruna',
    ISO3: 'CZK',
  },
  {
    Currency: Currency.DJF,
    MinorUnits: 0,
    Name: 'Djibouti Franc',
    ISO3: 'DJF',
  },
  {
    Currency: Currency.DKK,
    MinorUnits: 100,
    Name: 'Denmark Krone',
    ISO3: 'DKK',
  },
  {
    Currency: Currency.DOP,
    MinorUnits: 100,
    Name: 'Dominican Republic Peso',
    ISO3: 'DOP',
  },
  {
    Currency: Currency.DZD,
    MinorUnits: 100,
    Name: 'Algeria Dinar',
    ISO3: 'DZD',
  },
  { Currency: Currency.EGP, MinorUnits: 100, Name: 'Egypt Pound', ISO3: 'EGP' },
  {
    Currency: Currency.ERN,
    MinorUnits: 100,
    Name: 'Eritrea Nakfa',
    ISO3: 'ERN',
  },
  {
    Currency: Currency.ETB,
    MinorUnits: 100,
    Name: 'Ethiopia Birr',
    ISO3: 'ETB',
  },
  {
    Currency: Currency.EUR,
    MinorUnits: 100,
    Name: 'Euro Member Countries',
    ISO3: 'EUR',
  },
  { Currency: Currency.FJD, MinorUnits: 100, Name: 'Fiji Dollar', ISO3: 'FJD' },
  {
    Currency: Currency.FKP,
    MinorUnits: 100,
    Name: 'Falkland Islands (Malvinas) Pound',
    ISO3: 'FKP',
  },
  {
    Currency: Currency.GBP,
    MinorUnits: 100,
    Name: 'United Kingdom Pound',
    ISO3: 'GBP',
  },
  {
    Currency: Currency.GEL,
    MinorUnits: 100,
    Name: 'Georgia Lari',
    ISO3: 'GEL',
  },
  {
    Currency: Currency.GGP,
    MinorUnits: 100,
    Name: 'Guernsey Pound',
    ISO3: 'GGP',
  },
  { Currency: Currency.GHS, MinorUnits: 100, Name: 'Ghana Cedi', ISO3: 'GHS' },
  {
    Currency: Currency.GIP,
    MinorUnits: 100,
    Name: 'Gibraltar Pound',
    ISO3: 'GIP',
  },
  {
    Currency: Currency.GMD,
    MinorUnits: 100,
    Name: 'Gambia Dalasi',
    ISO3: 'GMD',
  },
  { Currency: Currency.GNF, MinorUnits: 0, Name: 'Guinea Franc', ISO3: 'GNF' },
  {
    Currency: Currency.GTQ,
    MinorUnits: 100,
    Name: 'Guatemala Quetzal',
    ISO3: 'GTQ',
  },
  {
    Currency: Currency.GYD,
    MinorUnits: 100,
    Name: 'Guyana Dollar',
    ISO3: 'GYD',
  },
  {
    Currency: Currency.HKD,
    MinorUnits: 100,
    Name: 'Hong Kong Dollar',
    ISO3: 'HKD',
  },
  {
    Currency: Currency.HNL,
    MinorUnits: 100,
    Name: 'Honduras Lempira',
    ISO3: 'HNL',
  },
  {
    Currency: Currency.HRK,
    MinorUnits: 100,
    Name: 'Croatia Kuna',
    ISO3: 'HRK',
  },
  {
    Currency: Currency.HTG,
    MinorUnits: 100,
    Name: 'Haiti Gourde',
    ISO3: 'HTG',
  },
  {
    Currency: Currency.HUF,
    MinorUnits: 100,
    Name: 'Hungary Forint',
    ISO3: 'HUF',
  },
  {
    Currency: Currency.IDR,
    MinorUnits: 100,
    Name: 'Indonesia Rupiah',
    ISO3: 'IDR',
  },
  {
    Currency: Currency.ILS,
    MinorUnits: 100,
    Name: 'Israel Shekel',
    ISO3: 'ILS',
  },
  {
    Currency: Currency.IMP,
    MinorUnits: 100,
    Name: 'Isle of Man Pound',
    ISO3: 'IMP',
  },
  { Currency: Currency.INR, MinorUnits: 100, Name: 'India Rupee', ISO3: 'INR' },
  { Currency: Currency.IQD, MinorUnits: 1000, Name: 'Iraq Dinar', ISO3: 'IQD' },
  { Currency: Currency.IRR, MinorUnits: 100, Name: 'Iran Rial', ISO3: 'IRR' },
  { Currency: Currency.ISK, MinorUnits: 0, Name: 'Iceland Krona', ISO3: 'ISK' },
  {
    Currency: Currency.JEP,
    MinorUnits: 100,
    Name: 'Jersey Pound',
    ISO3: 'JEP',
  },
  {
    Currency: Currency.JMD,
    MinorUnits: 100,
    Name: 'Jamaica Dollar',
    ISO3: 'JMD',
  },
  {
    Currency: Currency.JOD,
    MinorUnits: 1000,
    Name: 'Jordan Dinar',
    ISO3: 'JOD',
  },
  { Currency: Currency.JPY, MinorUnits: 0, Name: 'Japan Yen', ISO3: 'JPY' },
  {
    Currency: Currency.KES,
    MinorUnits: 100,
    Name: 'Kenya Shilling',
    ISO3: 'KES',
  },
  {
    Currency: Currency.KGS,
    MinorUnits: 100,
    Name: 'Kyrgyzstan Som',
    ISO3: 'KGS',
  },
  {
    Currency: Currency.KHR,
    MinorUnits: 100,
    Name: 'Cambodia Riel',
    ISO3: 'KHR',
  },
  { Currency: Currency.KMF, MinorUnits: 0, Name: 'Comoros Franc', ISO3: 'KMF' },
  {
    Currency: Currency.KPW,
    MinorUnits: 100,
    Name: 'Korea (North) Won',
    ISO3: 'KPW',
  },
  {
    Currency: Currency.KRW,
    MinorUnits: 0,
    Name: 'Korea (South) Won',
    ISO3: 'KRW',
  },
  {
    Currency: Currency.KWD,
    MinorUnits: 1000,
    Name: 'Kuwait Dinar',
    ISO3: 'KWD',
  },
  {
    Currency: Currency.KYD,
    MinorUnits: 100,
    Name: 'Cayman Islands Dollar',
    ISO3: 'KYD',
  },
  {
    Currency: Currency.KZT,
    MinorUnits: 100,
    Name: 'Kazakhstan Tenge',
    ISO3: 'KZT',
  },
  { Currency: Currency.LAK, MinorUnits: 100, Name: 'Laos Kip', ISO3: 'LAK' },
  {
    Currency: Currency.LBP,
    MinorUnits: 100,
    Name: 'Lebanon Pound',
    ISO3: 'LBP',
  },
  {
    Currency: Currency.LKR,
    MinorUnits: 100,
    Name: 'Sri Lanka Rupee',
    ISO3: 'LKR',
  },
  {
    Currency: Currency.LRD,
    MinorUnits: 100,
    Name: 'Liberia Dollar',
    ISO3: 'LRD',
  },
  {
    Currency: Currency.LSL,
    MinorUnits: 100,
    Name: 'Lesotho Loti',
    ISO3: 'LSL',
  },
  {
    Currency: Currency.LYD,
    MinorUnits: 1000,
    Name: 'Libya Dinar',
    ISO3: 'LYD',
  },
  {
    Currency: Currency.MAD,
    MinorUnits: 100,
    Name: 'Morocco Dirham',
    ISO3: 'MAD',
  },
  { Currency: Currency.MDL, MinorUnits: 100, Name: 'Moldova Leu', ISO3: 'MDL' },
  {
    Currency: Currency.MGA,
    MinorUnits: 100,
    Name: 'Madagascar Ariary',
    ISO3: 'MGA',
  },
  {
    Currency: Currency.MKD,
    MinorUnits: 100,
    Name: 'Macedonia Denar',
    ISO3: 'MKD',
  },
  {
    Currency: Currency.MMK,
    MinorUnits: 100,
    Name: 'Myanmar (Burma) Kyat',
    ISO3: 'MMK',
  },
  {
    Currency: Currency.MNT,
    MinorUnits: 100,
    Name: 'Mongolia Tughrik',
    ISO3: 'MNT',
  },
  {
    Currency: Currency.MOP,
    MinorUnits: 100,
    Name: 'Macau Pataca',
    ISO3: 'MOP',
  },
  {
    Currency: Currency.MRO,
    MinorUnits: 100,
    Name: 'Mauritania Ouguiya',
    ISO3: 'MRO',
  },
  {
    Currency: Currency.MUR,
    MinorUnits: 100,
    Name: 'Mauritius Rupee',
    ISO3: 'MUR',
  },
  {
    Currency: Currency.MVR,
    MinorUnits: 100,
    Name: 'Maldives (Maldive Islands) Rufiyaa',
    ISO3: 'MVR',
  },
  {
    Currency: Currency.MWK,
    MinorUnits: 100,
    Name: 'Malawi Kwacha',
    ISO3: 'MWK',
  },
  { Currency: Currency.MXN, MinorUnits: 100, Name: 'Mexico Peso', ISO3: 'MXN' },
  {
    Currency: Currency.MYR,
    MinorUnits: 100,
    Name: 'Malaysia Ringgit',
    ISO3: 'MYR',
  },
  {
    Currency: Currency.MZN,
    MinorUnits: 100,
    Name: 'Mozambique Metical',
    ISO3: 'MZN',
  },
  {
    Currency: Currency.NAD,
    MinorUnits: 100,
    Name: 'Namibia Dollar',
    ISO3: 'NAD',
  },
  {
    Currency: Currency.NGN,
    MinorUnits: 100,
    Name: 'Nigeria Naira',
    ISO3: 'NGN',
  },
  {
    Currency: Currency.NIO,
    MinorUnits: 100,
    Name: 'Nicaragua Cordoba',
    ISO3: 'NIO',
  },
  {
    Currency: Currency.NOK,
    MinorUnits: 100,
    Name: 'Norway Krone',
    ISO3: 'NOK',
  },
  { Currency: Currency.NPR, MinorUnits: 100, Name: 'Nepal Rupee', ISO3: 'NPR' },
  {
    Currency: Currency.NZD,
    MinorUnits: 100,
    Name: 'New Zealand Dollar',
    ISO3: 'NZD',
  },
  { Currency: Currency.OMR, MinorUnits: 1000, Name: 'Oman Rial', ISO3: 'OMR' },
  {
    Currency: Currency.PAB,
    MinorUnits: 100,
    Name: 'Panama Balboa',
    ISO3: 'PAB',
  },
  {
    Currency: Currency.PEN,
    MinorUnits: 100,
    Name: 'Peru Nuevo Sol',
    ISO3: 'PEN',
  },
  {
    Currency: Currency.PGK,
    MinorUnits: 100,
    Name: 'Papua New Guinea Kina',
    ISO3: 'PGK',
  },
  {
    Currency: Currency.PHP,
    MinorUnits: 100,
    Name: 'Philippines Peso',
    ISO3: 'PHP',
  },
  {
    Currency: Currency.PKR,
    MinorUnits: 100,
    Name: 'Pakistan Rupee',
    ISO3: 'PKR',
  },
  {
    Currency: Currency.PLN,
    MinorUnits: 100,
    Name: 'Poland Zloty',
    ISO3: 'PLN',
  },
  {
    Currency: Currency.PYG,
    MinorUnits: 0,
    Name: 'Paraguay Guarani',
    ISO3: 'PYG',
  },
  { Currency: Currency.QAR, MinorUnits: 100, Name: 'Qatar Riyal', ISO3: 'QAR' },
  {
    Currency: Currency.RON,
    MinorUnits: 100,
    Name: 'Romania New Leu',
    ISO3: 'RON',
  },
  {
    Currency: Currency.RSD,
    MinorUnits: 100,
    Name: 'Serbia Dinar',
    ISO3: 'RSD',
  },
  {
    Currency: Currency.RUB,
    MinorUnits: 100,
    Name: 'Russia Ruble',
    ISO3: 'RUB',
  },
  { Currency: Currency.RWF, MinorUnits: 0, Name: 'Rwanda Franc', ISO3: 'RWF' },
  {
    Currency: Currency.SAR,
    MinorUnits: 100,
    Name: 'Saudi Arabia Riyal',
    ISO3: 'SAR',
  },
  {
    Currency: Currency.SBD,
    MinorUnits: 100,
    Name: 'Solomon Islands Dollar',
    ISO3: 'SBD',
  },
  {
    Currency: Currency.SCR,
    MinorUnits: 100,
    Name: 'Seychelles Rupee',
    ISO3: 'SCR',
  },
  { Currency: Currency.SDG, MinorUnits: 100, Name: 'Sudan Pound', ISO3: 'SDG' },
  {
    Currency: Currency.SEK,
    MinorUnits: 100,
    Name: 'Sweden Krona',
    ISO3: 'SEK',
  },
  {
    Currency: Currency.SGD,
    MinorUnits: 100,
    Name: 'Singapore Dollar',
    ISO3: 'SGD',
  },
  {
    Currency: Currency.SHP,
    MinorUnits: 100,
    Name: 'Saint Helena Pound',
    ISO3: 'SHP',
  },
  {
    Currency: Currency.SLL,
    MinorUnits: 100,
    Name: 'Sierra Leone Leone',
    ISO3: 'SLL',
  },
  {
    Currency: Currency.SOS,
    MinorUnits: 100,
    Name: 'Somalia Shilling',
    ISO3: 'SOS',
  },
  {
    Currency: Currency.SPL,
    MinorUnits: 100,
    Name: 'Seborga Luigino',
    ISO3: 'SPL',
  },
  {
    Currency: Currency.SRD,
    MinorUnits: 100,
    Name: 'Suriname Dollar',
    ISO3: 'SRD',
  },
  {
    Currency: Currency.STD,
    MinorUnits: 100,
    Name: 'São Tomé and Príncipe Dobra',
    ISO3: 'STD',
  },
  {
    Currency: Currency.SVC,
    MinorUnits: 100,
    Name: 'El Salvador Colon',
    ISO3: 'SVC',
  },
  { Currency: Currency.SYP, MinorUnits: 100, Name: 'Syria Pound', ISO3: 'SYP' },
  {
    Currency: Currency.SZL,
    MinorUnits: 100,
    Name: 'Swaziland Lilangeni',
    ISO3: 'SZL',
  },
  {
    Currency: Currency.THB,
    MinorUnits: 100,
    Name: 'Thailand Baht',
    ISO3: 'THB',
  },
  {
    Currency: Currency.TJS,
    MinorUnits: 100,
    Name: 'Tajikistan Somoni',
    ISO3: 'TJS',
  },
  {
    Currency: Currency.TMT,
    MinorUnits: 100,
    Name: 'Turkmenistan Manat',
    ISO3: 'TMT',
  },
  {
    Currency: Currency.TND,
    MinorUnits: 1000,
    Name: 'Tunisia Dinar',
    ISO3: 'TND',
  },
  {
    Currency: Currency.TOP,
    MinorUnits: 100,
    Name: "Tonga Pa'anga",
    ISO3: 'TOP',
  },
  { Currency: Currency.TRY, MinorUnits: 100, Name: 'Turkey Lira', ISO3: 'TRY' },
  {
    Currency: Currency.TTD,
    MinorUnits: 100,
    Name: 'Trinidad and Tobago Dollar',
    ISO3: 'TTD',
  },
  {
    Currency: Currency.TVD,
    MinorUnits: 100,
    Name: 'Tuvalu Dollar',
    ISO3: 'TVD',
  },
  {
    Currency: Currency.TWD,
    MinorUnits: 100,
    Name: 'Taiwan New Dollar',
    ISO3: 'TWD',
  },
  {
    Currency: Currency.TZS,
    MinorUnits: 100,
    Name: 'Tanzania Shilling',
    ISO3: 'TZS',
  },
  {
    Currency: Currency.UAH,
    MinorUnits: 100,
    Name: 'Ukraine Hryvnia',
    ISO3: 'UAH',
  },
  {
    Currency: Currency.UGX,
    MinorUnits: 0,
    Name: 'Uganda Shilling',
    ISO3: 'UGX',
  },
  {
    Currency: Currency.USD,
    MinorUnits: 100,
    Name: 'United States Dollar',
    ISO3: 'USD',
  },
  { Currency: Currency.UYU, MinorUnits: 0, Name: 'Uruguay Peso', ISO3: 'UYU' },
  {
    Currency: Currency.UZS,
    MinorUnits: 100,
    Name: 'Uzbekistan Som',
    ISO3: 'UZS',
  },
  {
    Currency: Currency.VEF,
    MinorUnits: 100,
    Name: 'Venezuela Bolivar',
    ISO3: 'VEF',
  },
  { Currency: Currency.VND, MinorUnits: 0, Name: 'Viet Nam Dong', ISO3: 'VND' },
  { Currency: Currency.VUV, MinorUnits: 0, Name: 'Vanuatu Vatu', ISO3: 'VUV' },
  { Currency: Currency.WST, MinorUnits: 100, Name: 'Samoa Tala', ISO3: 'WST' },
  {
    Currency: Currency.XAF,
    MinorUnits: 0,
    Name: 'Communauté Financière Africaine (BEAC) CFA Franc BEAC',
    ISO3: 'XAF',
  },
  {
    Currency: Currency.XCD,
    MinorUnits: 100,
    Name: 'East Caribbean Dollar',
    ISO3: 'XCD',
  },
  {
    Currency: Currency.XOF,
    MinorUnits: 0,
    Name: 'Communauté Financière Africaine (BCEAO) Franc',
    ISO3: 'XOF',
  },
  {
    Currency: Currency.XPF,
    MinorUnits: 0,
    Name: 'Comptoirs Français du Pacifique (CFP) Franc',
    ISO3: 'XPF',
  },
  { Currency: Currency.YER, MinorUnits: 100, Name: 'Yemen Rial', ISO3: 'YER' },
  {
    Currency: Currency.ZAR,
    MinorUnits: 100,
    Name: 'South Africa Rand',
    ISO3: 'ZAR',
  },
  {
    Currency: Currency.ZMW,
    MinorUnits: 100,
    Name: 'Zambia Kwacha',
    ISO3: 'ZMW',
  },
  {
    Currency: Currency.ZWD,
    MinorUnits: 100,
    Name: 'Zimbabwe Dollar',
    ISO3: 'ZWD',
  },
];
