deployments:
  services:
    ids:
      - b:YXJpOmNsb3VkOmdyYXBoOjpzZXJ2aWNlL2E3MDJmYzVhLTNmMTUtNGU2NS05MDU0LThiNThhMDY5MTlmOS8wODgxMGY2OC1jNmU0LTExZWQtYmRjYS0xMjhiNDI4MTk0MjQ=
      - b:YXJpOmNsb3VkOmdyYXBoOjpzZXJ2aWNlL2E3MDJmYzVhLTNmMTUtNGU2NS05MDU0LThiNThhMDY5MTlmOS80ZjRiNzZjNC1jNzAwLTExZWQtODMyYi0xMjhiNDI4MTk0MjQ=
