/*
Pi.FundMarketData.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package go_client

import (
	"encoding/json"
)

// checks if the PiFundMarketDataAPIModelsResponsesHistoricalNavResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PiFundMarketDataAPIModelsResponsesHistoricalNavResponse{}

// PiFundMarketDataAPIModelsResponsesHistoricalNavResponse struct for PiFundMarketDataAPIModelsResponsesHistoricalNavResponse
type PiFundMarketDataAPIModelsResponsesHistoricalNavResponse struct {
	Timestamp *int64   `json:"timestamp,omitempty"`
	Nav       *float32 `json:"nav,omitempty"`
}

// NewPiFundMarketDataAPIModelsResponsesHistoricalNavResponse instantiates a new PiFundMarketDataAPIModelsResponsesHistoricalNavResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPiFundMarketDataAPIModelsResponsesHistoricalNavResponse() *PiFundMarketDataAPIModelsResponsesHistoricalNavResponse {
	this := PiFundMarketDataAPIModelsResponsesHistoricalNavResponse{}
	return &this
}

// NewPiFundMarketDataAPIModelsResponsesHistoricalNavResponseWithDefaults instantiates a new PiFundMarketDataAPIModelsResponsesHistoricalNavResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPiFundMarketDataAPIModelsResponsesHistoricalNavResponseWithDefaults() *PiFundMarketDataAPIModelsResponsesHistoricalNavResponse {
	this := PiFundMarketDataAPIModelsResponsesHistoricalNavResponse{}
	return &this
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *PiFundMarketDataAPIModelsResponsesHistoricalNavResponse) GetTimestamp() int64 {
	if o == nil || IsNil(o.Timestamp) {
		var ret int64
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PiFundMarketDataAPIModelsResponsesHistoricalNavResponse) GetTimestampOk() (*int64, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *PiFundMarketDataAPIModelsResponsesHistoricalNavResponse) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given int64 and assigns it to the Timestamp field.
func (o *PiFundMarketDataAPIModelsResponsesHistoricalNavResponse) SetTimestamp(v int64) {
	o.Timestamp = &v
}

// GetNav returns the Nav field value if set, zero value otherwise.
func (o *PiFundMarketDataAPIModelsResponsesHistoricalNavResponse) GetNav() float32 {
	if o == nil || IsNil(o.Nav) {
		var ret float32
		return ret
	}
	return *o.Nav
}

// GetNavOk returns a tuple with the Nav field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PiFundMarketDataAPIModelsResponsesHistoricalNavResponse) GetNavOk() (*float32, bool) {
	if o == nil || IsNil(o.Nav) {
		return nil, false
	}
	return o.Nav, true
}

// HasNav returns a boolean if a field has been set.
func (o *PiFundMarketDataAPIModelsResponsesHistoricalNavResponse) HasNav() bool {
	if o != nil && !IsNil(o.Nav) {
		return true
	}

	return false
}

// SetNav gets a reference to the given float32 and assigns it to the Nav field.
func (o *PiFundMarketDataAPIModelsResponsesHistoricalNavResponse) SetNav(v float32) {
	o.Nav = &v
}

func (o PiFundMarketDataAPIModelsResponsesHistoricalNavResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PiFundMarketDataAPIModelsResponsesHistoricalNavResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	if !IsNil(o.Nav) {
		toSerialize["nav"] = o.Nav
	}
	return toSerialize, nil
}

type NullablePiFundMarketDataAPIModelsResponsesHistoricalNavResponse struct {
	value *PiFundMarketDataAPIModelsResponsesHistoricalNavResponse
	isSet bool
}

func (v NullablePiFundMarketDataAPIModelsResponsesHistoricalNavResponse) Get() *PiFundMarketDataAPIModelsResponsesHistoricalNavResponse {
	return v.value
}

func (v *NullablePiFundMarketDataAPIModelsResponsesHistoricalNavResponse) Set(val *PiFundMarketDataAPIModelsResponsesHistoricalNavResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePiFundMarketDataAPIModelsResponsesHistoricalNavResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePiFundMarketDataAPIModelsResponsesHistoricalNavResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePiFundMarketDataAPIModelsResponsesHistoricalNavResponse(val *PiFundMarketDataAPIModelsResponsesHistoricalNavResponse) *NullablePiFundMarketDataAPIModelsResponsesHistoricalNavResponse {
	return &NullablePiFundMarketDataAPIModelsResponsesHistoricalNavResponse{value: val, isSet: true}
}

func (v NullablePiFundMarketDataAPIModelsResponsesHistoricalNavResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePiFundMarketDataAPIModelsResponsesHistoricalNavResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
