/*
Pi.FundMarketData.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package go_client

import (
	"encoding/json"
)

// checks if the PiFundMarketDataAPIModelsResponsesFundSearchResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PiFundMarketDataAPIModelsResponsesFundSearchResponse{}

// PiFundMarketDataAPIModelsResponsesFundSearchResponse struct for PiFundMarketDataAPIModelsResponsesFundSearchResponse
type PiFundMarketDataAPIModelsResponsesFundSearchResponse struct {
	Symbol              NullableString  `json:"symbol,omitempty"`
	Currency            NullableString  `json:"currency,omitempty"`
	Name                NullableString  `json:"name,omitempty"`
	NavChange           NullableFloat32 `json:"navChange,omitempty"`
	Nav                 *float32        `json:"nav,omitempty"`
	NavChangePercentage NullableFloat64 `json:"navChangePercentage,omitempty"`
	AmcLogo             NullableString  `json:"amcLogo,omitempty"`
}

// NewPiFundMarketDataAPIModelsResponsesFundSearchResponse instantiates a new PiFundMarketDataAPIModelsResponsesFundSearchResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPiFundMarketDataAPIModelsResponsesFundSearchResponse() *PiFundMarketDataAPIModelsResponsesFundSearchResponse {
	this := PiFundMarketDataAPIModelsResponsesFundSearchResponse{}
	return &this
}

// NewPiFundMarketDataAPIModelsResponsesFundSearchResponseWithDefaults instantiates a new PiFundMarketDataAPIModelsResponsesFundSearchResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPiFundMarketDataAPIModelsResponsesFundSearchResponseWithDefaults() *PiFundMarketDataAPIModelsResponsesFundSearchResponse {
	this := PiFundMarketDataAPIModelsResponsesFundSearchResponse{}
	return &this
}

// GetSymbol returns the Symbol field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) GetSymbol() string {
	if o == nil || IsNil(o.Symbol.Get()) {
		var ret string
		return ret
	}
	return *o.Symbol.Get()
}

// GetSymbolOk returns a tuple with the Symbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) GetSymbolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Symbol.Get(), o.Symbol.IsSet()
}

// HasSymbol returns a boolean if a field has been set.
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) HasSymbol() bool {
	if o != nil && o.Symbol.IsSet() {
		return true
	}

	return false
}

// SetSymbol gets a reference to the given NullableString and assigns it to the Symbol field.
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) SetSymbol(v string) {
	o.Symbol.Set(&v)
}

// SetSymbolNil sets the value for Symbol to be an explicit nil
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) SetSymbolNil() {
	o.Symbol.Set(nil)
}

// UnsetSymbol ensures that no value is present for Symbol, not even an explicit nil
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) UnsetSymbol() {
	o.Symbol.Unset()
}

// GetCurrency returns the Currency field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) GetCurrency() string {
	if o == nil || IsNil(o.Currency.Get()) {
		var ret string
		return ret
	}
	return *o.Currency.Get()
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Currency.Get(), o.Currency.IsSet()
}

// HasCurrency returns a boolean if a field has been set.
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) HasCurrency() bool {
	if o != nil && o.Currency.IsSet() {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given NullableString and assigns it to the Currency field.
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) SetCurrency(v string) {
	o.Currency.Set(&v)
}

// SetCurrencyNil sets the value for Currency to be an explicit nil
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) SetCurrencyNil() {
	o.Currency.Set(nil)
}

// UnsetCurrency ensures that no value is present for Currency, not even an explicit nil
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) UnsetCurrency() {
	o.Currency.Unset()
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) UnsetName() {
	o.Name.Unset()
}

// GetNavChange returns the NavChange field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) GetNavChange() float32 {
	if o == nil || IsNil(o.NavChange.Get()) {
		var ret float32
		return ret
	}
	return *o.NavChange.Get()
}

// GetNavChangeOk returns a tuple with the NavChange field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) GetNavChangeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.NavChange.Get(), o.NavChange.IsSet()
}

// HasNavChange returns a boolean if a field has been set.
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) HasNavChange() bool {
	if o != nil && o.NavChange.IsSet() {
		return true
	}

	return false
}

// SetNavChange gets a reference to the given NullableFloat32 and assigns it to the NavChange field.
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) SetNavChange(v float32) {
	o.NavChange.Set(&v)
}

// SetNavChangeNil sets the value for NavChange to be an explicit nil
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) SetNavChangeNil() {
	o.NavChange.Set(nil)
}

// UnsetNavChange ensures that no value is present for NavChange, not even an explicit nil
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) UnsetNavChange() {
	o.NavChange.Unset()
}

// GetNav returns the Nav field value if set, zero value otherwise.
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) GetNav() float32 {
	if o == nil || IsNil(o.Nav) {
		var ret float32
		return ret
	}
	return *o.Nav
}

// GetNavOk returns a tuple with the Nav field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) GetNavOk() (*float32, bool) {
	if o == nil || IsNil(o.Nav) {
		return nil, false
	}
	return o.Nav, true
}

// HasNav returns a boolean if a field has been set.
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) HasNav() bool {
	if o != nil && !IsNil(o.Nav) {
		return true
	}

	return false
}

// SetNav gets a reference to the given float32 and assigns it to the Nav field.
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) SetNav(v float32) {
	o.Nav = &v
}

// GetNavChangePercentage returns the NavChangePercentage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) GetNavChangePercentage() float64 {
	if o == nil || IsNil(o.NavChangePercentage.Get()) {
		var ret float64
		return ret
	}
	return *o.NavChangePercentage.Get()
}

// GetNavChangePercentageOk returns a tuple with the NavChangePercentage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) GetNavChangePercentageOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.NavChangePercentage.Get(), o.NavChangePercentage.IsSet()
}

// HasNavChangePercentage returns a boolean if a field has been set.
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) HasNavChangePercentage() bool {
	if o != nil && o.NavChangePercentage.IsSet() {
		return true
	}

	return false
}

// SetNavChangePercentage gets a reference to the given NullableFloat64 and assigns it to the NavChangePercentage field.
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) SetNavChangePercentage(v float64) {
	o.NavChangePercentage.Set(&v)
}

// SetNavChangePercentageNil sets the value for NavChangePercentage to be an explicit nil
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) SetNavChangePercentageNil() {
	o.NavChangePercentage.Set(nil)
}

// UnsetNavChangePercentage ensures that no value is present for NavChangePercentage, not even an explicit nil
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) UnsetNavChangePercentage() {
	o.NavChangePercentage.Unset()
}

// GetAmcLogo returns the AmcLogo field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) GetAmcLogo() string {
	if o == nil || IsNil(o.AmcLogo.Get()) {
		var ret string
		return ret
	}
	return *o.AmcLogo.Get()
}

// GetAmcLogoOk returns a tuple with the AmcLogo field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) GetAmcLogoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AmcLogo.Get(), o.AmcLogo.IsSet()
}

// HasAmcLogo returns a boolean if a field has been set.
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) HasAmcLogo() bool {
	if o != nil && o.AmcLogo.IsSet() {
		return true
	}

	return false
}

// SetAmcLogo gets a reference to the given NullableString and assigns it to the AmcLogo field.
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) SetAmcLogo(v string) {
	o.AmcLogo.Set(&v)
}

// SetAmcLogoNil sets the value for AmcLogo to be an explicit nil
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) SetAmcLogoNil() {
	o.AmcLogo.Set(nil)
}

// UnsetAmcLogo ensures that no value is present for AmcLogo, not even an explicit nil
func (o *PiFundMarketDataAPIModelsResponsesFundSearchResponse) UnsetAmcLogo() {
	o.AmcLogo.Unset()
}

func (o PiFundMarketDataAPIModelsResponsesFundSearchResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PiFundMarketDataAPIModelsResponsesFundSearchResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Symbol.IsSet() {
		toSerialize["symbol"] = o.Symbol.Get()
	}
	if o.Currency.IsSet() {
		toSerialize["currency"] = o.Currency.Get()
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.NavChange.IsSet() {
		toSerialize["navChange"] = o.NavChange.Get()
	}
	if !IsNil(o.Nav) {
		toSerialize["nav"] = o.Nav
	}
	if o.NavChangePercentage.IsSet() {
		toSerialize["navChangePercentage"] = o.NavChangePercentage.Get()
	}
	if o.AmcLogo.IsSet() {
		toSerialize["amcLogo"] = o.AmcLogo.Get()
	}
	return toSerialize, nil
}

type NullablePiFundMarketDataAPIModelsResponsesFundSearchResponse struct {
	value *PiFundMarketDataAPIModelsResponsesFundSearchResponse
	isSet bool
}

func (v NullablePiFundMarketDataAPIModelsResponsesFundSearchResponse) Get() *PiFundMarketDataAPIModelsResponsesFundSearchResponse {
	return v.value
}

func (v *NullablePiFundMarketDataAPIModelsResponsesFundSearchResponse) Set(val *PiFundMarketDataAPIModelsResponsesFundSearchResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePiFundMarketDataAPIModelsResponsesFundSearchResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePiFundMarketDataAPIModelsResponsesFundSearchResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePiFundMarketDataAPIModelsResponsesFundSearchResponse(val *PiFundMarketDataAPIModelsResponsesFundSearchResponse) *NullablePiFundMarketDataAPIModelsResponsesFundSearchResponse {
	return &NullablePiFundMarketDataAPIModelsResponsesFundSearchResponse{value: val, isSet: true}
}

func (v NullablePiFundMarketDataAPIModelsResponsesFundSearchResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePiFundMarketDataAPIModelsResponsesFundSearchResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
