/*
Pi.User.API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package go_client

import (
	"encoding/json"
)

// checks if the PiUserAPIModelsUserInfoCitizenIdResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PiUserAPIModelsUserInfoCitizenIdResponse{}

// PiUserAPIModelsUserInfoCitizenIdResponse struct for PiUserAPIModelsUserInfoCitizenIdResponse
type PiUserAPIModelsUserInfoCitizenIdResponse struct {
	Id        *string        `json:"id,omitempty"`
	CitizenId NullableString `json:"citizenId,omitempty"`
}

// NewPiUserAPIModelsUserInfoCitizenIdResponse instantiates a new PiUserAPIModelsUserInfoCitizenIdResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPiUserAPIModelsUserInfoCitizenIdResponse() *PiUserAPIModelsUserInfoCitizenIdResponse {
	this := PiUserAPIModelsUserInfoCitizenIdResponse{}
	return &this
}

// NewPiUserAPIModelsUserInfoCitizenIdResponseWithDefaults instantiates a new PiUserAPIModelsUserInfoCitizenIdResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPiUserAPIModelsUserInfoCitizenIdResponseWithDefaults() *PiUserAPIModelsUserInfoCitizenIdResponse {
	this := PiUserAPIModelsUserInfoCitizenIdResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PiUserAPIModelsUserInfoCitizenIdResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PiUserAPIModelsUserInfoCitizenIdResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PiUserAPIModelsUserInfoCitizenIdResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PiUserAPIModelsUserInfoCitizenIdResponse) SetId(v string) {
	o.Id = &v
}

// GetCitizenId returns the CitizenId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PiUserAPIModelsUserInfoCitizenIdResponse) GetCitizenId() string {
	if o == nil || IsNil(o.CitizenId.Get()) {
		var ret string
		return ret
	}
	return *o.CitizenId.Get()
}

// GetCitizenIdOk returns a tuple with the CitizenId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PiUserAPIModelsUserInfoCitizenIdResponse) GetCitizenIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CitizenId.Get(), o.CitizenId.IsSet()
}

// HasCitizenId returns a boolean if a field has been set.
func (o *PiUserAPIModelsUserInfoCitizenIdResponse) HasCitizenId() bool {
	if o != nil && o.CitizenId.IsSet() {
		return true
	}

	return false
}

// SetCitizenId gets a reference to the given NullableString and assigns it to the CitizenId field.
func (o *PiUserAPIModelsUserInfoCitizenIdResponse) SetCitizenId(v string) {
	o.CitizenId.Set(&v)
}

// SetCitizenIdNil sets the value for CitizenId to be an explicit nil
func (o *PiUserAPIModelsUserInfoCitizenIdResponse) SetCitizenIdNil() {
	o.CitizenId.Set(nil)
}

// UnsetCitizenId ensures that no value is present for CitizenId, not even an explicit nil
func (o *PiUserAPIModelsUserInfoCitizenIdResponse) UnsetCitizenId() {
	o.CitizenId.Unset()
}

func (o PiUserAPIModelsUserInfoCitizenIdResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PiUserAPIModelsUserInfoCitizenIdResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if o.CitizenId.IsSet() {
		toSerialize["citizenId"] = o.CitizenId.Get()
	}
	return toSerialize, nil
}

type NullablePiUserAPIModelsUserInfoCitizenIdResponse struct {
	value *PiUserAPIModelsUserInfoCitizenIdResponse
	isSet bool
}

func (v NullablePiUserAPIModelsUserInfoCitizenIdResponse) Get() *PiUserAPIModelsUserInfoCitizenIdResponse {
	return v.value
}

func (v *NullablePiUserAPIModelsUserInfoCitizenIdResponse) Set(val *PiUserAPIModelsUserInfoCitizenIdResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePiUserAPIModelsUserInfoCitizenIdResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePiUserAPIModelsUserInfoCitizenIdResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePiUserAPIModelsUserInfoCitizenIdResponse(val *PiUserAPIModelsUserInfoCitizenIdResponse) *NullablePiUserAPIModelsUserInfoCitizenIdResponse {
	return &NullablePiUserAPIModelsUserInfoCitizenIdResponse{value: val, isSet: true}
}

func (v NullablePiUserAPIModelsUserInfoCitizenIdResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePiUserAPIModelsUserInfoCitizenIdResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
