using Pi.SetMarketData.Domain.Models.Response;
namespace Pi.SetMarketData.Application.Queries;
public record PostMarketGlobalEquityInstrumentInfoResponse(MarketGlobalEquityInstrumentInfoResponse Data);