/*
Pi User Service V2

Contain Generic Information.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the DtoCreateExternalAccountRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoCreateExternalAccountRequest{}

// DtoCreateExternalAccountRequest struct for DtoCreateExternalAccountRequest
type DtoCreateExternalAccountRequest struct {
	Account      *string `json:"account,omitempty"`
	CustomerCode *string `json:"customerCode,omitempty"`
	Id           *string `json:"id,omitempty"`
	Product      *string `json:"product,omitempty"`
	ProviderId   *int32  `json:"providerId,omitempty"`
}

// NewDtoCreateExternalAccountRequest instantiates a new DtoCreateExternalAccountRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoCreateExternalAccountRequest() *DtoCreateExternalAccountRequest {
	this := DtoCreateExternalAccountRequest{}
	return &this
}

// NewDtoCreateExternalAccountRequestWithDefaults instantiates a new DtoCreateExternalAccountRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoCreateExternalAccountRequestWithDefaults() *DtoCreateExternalAccountRequest {
	this := DtoCreateExternalAccountRequest{}
	return &this
}

// GetAccount returns the Account field value if set, zero value otherwise.
func (o *DtoCreateExternalAccountRequest) GetAccount() string {
	if o == nil || IsNil(o.Account) {
		var ret string
		return ret
	}
	return *o.Account
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreateExternalAccountRequest) GetAccountOk() (*string, bool) {
	if o == nil || IsNil(o.Account) {
		return nil, false
	}
	return o.Account, true
}

// HasAccount returns a boolean if a field has been set.
func (o *DtoCreateExternalAccountRequest) HasAccount() bool {
	if o != nil && !IsNil(o.Account) {
		return true
	}

	return false
}

// SetAccount gets a reference to the given string and assigns it to the Account field.
func (o *DtoCreateExternalAccountRequest) SetAccount(v string) {
	o.Account = &v
}

// GetCustomerCode returns the CustomerCode field value if set, zero value otherwise.
func (o *DtoCreateExternalAccountRequest) GetCustomerCode() string {
	if o == nil || IsNil(o.CustomerCode) {
		var ret string
		return ret
	}
	return *o.CustomerCode
}

// GetCustomerCodeOk returns a tuple with the CustomerCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreateExternalAccountRequest) GetCustomerCodeOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerCode) {
		return nil, false
	}
	return o.CustomerCode, true
}

// HasCustomerCode returns a boolean if a field has been set.
func (o *DtoCreateExternalAccountRequest) HasCustomerCode() bool {
	if o != nil && !IsNil(o.CustomerCode) {
		return true
	}

	return false
}

// SetCustomerCode gets a reference to the given string and assigns it to the CustomerCode field.
func (o *DtoCreateExternalAccountRequest) SetCustomerCode(v string) {
	o.CustomerCode = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DtoCreateExternalAccountRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreateExternalAccountRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DtoCreateExternalAccountRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DtoCreateExternalAccountRequest) SetId(v string) {
	o.Id = &v
}

// GetProduct returns the Product field value if set, zero value otherwise.
func (o *DtoCreateExternalAccountRequest) GetProduct() string {
	if o == nil || IsNil(o.Product) {
		var ret string
		return ret
	}
	return *o.Product
}

// GetProductOk returns a tuple with the Product field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreateExternalAccountRequest) GetProductOk() (*string, bool) {
	if o == nil || IsNil(o.Product) {
		return nil, false
	}
	return o.Product, true
}

// HasProduct returns a boolean if a field has been set.
func (o *DtoCreateExternalAccountRequest) HasProduct() bool {
	if o != nil && !IsNil(o.Product) {
		return true
	}

	return false
}

// SetProduct gets a reference to the given string and assigns it to the Product field.
func (o *DtoCreateExternalAccountRequest) SetProduct(v string) {
	o.Product = &v
}

// GetProviderId returns the ProviderId field value if set, zero value otherwise.
func (o *DtoCreateExternalAccountRequest) GetProviderId() int32 {
	if o == nil || IsNil(o.ProviderId) {
		var ret int32
		return ret
	}
	return *o.ProviderId
}

// GetProviderIdOk returns a tuple with the ProviderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoCreateExternalAccountRequest) GetProviderIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ProviderId) {
		return nil, false
	}
	return o.ProviderId, true
}

// HasProviderId returns a boolean if a field has been set.
func (o *DtoCreateExternalAccountRequest) HasProviderId() bool {
	if o != nil && !IsNil(o.ProviderId) {
		return true
	}

	return false
}

// SetProviderId gets a reference to the given int32 and assigns it to the ProviderId field.
func (o *DtoCreateExternalAccountRequest) SetProviderId(v int32) {
	o.ProviderId = &v
}

func (o DtoCreateExternalAccountRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoCreateExternalAccountRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Account) {
		toSerialize["account"] = o.Account
	}
	if !IsNil(o.CustomerCode) {
		toSerialize["customerCode"] = o.CustomerCode
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Product) {
		toSerialize["product"] = o.Product
	}
	if !IsNil(o.ProviderId) {
		toSerialize["providerId"] = o.ProviderId
	}
	return toSerialize, nil
}

type NullableDtoCreateExternalAccountRequest struct {
	value *DtoCreateExternalAccountRequest
	isSet bool
}

func (v NullableDtoCreateExternalAccountRequest) Get() *DtoCreateExternalAccountRequest {
	return v.value
}

func (v *NullableDtoCreateExternalAccountRequest) Set(val *DtoCreateExternalAccountRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoCreateExternalAccountRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoCreateExternalAccountRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoCreateExternalAccountRequest(val *DtoCreateExternalAccountRequest) *NullableDtoCreateExternalAccountRequest {
	return &NullableDtoCreateExternalAccountRequest{value: val, isSet: true}
}

func (v NullableDtoCreateExternalAccountRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoCreateExternalAccountRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
