/*
Pi User Service V2

Contain Generic Information.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the InternalV1TradingAccountsMarketingInfosGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InternalV1TradingAccountsMarketingInfosGet200Response{}

// InternalV1TradingAccountsMarketingInfosGet200Response struct for InternalV1TradingAccountsMarketingInfosGet200Response
type InternalV1TradingAccountsMarketingInfosGet200Response struct {
	Code *string                           `json:"code,omitempty"`
	Msg  *string                           `json:"msg,omitempty"`
	Data []DtoTradingAccountsMarketingInfo `json:"data,omitempty"`
}

// NewInternalV1TradingAccountsMarketingInfosGet200Response instantiates a new InternalV1TradingAccountsMarketingInfosGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInternalV1TradingAccountsMarketingInfosGet200Response() *InternalV1TradingAccountsMarketingInfosGet200Response {
	this := InternalV1TradingAccountsMarketingInfosGet200Response{}
	return &this
}

// NewInternalV1TradingAccountsMarketingInfosGet200ResponseWithDefaults instantiates a new InternalV1TradingAccountsMarketingInfosGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInternalV1TradingAccountsMarketingInfosGet200ResponseWithDefaults() *InternalV1TradingAccountsMarketingInfosGet200Response {
	this := InternalV1TradingAccountsMarketingInfosGet200Response{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *InternalV1TradingAccountsMarketingInfosGet200Response) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalV1TradingAccountsMarketingInfosGet200Response) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *InternalV1TradingAccountsMarketingInfosGet200Response) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *InternalV1TradingAccountsMarketingInfosGet200Response) SetCode(v string) {
	o.Code = &v
}

// GetMsg returns the Msg field value if set, zero value otherwise.
func (o *InternalV1TradingAccountsMarketingInfosGet200Response) GetMsg() string {
	if o == nil || IsNil(o.Msg) {
		var ret string
		return ret
	}
	return *o.Msg
}

// GetMsgOk returns a tuple with the Msg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalV1TradingAccountsMarketingInfosGet200Response) GetMsgOk() (*string, bool) {
	if o == nil || IsNil(o.Msg) {
		return nil, false
	}
	return o.Msg, true
}

// HasMsg returns a boolean if a field has been set.
func (o *InternalV1TradingAccountsMarketingInfosGet200Response) HasMsg() bool {
	if o != nil && !IsNil(o.Msg) {
		return true
	}

	return false
}

// SetMsg gets a reference to the given string and assigns it to the Msg field.
func (o *InternalV1TradingAccountsMarketingInfosGet200Response) SetMsg(v string) {
	o.Msg = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *InternalV1TradingAccountsMarketingInfosGet200Response) GetData() []DtoTradingAccountsMarketingInfo {
	if o == nil || IsNil(o.Data) {
		var ret []DtoTradingAccountsMarketingInfo
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalV1TradingAccountsMarketingInfosGet200Response) GetDataOk() ([]DtoTradingAccountsMarketingInfo, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *InternalV1TradingAccountsMarketingInfosGet200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []DtoTradingAccountsMarketingInfo and assigns it to the Data field.
func (o *InternalV1TradingAccountsMarketingInfosGet200Response) SetData(v []DtoTradingAccountsMarketingInfo) {
	o.Data = v
}

func (o InternalV1TradingAccountsMarketingInfosGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InternalV1TradingAccountsMarketingInfosGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Msg) {
		toSerialize["msg"] = o.Msg
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableInternalV1TradingAccountsMarketingInfosGet200Response struct {
	value *InternalV1TradingAccountsMarketingInfosGet200Response
	isSet bool
}

func (v NullableInternalV1TradingAccountsMarketingInfosGet200Response) Get() *InternalV1TradingAccountsMarketingInfosGet200Response {
	return v.value
}

func (v *NullableInternalV1TradingAccountsMarketingInfosGet200Response) Set(val *InternalV1TradingAccountsMarketingInfosGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableInternalV1TradingAccountsMarketingInfosGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableInternalV1TradingAccountsMarketingInfosGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInternalV1TradingAccountsMarketingInfosGet200Response(val *InternalV1TradingAccountsMarketingInfosGet200Response) *NullableInternalV1TradingAccountsMarketingInfosGet200Response {
	return &NullableInternalV1TradingAccountsMarketingInfosGet200Response{value: val, isSet: true}
}

func (v NullableInternalV1TradingAccountsMarketingInfosGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInternalV1TradingAccountsMarketingInfosGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
