ALTER TABLE `portfolio_bond_daily_snapshot` ADD INDEX `portfolio_bond_daily_snapshot_custcode` (`custcode`);
ALTER TABLE `portfolio_bond_daily_snapshot` ADD INDEX `portfolio_bond_daily_snapshot_date_key` (`date_key`);
ALTER TABLE `portfolio_bond_daily_snapshot` ADD INDEX `portfolio_bond_daily_snapshot_date_key_custcode` (`date_key`, `custcode`);
ALTER TABLE `portfolio_cash_daily_snapshot` ADD INDEX `portfolio_cash_daily_snapshot_custcode` (`custcode`);
ALTER TABLE `portfolio_cash_daily_snapshot` ADD INDEX `portfolio_cash_daily_snapshot_date_key` (`date_key`);
ALTER TABLE `portfolio_cash_daily_snapshot` ADD INDEX `portfolio_cash_daily_snapshot_date_key_custcode` (`date_key`, `custcode`);
ALTER TABLE `portfolio_global_equity_daily_snapshot` ADD INDEX `portfolio_global_equity_daily_snapshot_custcode` (`custcode`);
ALTER TABLE `portfolio_global_equity_daily_snapshot` ADD INDEX `portfolio_global_equity_daily_snapshot_date_key` (`date_key`);
ALTER TABLE `portfolio_global_equity_daily_snapshot` ADD INDEX `portfolio_global_equity_daily_snapshot_date_key_custcode` (`date_key`, `custcode`);
ALTER TABLE `portfolio_global_equity_otc_daily_snapshot` ADD INDEX `portfolio_global_equity_otc_daily_snapshot_custcode` (`custcode`);
ALTER TABLE `portfolio_global_equity_otc_daily_snapshot` ADD INDEX `portfolio_global_equity_otc_daily_snapshot_date_key` (`date_key`);
ALTER TABLE `portfolio_global_equity_otc_daily_snapshot` ADD INDEX `portfolio_global_equity_otc_daily_snapshot_date_key_custcode` (`date_key`, `custcode`);
ALTER TABLE `portfolio_mutual_fund_daily_snapshot` ADD INDEX `portfolio_mutual_fund_daily_snapshot_custcode` (`custcode`);
ALTER TABLE `portfolio_mutual_fund_daily_snapshot` ADD INDEX `portfolio_mutual_fund_daily_snapshot_date_key` (`date_key`);
ALTER TABLE `portfolio_mutual_fund_daily_snapshot` ADD INDEX `portfolio_mutual_fund_daily_snapshot_date_key_custcode` (`date_key`, `custcode`);
ALTER TABLE `portfolio_structured_product_daily_snapshot` ADD INDEX `portfolio_structured_product_daily_snapshot_custcode` (`custcode`);
ALTER TABLE `portfolio_structured_product_daily_snapshot` ADD INDEX `portfolio_structured_product_daily_snapshot_date_key` (`date_key`);
ALTER TABLE `portfolio_structured_product_daily_snapshot` ADD INDEX `portfolio_structured_product_daily_snapshot_date_key_custcode` (`date_key`, `custcode`);
ALTER TABLE `portfolio_summary_daily_snapshot` ADD INDEX `portfolio_summary_daily_snapshot_custcode` (`custcode`);
ALTER TABLE `portfolio_summary_daily_snapshot` ADD INDEX `portfolio_summary_daily_snapshot_date_key` (`date_key`);
ALTER TABLE `portfolio_summary_daily_snapshot` ADD INDEX `portfolio_summary_daily_snapshot_date_key_custcode_mktid` (`date_key`, `custcode`, `mktid`);
ALTER TABLE `portfolio_tfex_daily_snapshot` ADD INDEX `portfolio_tfex_daily_snapshot_custcode` (`custcode`);
ALTER TABLE `portfolio_tfex_daily_snapshot` ADD INDEX `portfolio_tfex_daily_snapshot_date_key` (`date_key`);
ALTER TABLE `portfolio_tfex_daily_snapshot` ADD INDEX `portfolio_tfex_daily_snapshot_date_key_custcode` (`date_key`, `custcode`);
ALTER TABLE `portfolio_tfex_summary_daily_snapshot` ADD INDEX `portfolio_tfex_summary_daily_snapshot_custcode` (`custcode`);
ALTER TABLE `portfolio_tfex_summary_daily_snapshot` ADD INDEX `portfolio_tfex_summary_daily_snapshot_date_key` (`date_key`);
ALTER TABLE `portfolio_tfex_summary_daily_snapshot` ADD INDEX `portfolio_tfex_summary_daily_snapshot_date_key_custcode` (`date_key`, `custcode`);
ALTER TABLE `portfolio_thai_equity_daily_snapshot` ADD INDEX `portfolio_thai_equity_daily_snapshot_custcode` (`custcode`);
ALTER TABLE `portfolio_thai_equity_daily_snapshot` ADD INDEX `portfolio_thai_equity_daily_snapshot_date_key` (`date_key`);
ALTER TABLE `portfolio_thai_equity_daily_snapshot` ADD INDEX `portfolio_thai_equity_daily_snapshot_date_key_custcode` (`date_key`, `custcode`);
SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME = 'SequelizeMeta' AND TABLE_SCHEMA = 'portfolio_summary_db';
SHOW INDEX FROM `SequelizeMeta`;\nINSERT INTO `SequelizeMeta` (`name`) VALUES ('20240311070520-add-index-portfolio-daily-snapshot.js');
