ALTER TABLE `exante_trades` CHANGE `time` `time` DATETIME NOT NULL;
ALTER TABLE `exante_trades` CHANGE `account_id` `account_id` VARCHAR(255) NOT NULL;
ALTER TABLE `exante_trades` CHANGE `side` `side` VARCHAR(255) NOT NULL;
ALTER TABLE `exante_trades` CHANGE `symbol_id` `symbol_id` VARCHAR(255) NOT NULL;
ALTER TABLE `exante_trades` CHANGE `isin` `isin` VARCHAR(255) NOT NULL;
ALTER TABLE `exante_trades` CHANGE `type` `type` VARCHAR(255) NOT NULL;
ALTER TABLE `exante_trades` CHANGE `price` `price` DECIMAL(65,8) NOT NULL;
ALTER TABLE `exante_trades` CHANGE `currency` `currency` VARCHAR(255) NOT NULL;
ALTER TABLE `exante_trades` CHANGE `quantity` `quantity` INTEGER NOT NULL;
ALTER TABLE `exante_trades` CHANGE `commission` `commission` DECIMAL(65,8) NOT NULL;
ALTER TABLE `exante_trades` CHANGE `commission_currency` `commission_currency` VARCHAR(255) NOT NULL;
ALTER TABLE `exante_trades` CHANGE `p_and_l` `p_and_l` DECIMAL(65,8) NOT NULL;
ALTER TABLE `exante_trades` CHANGE `traded_volume` `traded_volume` DECIMAL(65,8) NOT NULL;
ALTER TABLE `exante_trades` CHANGE `order_id` `order_id` VARCHAR(255) NOT NULL;
ALTER TABLE `exante_trades` CHANGE `order_pos` `order_pos` INTEGER NOT NULL;
ALTER TABLE `exante_trades` CHANGE `value_date` `value_date` DATE NOT NULL;
ALTER TABLE `exante_trades` CHANGE `trade_type` `trade_type` VARCHAR(255) NOT NULL;
SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME = 'SequelizeMeta' AND TABLE_SCHEMA = 'reconcile_db';
SHOW INDEX FROM `SequelizeMeta`;
DELETE FROM `SequelizeMeta` WHERE `name` = '20231219065220-update-exante-trades-table-property.js';
