import { FieldConfig } from './FieldConfig';

export const clientAccountFileConfig: FieldConfig[] = [
  { name: 'branch', start: 1, length: 10, empty: true },
  { name: 'custcode', start: 11, length: 15 },
  { name: 'account', start: 26, length: 20 },
  { name: 'thainame', start: 46, length: 71 },
  { name: 'engname', start: 117, length: 71, empty: true },
  { name: 'accounttype', start: 188, length: 1, empty: true },
  { name: 'appcreditline', start: 189, length: 22 },
  { name: 'credittype', start: 211, length: 1, empty: true },
  { name: 'clienttype', start: 212, length: 1, empty: true },
  { name: 'password', start: 213, length: 20, empty: true },
  { name: 'canbuy', start: 233, length: 1 },
  { name: 'cansell', start: 234, length: 1 },
  { name: 'overcredit', start: 235, length: 1, empty: true },
  { name: 'mark_to_market', start: 236, length: 1, empty: true },
  { name: 'viewconfirm', start: 237, length: 1, empty: true },
  { name: 'exceedcrdapp', start: 238, length: 10, empty: true },
  { name: 'maxvalperord', start: 248, length: 22, empty: true },
  { name: 'cashbalance', start: 270, length: 22 },
  { name: 'commrate', start: 292, length: 3, empty: true },
  { name: 'whtrate', start: 295, length: 3, empty: true },
  { name: 'accstatus', start: 298, length: 1 },
  { name: 'closingmthod', start: 299, length: 1, empty: true },
  { name: 'marginmethod', start: 300, length: 1, empty: true },
  { name: 'aecode', start: 301, length: 10 },
  { name: 'aename', start: 311, length: 35, empty: true },
  { name: 'tchacct', start: 346, length: 15, empty: true },
  { name: 'clientcode', start: 361, length: 1, empty: true },
  { name: 'staffflag', start: 362, length: 1, empty: true },
  { name: 'cardidtype', start: 363, length: 1, empty: true },
  { name: 'cardid', start: 364, length: 20, empty: true },
  { name: 'broker_internet', start: 384, length: 1, empty: true },
  { name: 'margingroup', start: 385, length: 10, empty: true },
  { name: 'margincalmet', start: 395, length: 1, empty: true },
  { name: 'custodianaccno', start: 396, length: 15, empty: true },
  { name: 'othercollate', start: 411, length: 13, empty: true },
  { name: 'fccollat', start: 424, length: 10, empty: true },
  { name: 'comgroup', start: 434, length: 10 },
  { name: 'email', start: 444, length: 48 },
  { name: 'wealthtype', start: 493, length: 10 },
];
