import { FieldConfig } from './FieldConfig';

export const traderFileConfig: FieldConfig[] = [
  { name: 'aecode', start: 1, length: 10 },
  { name: 'aename', start: 11, length: 35 },
  { name: 'tdtypecode', start: 46, length: 1 },
  { name: 'aestatus', start: 47, length: 1 },
  { name: 'settdid', start: 48, length: 20 },
  { name: 'pswd', start: 68, length: 20 },
  { name: 'supervstd', start: 88, length: 10 },
  { name: 'tdgroupno', start: 98, length: 10 },
  { name: 'overcdlimit', start: 108, length: 13 },
  { name: 'shortsale', start: 121, length: 13 },
  { name: 'dailycdlimit', start: 134, length: 13 },
  { name: 'accumovercd', start: 147, length: 5 },
  { name: 'canchgacctno', start: 152, length: 1 },
  { name: 'canmktrans', start: 153, length: 1 },
  { name: 'canview', start: 154, length: 1 },
  { name: 'canapwithout', start: 155, length: 1 },
  { name: 'apptypecode', start: 156, length: 1 },
  { name: 'canmkshortsale', start: 157, length: 1 },
  { name: 'canmkcover', start: 158, length: 1 },
  { name: 'terminalscreen', start: 159, length: 1 },
  { name: 'orderseq', start: 160, length: 1 },
  { name: 'vieworderseq', start: 161, length: 1 },
  { name: 'cancelorder', start: 162, length: 1 },
  { name: 'aebranchcode', start: 163, length: 10 },
  { name: 'deptcode', start: 173, length: 10 },
  { name: 'teamcode', start: 183, length: 10 },
  { name: 'filter', start: 193, length: 18 },
];
