package constants

import "github.com/pi-financial/go-common/errorx"

var (
	// TODO: Remove this after migration to errorx
	// Success
	E000 = errorx.NewErrCodeMsg("E000", "successfully")
	E001 = errorx.NewErrCodeMsg("E002", "update successfully")

	ErrDecrypt                        = errorx.NewErrCodeMsg("SSO0001", "Failed to decryption")
	ErrUserNotFound                   = errorx.NewErrCodeMsg("SSO0002", "User not found")
	ErrUsernameExists                 = errorx.NewErrCodeMsg("SSO0003", "Username already exists")
	ErrDecryptPassword                = errorx.NewErrCodeMsg("SSO0004", "Failed to decrypt password")
	ErrUpdatePassword                 = errorx.NewErrCodeMsg("SSO0005", "Failed to update password")
	ErrGetCustomerInfo                = errorx.NewErrCodeMsg("SSO0006", "Failed to get customer info")
	ErrCreateUser                     = errorx.NewErrCodeMsg("SSO0007", "Failed to create user")
	ErrFindByUsername                 = errorx.NewErrCodeMsg("SSO0008", "Failed to find user by username")
	ErrEmailUsernameCannotLinkAccount = errorx.NewErrCodeMsg("SSO0009", "Email username cannot link account")
	ErrCardIDNotMatch                 = errorx.NewErrCodeMsg("SSO0010", "Card ID not match")
	ErrAccountIdNotFound              = errorx.NewErrCodeMsg("SSO0011", "Account_id not found")
	ErrSyncUser                       = errorx.NewErrCodeMsg("SSO0012", "Failed to sync user")

	ErrEmailNotFound           = errorx.NewErrCodeMsg("SSO0043", "Customer Info : Email not found")
	ErrPhoneNotFound           = errorx.NewErrCodeMsg("SSO0044", "Customer Info : Phone not found")
	ErrUpdateInfoUser          = errorx.NewErrCodeMsg("SSO0045", "Failed to update info user")
	ErrGetUserIdByCustcode     = errorx.NewErrCodeMsg("SSO0046", "Failed to get user id by custcode")
	ErrCreateAccount           = errorx.NewErrCodeMsg("SSO0047", "Failed to create account")
	ErrGetEfinUser             = errorx.NewErrCodeMsg("SSO0048", "Failed to get efin user")
	ErrMaskPhoneNumber         = errorx.NewErrCodeMsg("SSO0049", "Failed to mask phone number")
	ErrOtpRequestNotFound      = errorx.NewErrCodeMsg("SSO0050", "Login OTP request not found")
	ErrInvalidOtpCode          = errorx.NewErrCodeMsg("SSO0051", "Invalid OTP code")
	ErrPinSequence             = errorx.NewErrCodeMsg("SSO0052", "The PIN must not contain sequential or repeating numbers.")
	ErrCheckUsernameExists     = errorx.NewErrCodeMsg("SSO0053", "Failed to check username exists")
	ErrCustcodeExists          = errorx.NewErrCodeMsg("SSO0054", "Custcode already exists")
	ErrCreateSendLinkAccount   = errorx.NewErrCodeMsg("SSO0055", "Failed to create send link account")
	ErrSendEmail               = errorx.NewErrCodeMsg("SSO0056", "Failed to send email")
	ErrSendLinkAccountFindById = errorx.NewErrCodeMsg("SSO0057", "Failed to find send link by id")
	ErrUpdateSendLinkAccount   = errorx.NewErrCodeMsg("SSO0058", "Failed to update send link account")
	ErrLinkAccountUsed         = errorx.NewErrCodeMsg("SSO0059", "Link account is already used")
	ErrSendLinkAccountNotFound = errorx.NewErrCodeMsg("SSO0060", "Send link account not found")
	ErrInvalidClientID         = errorx.NewErrCodeMsg("SSO0061", "Client ID is invalid or incorrectly formatted. Please ensure it follows the required UUID format.")
	ErrFindByEmail             = errorx.NewErrCodeMsg("SSO0062", "Failed to find user by email")
	ErrGetAccountTabInfo       = errorx.NewErrCodeMsg("SSO0063", "Failed to get account tab info")
	ErrUpdateUserInfo          = errorx.NewErrCodeMsg("SSO0064", "Failed to update user info")
	ErrFailedToUpdatePassword  = errorx.NewErrCodeMsg("SSO0065", "Failed to update password")
	ErrAccountNotFound         = errorx.NewErrCodeMsg("SSO0066", "Account not found")
	ErrUserIdNotFound          = errorx.NewErrCodeMsg("SSO0067", "User ID not found")
	ErrIdCardNoNotMatch        = errorx.NewErrCodeMsg("SSO0068", "ID card number not match")
	ErrBirthdayNotMatch        = errorx.NewErrCodeMsg("SSO0069", "Birthday not match")
	ErrPasswordNotMatch        = errorx.NewErrCodeMsg("SSO0070", "Password not match")
	ErrSettradeAPIRequest      = errorx.NewErrCodeMsg("SSO0071", "Settrade API request failed")
	// Authentication & User Management Errors
	ErrInvalidRequest              = errorx.NewErrCodeMsg("SSO0012", "Invalid request")                                         // E100
	ErrValidationFailed            = errorx.NewErrCodeMsg("SSO0013", "Validation failed")                                       // E101
	ErrFailedToRetrieveAccounts    = errorx.NewErrCodeMsg("SSO0014", "Failed to retrieve accounts")                             // E102
	ErrFailedToCreateAccount       = errorx.NewErrCodeMsg("SSO0015", "Failed to create account")                                // E103
	ErrFailedToRegisterGuest       = errorx.NewErrCodeMsg("SSO0016", "Failed to register guest")                                // E104
	ErrInvalidUsernameOrPassword   = errorx.NewErrCodeMsg("SSO0017", "Invalid username or password")                            // E105
	ErrAccountLocked               = errorx.NewErrCodeMsg("SSO0018", "Account is locked due to too many failed login attempts") // E106
	ErrUnauthorizedOrInvalidUser   = errorx.NewErrCodeMsg("SSO0019", "Unauthorized or Invalid user, please login again")        // E107
	ErrInvalidDecryptPassword      = errorx.NewErrCodeMsg("SSO0020", "Invalid decrypt password")                                // E108
	ErrInvalidEncryptPassword      = errorx.NewErrCodeMsg("SSO0021", "Invalid encrypt password")                                // E109
	ErrDuplicateUsername           = errorx.NewErrCodeMsg("SSO0022", "Duplicate username")                                      // E110
	ErrDuplicatePhoneNumber        = errorx.NewErrCodeMsg("SSO0023", "Duplicate phone number")                                  // E111
	ErrFailedToUpdateLoginAttempts = errorx.NewErrCodeMsg("SSO0024", "Failed to update login attempts")                         // E112
	ErrFailedToResetLoginAttempts  = errorx.NewErrCodeMsg("SSO0025", "Failed to reset login attempts")                          // E113

	ErrEmailUsernameCannotSetPin              = errorx.NewErrCodeMsg("SSO0026", "Email username cannot set pin")                  // E115
	ErrPinNotSet                              = errorx.NewErrCodeMsg("SSO0027", "Pin is not set")                                 // E116
	ErrPinIncorrect                           = errorx.NewErrCodeMsg("SSO0028", "Pin is incorrect")                               // E117
	ErrUserNotFoundInPreloadedData            = errorx.NewErrCodeMsg("SSO0029", "User with username not found in preloaded data") // E118
	ErrSettradeAPIRequestFailed               = errorx.NewErrCodeMsg("SSO0030", "Settrade API request failed")                    // E119
	ErrFailedToGenerateSalt                   = errorx.NewErrCodeMsg("SSO0031", "Failed to generate salt")                        // E120
	ErrFailedToHashNewPassword                = errorx.NewErrCodeMsg("SSO0032", "Failed to hash new password")                    // E121
	ErrFailedToUpdatePinAndSalt               = errorx.NewErrCodeMsg("SSO0033", "Failed to update pin and salt for username")     // E122
	ErrFailedToDecryptUsername                = errorx.NewErrCodeMsg("SSO0034", "Failed to decrypt username")                     // E123
	ErrPasswordIncorrect                      = errorx.NewErrCodeMsg("SSO0035", "Password is incorrect")                          // E124
	ErrFailedToHashNewPin                     = errorx.NewErrCodeMsg("SSO0036", "Failed to hash new pin")                         // E125
	ErrOldPinIncorrect                        = errorx.NewErrCodeMsg("SSO0037", "Old pin is incorrect")                           // E126
	ErrFailedToHashToken                      = errorx.NewErrCodeMsg("SSO0038", "Failed to hash token")                           // E127
	ErrBiometricNotFound                      = errorx.NewErrCodeMsg("SSO0039", "Biometric not found")                            // E128
	ErrFailedToGenerateAccessToken            = errorx.NewErrCodeMsg("SSO0040", "Failed to generate access token")                // E129
	ErrFailedToGenerateRefreshToken           = errorx.NewErrCodeMsg("SSO0041", "Failed to generate refresh token")               // E130
	ErrInvalidBiometricToken                  = errorx.NewErrCodeMsg("SSO0042", "Invalid biometric token")                        // E131
	ErrFailedToUpdateIsVerify                 = errorx.NewErrCodeMsg("SSO0052", "Failed to update is_verify")                     // E132
	ErrFailedToUpdatePin                      = errorx.NewErrCodeMsg("SSO0072", "Failed to update pin")
	ErrTokenNotFound                          = errorx.NewErrCodeMsg("SSO0073", "Token not found")
	ErrDecryptUsername                        = errorx.NewErrCodeMsg("SSO0074", "Failed to decrypt username")
	ErrSendSettradeRequest                    = errorx.NewErrCodeMsg("SSO0075", "Failed to send settrade request")
	ErrFailedToHashPin                        = errorx.NewErrCodeMsg("SSO0076", "Failed to hash pin")
	ErrUpdateTokenStatus                      = errorx.NewErrCodeMsg("SSO0077", "Failed to update token status")
	ErrInvalidEmailFormat                     = errorx.NewErrCodeMsg("SSO0078", "Invalid email format")
	ErrGenerateUUIDToken                      = errorx.NewErrCodeMsg("SSO0079", "Failed to generate UUID token")
	ErrConvertStringToInt                     = errorx.NewErrCodeMsg("SSO0080", "Failed to convert string to int")
	ErrCreatePasswordReset                    = errorx.NewErrCodeMsg("SSO0081", "Failed to create password reset")
	ErrReadHTMLTemplate                       = errorx.NewErrCodeMsg("SSO0082", "Failed to read HTML template")
	ErrFailedToHashPassword                   = errorx.NewErrCodeMsg("SSO0083", "Failed to hash password")
	ErrTokenExpired                           = errorx.NewErrCodeMsg("SSO0084", "Token expired")
	ErrTokenAlreadyUsed                       = errorx.NewErrCodeMsg("SSO0085", "Token already used")
	ErrGenerateOtpToEmailForSetupFindById     = errorx.NewErrCodeMsg("SSO0086", "Failed to find generate otp to email for setup by id")
	ErrGenerateOtpToEmailForSetupCreate       = errorx.NewErrCodeMsg("SSO0087", "Failed to create generate otp to email for setup")
	ErrGenerateRandomUppercase                = errorx.NewErrCodeMsg("SSO0088", "Failed to generate random uppercase")
	ErrGenerateRandomNumbers                  = errorx.NewErrCodeMsg("SSO0089", "Failed to generate random numbers")
	ErrGenerateOtpToEmailForSetupUpdate       = errorx.NewErrCodeMsg("SSO0090", "Failed to update generate otp to email for setup")
	ErrReadEmailTemplate                      = errorx.NewErrCodeMsg("SSO0091", "Failed to read email template")
	ErrOtpExpired                             = errorx.NewErrCodeMsg("SSO0092", "OTP expired of Setup")
	ErrOtpCodeNotMatch                        = errorx.NewErrCodeMsg("SSO0093", "OTP code not match of Setup")
	ErrGenerateOtpToEmailForSetupUpdateStatus = errorx.NewErrCodeMsg("SSO0094", "Failed to update generate otp to email for setup status")
	ErrOtpUsed                                = errorx.NewErrCodeMsg("SSO0095", "OTP already used")
	ErrFindByPhoneNumber                      = errorx.NewErrCodeMsg("SSO0096", "Failed to find user by phone number")
	ErrPhoneNumberExists                      = errorx.NewErrCodeMsg("SSO0097", "Phone number already exists")
	ErrSendOtp                                = errorx.NewErrCodeMsg("SSO0098", "Failed to send OTP")
	ErrGenerateOtpToPhoneForSetupCreate       = errorx.NewErrCodeMsg("SSO0099", "Failed to create generate otp to phone for setup")
	ErrGenerateOtpToPhoneForSetupFindById     = errorx.NewErrCodeMsg("SSO0100", "Failed to find generate otp to phone for setup by id")
	ErrGenerateOtpToPhoneForSetupUpdateStatus = errorx.NewErrCodeMsg("SSO0101", "Failed to update generate otp to phone for setup status")
	ErrInvalidOtpRef                          = errorx.NewErrCodeMsg("SSO0102", "Invalid Otp ref")
	ErrFailedToSendSettradeRequest            = errorx.NewErrCodeMsg("SSO0103", "Failed to send settrade request")
	ErrFindByCardNo                           = errorx.NewErrCodeMsg("SSO0104", "Failed to find user by card no")
	ErrSendLinkAccountIsUsed                  = errorx.NewErrCodeMsg("SSO0105", "Failed Account already been linked")
	ErrEncryptText                            = errorx.NewErrCodeMsg("SSO0106", "Failed to encrypt text")
	ErrDecryptText                            = errorx.NewErrCodeMsg("SSO0107", "Failed to decrypt text")
	ErrCreateSyncToken                        = errorx.NewErrCodeMsg("SSO0108", "Failed to create sync token")
	ErrSyncTokenNotFound                      = errorx.NewErrCodeMsg("SSO0109", "Sync token not found")
	ErrUpdateSyncToken                        = errorx.NewErrCodeMsg("SSO0110", "Failed to update sync token")
	ErrSyncTokenUsed                          = errorx.NewErrCodeMsg("SSO0111", "Sync token is already used")
	ErrLogSessionNotFound                     = errorx.NewErrCodeMsg("SSO0112", "Log session not found")
	ErrSyncPasswordToSsoV1                    = errorx.NewErrCodeMsg("SSO0113", "Failed to sync password to sso v1")
	ErrUserInfoNotFound                       = errorx.NewErrCodeMsg("SSO0114", "User info not found")
	ErrAccountsListNotFound                   = errorx.NewErrCodeMsg("SSO0115", "Accounts list not found")
	ErrCustomerNotFound                       = errorx.NewErrCodeMsg("SSO0116", "Customer info not found")
	ErrFindByCustCode                         = errorx.NewErrCodeMsg("SSO0117", "Failed to find user by cust code")
	ErrFindByUserId                           = errorx.NewErrCodeMsg("SSO0118", "Failed to find user by user id")       // E119
	ErrFailedToSendSyncMembeToSsoV1           = errorx.NewErrCodeMsg("SSO0119", "Failed to send sync member to sso v1") // E120
	ErrUpdatePinAndSalt                       = errorx.NewErrCodeMsg("SSO0120", "Failed to update pin and salt")        // E121
	ErrUpdateEmail                            = errorx.NewErrCodeMsg("SSO0121", "Failed to update email")               // E122
	ErrOtpNotFound                            = errorx.NewErrCodeMsg("SSO0122", "OTP not found")                        // E123
	ErrUserIdNotMatch                         = errorx.NewErrCodeMsg("SSO0123", "User ID not match")                    // E124
	ErrFailedToUpdateUsername                 = errorx.NewErrCodeMsg("SSO0124", "Failed to update username")            // E125
	ErrUpdatePinFailed                        = errorx.NewErrCodeMsg("SSO0125", "Failed to update pin")
)
